### ISSUE TITLE
Installing SJLabel时报错

### ISSUE THREAD

**Issue by ElvistLui** [changsanjiang/SJVideoPlayer#10]
Installing SJLabel (1.1.0)

[!] Error installing SJLabel
[!] /usr/bin/git clone https://github.com/changsanjiang/SJLabel.git /var/folders/ht/r89947ls459fq5d1jz203s5h0000gn/T/d20180226-4771-ut4plr --template= --single-branch --depth 1 --branch v1.1.0

Cloning into '/var/folders/ht/r89947ls459fq5d1jz203s5h0000gn/T/d20180226-4771-ut4plr'...
warning: Could not find remote branch v1.1.0 to clone.
fatal: Remote branch v1.1.0 not found in upstream origin

**Comment by changsanjiang** [comment]
尝试一下 pod update , 那个Tag被我删掉了..

**Comment by ElvistLui** [comment]
是刚删的吗？我install失败后刷新了下你的项目网页发现项目更新了😂

**Comment by changsanjiang** [comment]
...... 这个项目下载下来, 应该可以直接跑起来. 不需要pod的.
