### ISSUE TITLE
能否设置缓冲到一定数据再播放

### ISSUE THREAD

**Issue by DockLle** [changsanjiang/SJVideoPlayer#103]
目前这个网络不好的时候体验很差，转，播放，转，播放，间隔太短，让人感觉卡顿，能否暴露出设置缓冲大小的api

**Comment by changsanjiang** [comment]
暂时先改下面这个属性吧, 看看效果

![image](https://user-images.githubusercontent.com/25744224/59988800-fdcab500-966e-11e9-8840-834f26c5cd75.png)
