### ISSUE TITLE
集成进去之后，影响pop动画，怎么解决？

### ISSUE THREAD

**Issue by tipshot** [changsanjiang/SJVideoPlayer#106]
集成进去之后，影响nav的pop动画，正常的pop是栈顶控制器从屏幕左侧滑向右侧，但是集成之后变成从屏幕右侧滑向左侧了，怎么解决？

**Comment by changsanjiang** [comment]
集成的是几版本的呢?

**Comment by tipshot** [comment]
如何查看版本？

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/60155522-fd701c80-981c-11e9-9bed-2a9837389024.png)

**Comment by tipshot** [comment]
![image](https://user-images.githubusercontent.com/18547353/60155618-3ad4aa00-981d-11e9-95bd-b54ee31393e6.png)
