### ISSUE TITLE
如何修改控制层收起后底部的Progress高度

### ISSUE THREAD

**Issue by Z-Victory** [changsanjiang/SJVideoPlayer#107]
![IMG_6DC37E078A66-1](https://user-images.githubusercontent.com/15643266/60232518-6d3edf80-98cf-11e9-8875-1b18aaa48aac.jpeg)

**Comment by changsanjiang** [comment]
修改高度没有暴露接口. 先改一下源码吧, 下个版本我添加到配置类里面: 

![image](https://user-images.githubusercontent.com/25744224/60232723-0a017d00-98d0-11e9-8eca-b7369c9c307f.png)

![image](https://user-images.githubusercontent.com/25744224/60232747-14237b80-98d0-11e9-9305-ef12ae935161.png)

**Comment by changsanjiang** [comment]
@Z-Victory , 最新的版本(2.6.3)可以直接设置了

```Objective-C
_player.defaultEdgeControlLayer.bottomProgressSliderHeight = 1;
```
