### ISSUE TITLE
kvo偶发崩溃

### ISSUE THREAD

**Issue by allanGoldZhiKang** [changsanjiang/SJVideoPlayer#108]
![1561619680439](https://user-images.githubusercontent.com/29418848/60245069-58257900-98ee-11e9-9f92-0506eaa85151.jpg)
这个移除kvo为什么没有trycatch

**Comment by changsanjiang** [comment]
那个地方是通过_factor来控制的, 为空就说明移除过了, 是安全的. 
你这个应该是很旧的版本.  奔溃的原因不在这里, 是多线程操作集合(sj_observerhashSet)奔溃的.

**Comment by allanGoldZhiKang** [comment]
> 那个地方是通过_factor来控制的, 为空就说明移除过了, 是安全的.
> 你这个应该是很旧的版本. 奔溃的原因不在这里, 是多线程操作集合(sj_observerhashSet)奔溃的.

您说的这个多线程操作的问题修复了吗，我刚又重新拉了新的pod还是这样啊

**Comment by changsanjiang** [comment]
哦哦, 你应该是指定 Player的版本号了吧, 旧版本依赖的那个库我没有更新. 我去更新一下. 

SJObserverHelper这个库我合并到了 `SJUIKit/ObserverHelper` 中了, 新的播放器现在依赖的是SJUIKit了.

**Comment by allanGoldZhiKang** [comment]
> 哦哦, 你应该是指定 Player的版本号了吧, 旧版本依赖的那个库我没有更新. 我去更新一下.
> 
> SJObserverHelper这个库我合并到了 `SJUIKit/ObserverHelper` 中了, 新的播放器现在依赖的是SJUIKit了.

原来这样啊，我说怎么拉不到最新的，我觉得应该把这种结构变换在readme里应该体现一下，这样对于使用老版本会有些帮助

**Comment by changsanjiang** [comment]
嗯呢, 以后我注意一下👌.  

Helper那个我刚才更新了, 如果还有问题的话我们加QQ聊吧 1779609779
