### ISSUE TITLE
Touch on VideoPlayer

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJVideoPlayer#11]
Hi there,
I add video player to viewcontroller have tableview, when i click full screen, i can't touch on video player. just touch on my viewcontroller. Please tell me why?
My ViewController in a PageViewController , and PageViewController in a TabBarController.
Thanks

**Comment by anhnt92** [comment]
Your demo haven't.
I can't touch on video player to show control when it full screen. Instead, i touch on my view controller.
Touch through.

**Comment by changsanjiang** [comment]
I [intercepted](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/master/SJBaseVideoPlayer/SJBaseVideoPlayer.m) the click event by gesture.( line 387 )

**Comment by anhnt92** [comment]
What do you mean?

**Comment by anhnt92** [comment]
And please tell how i use delegate to know status video on my viewcontroller?

**Comment by changsanjiang** [comment]
I am sorry, my English is not very good.
1. The first question, I don't know why.
2. State change will call this [delegate method](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/master/SJBaseVideoPlayer/SJBaseVideoPlayer.h). At line 252.

**Comment by HaozhongChen** [comment]
tabbarVC里面有个pageviewController，pageViewController里面有个VC，VC里面有个tabview，你的播放器全屏以后点击没反应

**Comment by changsanjiang** [comment]
OK, 这问题不好说, 得看他怎么旋转成全屏的, 是加在window上, 还是其他的方式. 
OK, This problem is not easy to say, depends on how he rotated into full screen, is added to the window, or other ways.

**Comment by anhnt92** [comment]
i have added with [self addSubview]

**Comment by changsanjiang** [comment]
If your controller supports rotation, check the view hierarchy to see if the player is obscured by other transparent views.
Or check the player below the view all rotate to full screen?

I recommend adding the player to the window layer when u click Full Screen.

**Comment by anhnt92** [comment]
"I recommend adding the player to the window layer when u click Full Screen."
How to i do it? Thanks

**Comment by changsanjiang** [comment]
I wrote a [demo](https://github.com/changsanjiang/SJOrentationObserver), you can try to use it to rotate the player.
