### ISSUE TITLE
怎么记录当前播放时间，下次进入续播？

### ISSUE THREAD

**Issue by TongCong12138** [changsanjiang/SJVideoPlayer#110]
大神，你好，我现在想做一个续播功能，这个肯定得接FMDB，想知道用户关闭了当前APP或者人为返回的时候怎么记录当前播放时间，然后下次进来接着上次时间播放

**Comment by changsanjiang** [comment]
如果不是特别准要的话, 可以在资源Dealloc的时候, 记录一下. 
```
  player.assetDeallocExeBlock = ^{ /.../ }
```

**Comment by changsanjiang** [comment]
可以在每个资源dealloc的时候, 获取一下播放器的当前时间, 记录起来.

**Comment by TongCong12138** [comment]
程序突然被杀死，也走这个方法吗？

**Comment by changsanjiang** [comment]
不会, 只会在正常的dealloc时触发
