### ISSUE TITLE
ipad端集成后，强制全屏之后，点击右下角全屏按钮两次，出现竖屏，并且返回按钮点击百分之五十的概率无法返回（点击没有相应）。

### ISSUE THREAD

**Issue by tipshot** [changsanjiang/SJVideoPlayer#111]
ipad端集成后，强制全屏之后，点击右下角全屏按钮两次，出现竖屏，并且返回按钮点击百分之五十的概率无法返回（点击没有相应）。现在想要如何把返回按钮增大，并且返回按钮不隐藏，以及去掉全屏按钮。请问如何实现？

**Comment by changsanjiang** [comment]
触发点击区域一般大小是 49 * 49, 这个方法应该足够大了.  你那边方便截个接入的代码吗? 发我QQ吧 1779609779

另外, 让返回按钮一直显示, 可以如下设置按钮常驻:

```
_player.showResidentBackButton = YES;
```

**Comment by tipshot** [comment]
好的，已添加你的qq。顺便说两个个问题：
1、返回按钮常驻之后，返现返回按钮点击第一次没有任何相应，点击第二次才会返回。每次必现这中情况。
2、我设置videoPlayer.showMoreItemForTopControlLayer = YES;之后，并没有现实更多设置按钮。
