### ISSUE TITLE
全屏时发现下半部分屏幕点击无效果

### ISSUE THREAD

**Issue by trembleCat** [changsanjiang/SJVideoPlayer#119]
如题，controller会自动跟随_player旋转，不需要像之前那样手动设置了。但是全屏后发现下半部分屏幕点击无效果。

**Comment by changsanjiang** [comment]
你好, 你那边的手机系统是哪个版本的呢?

**Comment by trembleCat** [comment]
iOS12.3.1的系统版本



            
            
                
                    
                            
                                
                            
                            
                                1424410506
                            
                    
                        
                            
                                    邮箱：1424410506@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            在2019年07月15日 12:19，changsanjiang 写道： 你好, 你那边的手机系统是哪个版本的呢?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/changsanjiang/SJVideoPlayer/issues/119?email_source=notifications\u0026email_token=AIELLL6367LCSUQUUXE3UBLP7P3EZA5CNFSM4IDS575KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ4VXRA#issuecomment-511269828",

"url": "https://github.com/changsanjiang/SJVideoPlayer/issues/119?email_source=notifications\u0026email_token=AIELLL6367LCSUQUUXE3UBLP7P3EZA5CNFSM4IDS575KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ4VXRA#issuecomment-511269828",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by trembleCat** [comment]
iOS12.3.1的系统版本

**Comment by trembleCat** [comment]
发现使用Simulator也会出现该问题，以下是使用代码：
     _player = [SJVideoPlayer player];
    [self.view addSubview:_player.view];
    [_player.view mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view.mas_top).offset(200);
        make.left.right.equalTo(self.view).offset(0);
        make.height.equalTo(@300);
    }];
    SJVideoPlayerURLAsset *asset1 = [[SJVideoPlayerURLAsset alloc]initWithTitle:@"视频1" URL:[NSURL URLWithString:@"http://vfx.mtime.cn/Video/2019/03/19/mp4/190319222227698228.mp4"] playModel:[SJPlayModel new]]
    _player.URLAsset = asset1;

**Comment by trembleCat** [comment]
昨天的更新增加了SJVCRotationManager.h文件，按照使用方法解决了下半部分屏幕点击无效果的问题。但是全屏时会有一秒的黑屏卡顿。于是发现写了这两句就会有黑屏卡顿，
    _rotationManager = [[SJVCRotationManager alloc] initWithViewController:self];
    _player.rotationManager = _rotationManager;
将这两句注释掉就可以完美的全屏，并且全屏时点击正常。其他copy代码不变，只是不要加上面这两句代码。手机系统12.3.1，不知道其他手机是否有这种问题。

**Comment by changsanjiang** [comment]
你好, 方便发个视图控制器的 .m文件吗?

**Comment by trembleCat** [comment]
您好，谢谢您的回复，这是我的.m文件。还有一个问题是，如果直接pod 'SJVideoPlayer' 然后 pod install的话好像并不是最新版的哦。
