### ISSUE TITLE
Error when add controlLayerDelegate

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJVideoPlayer#12]
When i add controlLayerDelegate, i can't touch to show control view.

**Comment by changsanjiang** [comment]
Have you set `controLayerDataSource` yet?

**Comment by anhnt92** [comment]
I set, and it work.
But problem is it not show control view like slider when i touch on.

**Comment by changsanjiang** [comment]
you need to implement the  delegateMethod. 
`- (void)controlLayerNeedAppear:(SJVideoPlayer *)videoPlayer` & `- (void)controlLayerNeedDisappear:(SJVideoPlayer *)videoPlayer`.

Can refer to the [default control layer](https://github.com/changsanjiang/SJVideoPlayer/blob/28a45feaf0b6c69a769d76ad0c5cc1704cc40dee/SJVideoPlayer/SJVideoPlayerDefaultControlView.m#L643). At line 643.

**Comment by changsanjiang** [comment]
Internal view display is controlled by yourself, the player does not handle it.

**Comment by anhnt92** [comment]
Thanks, Its work.
