### ISSUE TITLE
您好，ipad13.0播放.m3u8流，退出当前播放控制器后崩溃(在移除观察者处崩溃 NSObject+SJObserverHelper.m文件第164行)

### ISSUE THREAD

**Issue by suwenxiao** [changsanjiang/SJVideoPlayer#120]
ipad13.0播放.m3u8流，退出当前播放控制器后崩溃(在移除观察者处崩溃 NSObject+SJObserverHelper.m文件第164行) 
- (void)dealloc {
    @try {
        NSLog(@"----%@----", self.keyPath);
     ###    [_target removeObserver:self forKeyPath:_keyPath];  ##  这里崩溃##
    } @catch (NSException *__unused exception) { }
}

**Comment by changsanjiang** [comment]
收到

**Comment by suwenxiao** [comment]
您好，刚我做了一个判空处理，就ok了，不知道是否会对框架内部造成影响
- (void)dealloc {
    @try {
        NSLog(@"----%@----", self.keyPath);
        **if (!self.keyPath) {return;} ## 此处加了一个keypath为空的处理##**
        [_target removeObserver:self forKeyPath:_keyPath];
    } @catch (NSException *__unused exception) { }
}

**Comment by changsanjiang** [comment]
@suwenxiao 先更到最新的版本吧

**Comment by suwenxiao** [comment]
已解决，非常感谢...
