### ISSUE TITLE
Option to disable autoplay after seek

### ISSUE THREAD

**Issue by PhilipDukhov** [changsanjiang/SJVideoPlayer#121]
Another nice feature for me is to disable autoplay after seeking. So in case when video wasn't playing before I started seeking with pan gesture I don't want it to start. The code that starts playing right now is in [SJEdgeControlLayer _draggingDidEnd].

**Comment by changsanjiang** [comment]
Hello @PhilipDukhov , Now you can use it in the new version(2.6.3) to disable autoplay:

```Objective-C
_player.resumePlaybackWhenPlayerHasFinishedSeeking = NO;
```
