### ISSUE TITLE
播放问题 Error Domain=AVFoundationErrorDomain Code=-11800

### ISSUE THREAD

**Issue by xieweicai** [changsanjiang/SJVideoPlayer#124]
https://cdn.1home.online/video/ec63f30db770e60ca620f7e0f76ca164.mp4

**Comment by xieweicai** [comment]
> https://cdn.1home.online/video/ec63f30db770e60ca620f7e0f76ca164.mp4

**Comment by WM520** [comment]
怎么解决的额？

**Comment by mafiaIOS** [comment]
你好, 我也遇到这个问题了, 请问咋解决的AVFoundationErrorDomain Code=-11800
