### ISSUE TITLE
全屏后下半屏失效  更新2.6.4的跟git下载的好像结构不一样

### ISSUE THREAD

**Issue by zxr123** [changsanjiang/SJVideoPlayer#127]

**Comment by zxr123** [comment]
看到也有人提出 但是我没有找到如何解决下半屏无法点击的问题

**Comment by changsanjiang** [comment]
是在真机上吗? 在模拟器中 有同样的问题吗?

**Comment by zxr123** [comment]
真机下半身瘫痪 机型iphone6  系统版本:11.41  . 测试机全屏后全身瘫痪 模拟器XR 版本:12.2

**Comment by changsanjiang** [comment]
我这边是 Xcode 10.3, XR 12.4 没发现这个Bug.  加个QQ吧, 1779609779, 我们QQ聊

**Comment by zxr123** [comment]
问题解决 谢谢帮忙解决
