### ISSUE TITLE
Disable double touch to pause

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJVideoPlayer#13]
How to i disable double touch to pause ?

**Comment by anhnt92** [comment]
And have one more  problem when i add delegate controller, the timer video is 00:00/00:00.

**Comment by changsanjiang** [comment]
OK, Please wait 10 m.
1. The first issue,  I just added [disableGestureTypes](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/b8242246416c935dd6b05fe88c078a20474a066a/SJBaseVideoPlayer/SJBaseVideoPlayer.h#L136). At line 136.
Is pushing to trunk, please wait.

2. Default is 00:00/00:00.... When playing, it will call `- (void)videoPlayer:(SJBaseVideoPlayer *)videoPlayer currentTime:(NSTimeInterval)currentTime currentTimeStr:(NSString *)currentTimeStr totalTime:(NSTimeInterval)totalTime totalTimeStr:(NSString *)totalTimeStr`.

**Comment by anhnt92** [comment]
what about slider, button play ? they not change state.

**Comment by changsanjiang** [comment]
Sorry, I do not quite understand what you mean.
When calling [play || pause || stop] will go to the implementation of the delegate method. `- (void)videoPlayer:(SJBaseVideoPlayer *)videoPlayer stateChanged:(SJVideoPlayerPlayState)state`
