### ISSUE TITLE
视频请求头加密的处理

### ISSUE THREAD

**Issue by chenchao01** [changsanjiang/SJVideoPlayer#131]
大佬，你好，我想给视频加密，以前是这样处理的，在你的框架里，应该怎么改呢

       NSMutableDictionary * headers = [NSMutableDictionary dictionary];
        [headers setObject:@"***"forKey:@"User-Agent"];
        AVURLAsset* urlAsset = [AVURLAsset URLAssetWithURL:[NSURL URLWithString:self.videoUrl] options:@{@"AVURLAssetHTTPHeaderFieldsKey" : headers}];
        // 初始化playerItem
        AVPlayerItem *playerItem = [AVPlayerItem playerItemWithAsset:urlAsset];

**Comment by changsanjiang** [comment]
初始化资源用下面这几个方法:

![image](https://user-images.githubusercontent.com/25744224/62990404-733c5000-be7e-11e9-8685-b1cf387e8a10.png)
