### ISSUE TITLE
怎么做类似抖音上下滑动播放的效果

### ISSUE THREAD

**Issue by TongCong** [changsanjiang/SJVideoPlayer#132]
大哥，想用你这个做类似抖音那种全屏上下滑动的效果，怎么弄啊？我现在就是很简单的将播放器放在cell里面，然后滑动，但是会触发亮度手势，取消手势，但是没效果。。。实在不知道怎么弄

**Comment by changsanjiang** [comment]
我更了一个 CollectionView的Demo, 可以参考一下.
