### ISSUE TITLE
在控制层同时添加多个view最后一个总是会覆盖上一个

### ISSUE THREAD

**Issue by Costword** [changsanjiang/SJVideoPlayer#133]
例如添加view1 和view2 无论是否设置相同的tag，view2总是会覆盖view1，求解

**Comment by changsanjiang** [comment]
贴一下代码吧, 看看怎么用的

**Comment by Costword** [comment]
`-(void)addCollect{
    //添加第一个view
    UIView * collectBaseView = [[UIView alloc]initWithFrame:CGRectMake(0,0,120,30)];
    SJEdgeControlButtonItem *collectItem = [[SJEdgeControlButtonItem alloc] initWithCustomView:collectBaseView tag:SJTestCustom2ItemTag];
    collectItem.customView.backgroundColor = [UIColor greenColor];
    [_player.defaultEdgeControlLayer.topAdapter addItem:collectItem];
    
    //添加第二个view
    UIView * moreBaseView = [[UIView alloc]initWithFrame:CGRectMake(0,0,120,30)];
    SJEdgeControlButtonItem *itemMore = [[SJEdgeControlButtonItem alloc] initWithCustomView:moreBaseView tag:SJTestCustom2ItemTag];
    itemMore.customView.backgroundColor = [UIColor blueColor];
    [_player.defaultEdgeControlLayer.topAdapter addItem:itemMore];
    
}
`
就是连续添加两个view的时候在[_player.defaultEdgeControlLayer.topAdapter reload];调用之前显示是正常的，调用后就会把第一个隐藏了只显示最后一个

**Comment by changsanjiang** [comment]
哦哦, 这个是之前的bug,  更新一下就好了

**Comment by Costword** [comment]
好，谢谢～
