### ISSUE TITLE
tableivew cell 位置播放

### ISSUE THREAD

**Issue by CHparis** [changsanjiang/SJVideoPlayer#136]
设置
config.autoplayPosition = SJAutoplayPositionMiddle;
的时候，用demo在iPhonex上跑起来，会发现是播放屏幕底部的视频而不是屏幕中间的视频，请问这个有什么解决办法么？

**Comment by changsanjiang** [comment]
是个bug, [这个地方改成 offset = 0 吧](https://github.com/changsanjiang/SJVideoPlayer/blob/886c60e218983ebf3b4f153fc79c404eee85beac/Example/Pods/SJBaseVideoPlayer/SJBaseVideoPlayer/UIScrollView%2BListViewAutoplaySJAdd.m#L188)

![image](https://user-images.githubusercontent.com/25744224/63743964-7c8ed900-c8d0-11e9-9802-19e402e097fc.png)

**Comment by CHparis** [comment]
感谢，改成0确实可以解决屏幕中间的问题，但是会有另外一个体验问题，就是当正在播放中的cell滑动出去一部分的时候，还是会播放中，中间位置的视频cell已经就位了，但是没有开始播放。
还有一个问题问题是想咨询一下，如果一个tableview中有的是视频有的事普通cell，直接用demo中的ListViewAutoplayViewController的写法会有问题么？

**Comment by changsanjiang** [comment]
我那个处理是在 完全滑出的时候, 才去播放其他cell的. 
正常配置就行, 多种cell不影响. 

这个库的scrollView中自动播放是个简单版的, 这块需求不一样的话, 最好自己实现一个.

**Comment by CHparis** [comment]
好的
