### ISSUE TITLE
解码失败，大神看看原因啊

### ISSUE THREAD

**Issue by WM520** [changsanjiang/SJVideoPlayer#138]
SJVideoPlayerLog: Generate Preview Image Failed! error: Error Domain=AVFoundationErrorDomain Code=-11821 "无法解码" UserInfo={NSLocalizedFailureReason=媒体数据无法被解码，可能已损坏。, NSLocalizedDescription=无法解码, NSUnderlyingError=0x1c0646c90 {Error Domain=NSOSStatusErrorDomain Code=-12911 "(null)"}}
2019-08-27 15:49:08.305706+0800 SquirrelsStore-Enterprise[1096:788877] [MC] Invalidating cache

**Comment by changsanjiang** [comment]
视频文件损坏了吧

**Comment by WM520** [comment]
https://snt-oss-yunzao.oss-cn-hangzhou.aliyuncs.com/2019/8/8/e5dc4afc-675f-48bb-ba4b-ca7452bf90fb.mp4    安卓可以播放的，mac电脑也可以，大神求助

**Comment by WM520** [comment]
SJBaseVideoPlayer<0x13fd233b0>.SJVideoPlayerPlayStatus.Prepare

2019-08-27 16:30:01.648271+0800 SquirrelsStore-Enterprise[1096:804638] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}
2019-08-27 16:30:01.688527+0800 SquirrelsStore-Enterprise[1096:779423] [Common] _BSMachError: port 14f2f; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2019-08-27 16:30:02.470104+0800 SquirrelsStore-Enterprise[1096:779423] SJVideoPlayerLog: Generate Preview Image Failed! error: Error Domain=AVFoundationErrorDomain Code=-11821 "无法解码" UserInfo={NSLocalizedFailureReason=媒体数据无法被解码，可能已损坏。, NSLocalizedDescription=无法解码, NSUnderlyingError=0x1c4c50ad0 {Error Domain=NSOSStatusErrorDomain Code=-12911 "(null)"}}

**Comment by WM520** [comment]
- (void)_generatePreviewImagesIfNeededForVideoPlayer:(__kindof SJBaseVideoPlayer *)videoPlayer videoSize:(CGSize)size {
    if ( _videoPlayer.useFitOnScreenAndDisableRotation ) return;
    if ( videoPlayer.URLAsset.isM3u8 ) return;
    if ( !_generatePreviewImages ) return;
    if ( _hasBeenGeneratedPreviewImages ) return;
    CGSize previewItemSize = CGSizeMake(150, 150);
    __weak typeof(self) _self = self;
    [videoPlayer generatedPreviewImagesWithMaxItemSize:previewItemSize completion:^(SJBaseVideoPlayer * _Nonnull player, NSArray<id<SJVideoPlayerPreviewInfo>> * _Nullable images, NSError * _Nullable error) {
        __strong typeof(_self) self = _self;
        if ( !self ) return ;
        if ( error ) {
#ifdef DEBUG
            NSLog(@"SJVideoPlayerLog: Generate Preview Image Failed! error: %@", error);
#endif
        }
        else {
            self.hasBeenGeneratedPreviewImages = YES;
            [self _updateItemsFor_TopAdapterIfNeeded:self.videoPlayer];
            self.previewView.previewImages = images;
        }
    }];
}   这个地方报的

**Comment by changsanjiang** [comment]
视频转下码吧.  有声音无画面, 可能编码方式不支持.

**Comment by WM520** [comment]
我试试,您的框架支持MP4吧？

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/63756876-b4efe080-c8eb-11e9-8f9a-25c3fa82240d.png)

**Comment by WM520** [comment]
这个视频就是mp4的啊，你那边有声音吗，我用你框架，声音都听不到啊

**Comment by WM520** [comment]
编码格式为MPG-4的报解析失败

**Comment by sfssqs** [comment]
@WM520 问题解决了吗   遇到类似的情况  感觉ios系统解码不兼容

**Comment by ThisFriend** [comment]
> @WM520 问题解决了吗 遇到类似的情况 感觉ios系统解码不兼容

解决了么哥们

**Comment by changsanjiang** [comment]
试试切换下ijkplayer : https://github.com/changsanjiang/SJVideoPlayer/issues/164

**Comment by changsanjiang** [comment]
@ThisFriend

**Comment by ThisFriend** [comment]
> 试试切换下ijkplayer : #164

[!] CocoaPods could not find compatible versions for pod "SJBaseVideoPlayer/IJKPlayer":
  In Podfile:
    SJBaseVideoPlayer/IJKPlayer

Specs satisfying the `SJBaseVideoPlayer/IJKPlayer` dependency were found, but they required a higher minimum deployment target.

emmmm。。。  git clone的地址呢

**Comment by ThisFriend** [comment]
> 试试切换下ijkplayer : #164

platform:ios, "9.0"   ？  我之前一直是8.0的，需要改成9.0？ 我试试先

**Comment by ThisFriend** [comment]
> > 试试切换下ijkplayer : #164
> 
> platform:ios, "9.0" ？ 我之前一直是8.0的，需要改成9.0？ 我试试先

ok, 9.0可以下载
