### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJVideoPlayer#14]
Video full screen, how i scale it to small in my viewcontroller ?

**Comment by changsanjiang** [comment]
Call [this method](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/3038aa7736ddffca7d105641aae76763ce36b2b1/SJBaseVideoPlayer/SJBaseVideoPlayer.h#L173). At Line 173.
