### ISSUE TITLE
如何给basePlayer设置父视图？

### ISSUE THREAD

**Issue by LukeChow** [changsanjiang/SJVideoPlayer#145]
我找了半天也没找到如何把这个BasePlayer显示到我的superview上，只有显示到tableviewcell等等上面的方法，但是我只要显示在一个普通的view上，您说只需要[SJPlayModel new]这样就行了，可是我不明白这样做并没办法显示到我的superview上啊？请指教

**Comment by changsanjiang** [comment]
普通视图上播放不用设置playModel, 直接把 player.view 添加到自己的视图上.
