### ISSUE TITLE
iOS 旋转的配置看这里 (2.6.5版本及以后)

### ISSUE THREAD

**Issue by changsanjiang** [changsanjiang/SJVideoPlayer#148]
遇到点击无法触发旋转的请看这里.

**Comment by changsanjiang** [comment]
Demo: https://github.com/changsanjiang/SJVideoPlayer/files/3550253/swift-TestPlayer.zip

### 第一步: 

![image.png](https://upload-images.jianshu.io/upload_images/2318691-fb998d6ea98b6f2c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

___

### 第二步:
 
![image.png](https://upload-images.jianshu.io/upload_images/2318691-295ad6d0ef5c63ad.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


### 第三步:

```Objective-C
@implementation UIViewController (RotationControl)
- (BOOL)shouldAutorotate {
#ifdef DEBUG
    NSLog(@"%d - %s", (int)__LINE__, __func__);
#endif
    return NO;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
#ifdef DEBUG
    NSLog(@"%d - %s", (int)__LINE__, __func__);
#endif
    return UIInterfaceOrientationMaskPortrait;
}

@end


@implementation UITabBarController (RotationControl)
- (UIViewController *)sj_topViewController {
    if ( self.selectedIndex == NSNotFound )
        return self.viewControllers.firstObject;
    return self.selectedViewController;
}

- (BOOL)shouldAutorotate {
    return [[self sj_topViewController] shouldAutorotate];
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return [[self sj_topViewController] supportedInterfaceOrientations];
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return [[self sj_topViewController] preferredInterfaceOrientationForPresentation];
}
@end

@implementation UINavigationController (RotationControl)
- (BOOL)shouldAutorotate {
    return self.topViewController.shouldAutorotate;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return self.topViewController.supportedInterfaceOrientations;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    return self.topViewController.preferredInterfaceOrientationForPresentation;
}

- (nullable UIViewController *)childViewControllerForStatusBarStyle {
    return self.topViewController;
}

- (nullable UIViewController *)childViewControllerForStatusBarHidden {
    return self.topViewController;
}
@end

```

**Comment by szdkkk** [comment]
`self.windowLevel = UIApplication.sharedApplication.keyWindow.windowLevel + 1;// UIWindowLevelNormal;`
SJFullscreenModeWindow的windowLevel属性应该设置成比host app的keyWindow高，不然全屏之后是看不到播放window的。

**Comment by szdkkk** [comment]
另外还有个问题，UITabBarController的某一个子tab包含播放器的时候，如果正在显示的tab是不包含播放器，旋转屏幕也会呼出全屏播放器界面。

**Comment by changsanjiang** [comment]
@szdkkk  调一下这个几个方法试试. 
![image](https://user-images.githubusercontent.com/25744224/64679060-793d4500-d4ad-11e9-9c4e-b604d72d48dc.png)

**Comment by liuxz656** [comment]
貌似这个并没有起什么作用 点击全屏按钮 视图旋转不了

**Comment by frozenthrone** [comment]
第三部swift版本应该怎么加

**Comment by m3u8playlist** [comment]
这样配置是不是app界面只能竖屏了

**Comment by changsanjiang** [comment]
横屏的App参考ipad Demo

**Comment by jieshaoli** [comment]
配置完之后好像还是没有用啊。 点击全屏之后，整个屏幕点击失效了。

**Comment by ChanJaWe** [comment]
按照配置改好了项目，present推出视频控制器，返回时项目崩溃了
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2020-03-31 17:07:53.453080 家校安[6473:2905624] *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'preferredInterfaceOrientationForPresentation must return a supported interface orientation!'
*** First throw call stack:
(0x1817841c0 0x1801bc55c 0x181784108 0x1876c2418 0x187f8f65c 0x18791865c 0x18793bff8 0x1876f92cc 0x18769fe30 0x18769fbf0 0x18793b250 0x18769f964 0x10025d288 0x10025d644 0x10021b224 0x100213c6c 0x100219e48 0x1876019a0 0x187601920 0x1875ebdd0 0x18760120c 0x187b92120 0x187b8e1b8 0x1817317dc 0x18172f40c 0x18172f89c 0x18165e048 0x1830e1198 0x187637818 0x187632550 0x10009991c 0x1806405b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
请问应该怎么改？

**Comment by DarielChen** [comment]
![Snip20200411_61](https://user-images.githubusercontent.com/16555020/79044995-36a63b80-7c3b-11ea-975a-816f76dfde39.png)


横屏Demo有问题，这个问题项目中也存在，就是当非横屏状态下app退到后台，然后再回到前台app再切换屏幕方向，会出现上述状态

**Comment by changsanjiang** [comment]
![test](https://user-images.githubusercontent.com/25744224/79046494-d9fb4e80-7c43-11ea-9412-462065022d33.gif)

@DarielChen 奇怪了...我这里没出现这个bug... 可以提供一下详细的操作吗, 或者加QQ群录个小视频看看

**Comment by DarielChen** [comment]
[OC_demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4466487/OC_demo.zip)

我这个问题主要是按照你提供的方式配置了全屏的操作，但我想禁止自动横屏，只在点击自动全屏时才能横屏但不行，你能帮我看下么，到底啥问题哦

**Comment by Ccalary** [comment]
DarielChen :我这个问题主要是按照你提供的方式配置了全屏的操作，但我想禁止自动横屏，只在点击全屏按钮时才能横屏但不行，你能帮我看下么，到底啥问题哦

**Comment by DarielChen** [comment]
@Ccalary 用交换方法重新实现一下我上面列的两个方法

**Comment by Ccalary** [comment]
@DarielChen 交换方法重新实现，不太明白，可以详细说说吗

**Comment by DarielChen** [comment]
@Ccalary 

```objective_c
+ (void)load{
    NSError *err;
    [self jr_swizzleMethod:@selector(shouldAutorotate) withMethod:@selector(tm_shouldAutorotate) error:&err];
    [self jr_swizzleMethod:@selector(supportedInterfaceOrientations) withMethod:@selector(tm_supportedInterfaceOrientations) error:&err];
}

- (BOOL)tm_shouldAutorotate {
    return NO;
}

- (UIInterfaceOrientationMask)tm_supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskPortrait;
}
```

**Comment by YangYueFan** [comment]
第一次全屏动画卡顿是什么原因，跟没有动画一样，后面都正常

**Comment by chocolate1128** [comment]
你好，我设置了自动选择
当播放竖屏拍摄的视频时(Width<Height), 在点击全屏按钮之后, 没有问题。
当播放横屏拍摄的视频时(Width>Height), 在点击全屏按钮之后, 全屏播放的view没有出现，或者说是有一层透明的view盖在APP界面的上面，所有手势都没用，有遇到过这个情况吗

**Comment by changsanjiang** [comment]
@chocolate1128 前三步的配置需添加上

**Comment by changsanjiang** [comment]
@YangYueFan 可能是第一次旋转时, 执行的任务比较多卡顿了, 后续我再看看

**Comment by chocolate1128** [comment]
[测试全屏播放.mp4.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4584754/mp4.zip)
就是这样的情况，也不知道哪里出了问题

**Comment by chocolate1128** [comment]
找到问题了，有一个分类把supportedInterfaceOrientationsForWindow重写了，现在没问题了

**Comment by H4AER** [comment]
配置完旋转的时候不走下面的两个方法 @changsanjiang 
@implementation UIViewController (RotationControl)
- (BOOL)shouldAutorotate { 
    return NO;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}

**Comment by lianxiaoshuo** [comment]
> [OC_demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4466487/OC_demo.zip)
> 
> 我这个问题主要是按照你提供的方式配置了全屏的操作，但我想禁止自动横屏，只在点击全屏按钮时才能横屏但不行，你能帮我看下么，到底啥问题哦
> 
> ```
> @implementation UIViewController (RotationControl)
> - (BOOL)shouldAutorotate { 
>     return NO;
> }
> 
> - (UIInterfaceOrientationMask)supportedInterfaceOrientations {
>     return UIInterfaceOrientationMaskPortrait;
> }
> ```
> 
> 是这两个方法不调用？好奇怪

同问这个

**Comment by changsanjiang** [comment]
@lianxiaoshuo  TestController 加上这个

```Objective-C
@implementation TMTestController

- (BOOL)shouldAutorotate {
    return NO;
}

@end
```

**Comment by lianxiaoshuo** [comment]
> [OC_demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4466487/OC_demo.zip)
> 
> 我这个问题主要是按照你提供的方式配置了全屏的操作，但我想禁止自动横屏，只在点击全屏按钮时才能横屏但不行，你能帮我看下么，到底啥问题哦
> 
> ```
> @implementation UIViewController (RotationControl)
> - (BOOL)shouldAutorotate { 
>     return NO;
> }
> 
> - (UIInterfaceOrientationMask)supportedInterfaceOrientations {
>     return UIInterfaceOrientationMaskPortrait;
> }
> ```
> 
> 是这两个方法不调用？好奇怪
- (BOOL)shouldAutorotate { 
    return NO;
}在你的tablebar写上这句话就可以了

**Comment by changsanjiang** [comment]
这个调用是从 tabBar 到 nav 再到 vc, 一层一层传上来的. 当在某个 vc 实现了 shouldAutorotation 方法, 分类的方法就不会触发.

**Comment by lianxiaoshuo** [comment]
谢谢




| |
连硕
邮箱：13113451549@163.com
|

签名由 网易邮箱大师 定制

在2020年06月23日 10:35，changsanjiang 写道：

这个调用是从 tabBar 到 nav 再到 vc, 一层一层传上来的. 当在某个 vc 实现了 shouldAutorotation 方法, 分类的方法就不会触发.

**Comment by HanXiaoTeng** [comment]
这样设置以后 app其他的界面都可以横屏了 我只想在视频播放可以横屏，其他不能横屏，怎么解决

**Comment by chenshipeng** [comment]
点击旋转和自动旋转不是应该分开的吗？现在我按照这个配置了，点击全屏还是卡主了，页面其他的地方都不能点击了

**Comment by sauchye** [comment]
//修改按钮
    SJEdgeControlLayer *sjControlLayer            = self.player.defaultEdgeControlLayer;
    SJEdgeControlButtonItemAdapter *centerAdapter = sjControlLayer.centerAdapter;
    SJEdgeControlButtonItemAdapter *bottomAdapter = sjControlLayer.bottomAdapter;
    
    // 移除按钮
    [centerAdapter removeItemForTag:SJEdgeControlLayerCenterItem_Replay];/// 重播
    [centerAdapter reload];
    [bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_Full];/// 全屏
    
    // 添加按钮
    SJEdgeControlButtonItem *smallItem = [SJEdgeControlButtonItem.alloc initWithImage:[UIImage imageNamed:@"small_screen_icon"] target:self action:@selector(zoomAction) tag:1011];
    [bottomAdapter addItem:smallItem];
    [bottomAdapter reload];
    
    // 修改事件
    SJEdgeControlButtonItem *playItem = [bottomAdapter itemForTag:SJEdgeControlLayerBottomItem_Play];
    [playItem removeAllActions];
    [playItem addAction:[SJEdgeControlButtonItemAction actionWithHandler:^(SJEdgeControlButtonItemAction * _Nonnull action) {
        ////[weakSelf.navigationController popViewControllerAnimated:NO];
    }]];

**Comment by dczjs** [comment]
ipad无法旋转全屏
