### ISSUE TITLE
同一个player怎么替换一个新的url

### ISSUE THREAD

**Issue by hgeyork** [changsanjiang/SJVideoPlayer#150]

**Comment by changsanjiang** [comment]
直接设置资源.  player.URLAsset = ....

**Comment by hgeyork** [comment]
目前是这样的，我已经用一个网络地址播放了一段时间后切换了播放地址，重新创建了一个SJVideoPlayerURLAsset对象后调用了player.URLAsset = 方法后出现崩溃 崩溃位置为：
 objc_setAssociatedObject(target, _cmd, player, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
 其中target为一个空对象

**Comment by changsanjiang** [comment]
版本是2.6.5的吗? 

![image](https://user-images.githubusercontent.com/25744224/64751793-ebfefc80-d54f-11e9-848b-430c19b3d259.png)

**Comment by changsanjiang** [comment]
我们加一个QQ吧,  QQ看吧

**Comment by hgeyork** [comment]
2.4.4

**Comment by hgeyork** [comment]
v2.5.7 说错了抱歉

**Comment by hgeyork** [comment]
我想这是我这边使用场景的问题，目前我在同一个viewController可以播放其他视频源，并没有切换到其他的viewController，所以SJBaseVideoPlayer没有被替换，而是直接调用setUrlAsset重新赋予了一个新的asset给原来的player，目前我这边如果移除了旧的player，创建新的player之后就没有这个问题
