### ISSUE TITLE
Xcode11 iOS 13 返回崩溃

### ISSUE THREAD

**Issue by iOSzyz** [changsanjiang/SJVideoPlayer#153]
#import "NSObject+SJObserverHelper.h"
.m 158行
- (void)dealloc {
    @try {
        [_target removeObserver:self forKeyPath:_keyPath];
    } @catch (NSException *__unused exception) { }
}

**Comment by changsanjiang** [comment]
更新版本, 或者替换这个文件. 

[SJAVMediaMainPresenter.m.zip](https://github.com/changsanjiang/SJVideoPlayer/files/3644989/SJAVMediaMainPresenter.m.zip)

**Comment by goodMrs** [comment]
我昨天应该更新到最新版本了，更新到哪个版本才可以啊！

**Comment by changsanjiang** [comment]
SJBaseVideoPlayer 指定到 2.5.2 以上.
```ruby
pod 'SJBaseVideoPlayer', '>= 2.5.2'
```

**Comment by iOSzyz** [comment]
替换了文件确实好使了，👍

**Comment by houxianghua** [comment]
pod 'SJBaseVideoPlayer', '>= 2.5.2'  提示没有2.5.2版本  最新版本2.4.4是为什么

**Comment by houxianghua** [comment]
pod 'SJBaseVideoPlayer', '>= 2.5.2'  提示没有2.5.2版本  最新版本2.4.4是为什么

> SJBaseVideoPlayer 指定到 2.5.2 以上.
> 
> ```ruby
> pod 'SJBaseVideoPlayer', '>= 2.5.2'
> ```

我的提示没有2.5.2版本，最新只能更新到2.4.4 返回还是崩溃

**Comment by houxianghua** [comment]
你们怎么升级到2.5.2的

**Comment by houxianghua** [comment]
> 你们怎么升级到2.5.2的

知道了，要platform :ios, '9.0' 才可以

**Comment by Hank-Zhong** [comment]
要先 `repo update` 更新一下本地仓库
