### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by MrMaa** [changsanjiang/SJVideoPlayer#154]
Task <55FE0C4F-4AEA-42DE-AF90-845D9B0FA9C6>.<2> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://xy2.v.netease.com/r/video/20190814/7db8102c-1b18-4a59-ac70-ec03137f1c2e.mp4, NSErrorFailingURLKey=https://xy2.v.netease.com/r/video/20190814/7db8102c-1b18-4a59-ac70-ec03137f1c2e.mp4, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <55FE0C4F-4AEA-42DE-AF90-845D9B0FA9C6>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <55FE0C4F-4AEA-42DE-AF90-845D9B0FA9C6>.<2>, NSLocalizedDescription=cancelled} [-999]

**Comment by changsanjiang** [comment]
这个应该是网络请求被取消的报错, 应该不影响播放吧.
