### ISSUE TITLE
播放器使用SJIJKMediaPlaybackController 显示找不到SJMediaPlaybackProtocol

### ISSUE THREAD

**Issue by coderJLHome** [changsanjiang/SJVideoPlayer#155]
如题出现问题,更换不了.请问有没有相对应的demo和更换SJIJKMediaPlaybackController流程?

**Comment by changsanjiang** [comment]
已更新这个模块,  使用的话参照一下这个issue吧: https://github.com/changsanjiang/SJVideoPlayer/issues/164
