### ISSUE TITLE
iOS13.0+后台播放视频失效

### ISSUE THREAD

**Issue by szdkkk** [changsanjiang/SJVideoPlayer#156]
测试环境：iOS 13.0+，库版本3.0.0，播放视频文件并正在渲染视频画面，此时进入后台播放被暂停。

解绑SJAVMediaSubPresenter的时机需要提前到ApplicationWillResignActive，并且显式地从AVPlayerLayer移除AVPlayer。

**Comment by changsanjiang** [comment]
@szdkkk  非常感谢. 
我在新的版本中修复了它(SJBaseVideoPlayer v3.0.1).
