### ISSUE TITLE
iOS13.1 播放完成时闪退

### ISSUE THREAD

**Issue by Aaronwk** [changsanjiang/SJVideoPlayer#157]
- (void)dealloc {
    @try {
        [_target removeObserver:self forKeyPath:_keyPath]; // 闪退定位到了这一行
    } @catch (NSException *__unused exception) { }
}

**Comment by theflybirds** [comment]
ios13 禁止使用KVO了

**Comment by changsanjiang** [comment]
@Aaronwk @theflybirds 试试这个 https://github.com/changsanjiang/SJVideoPlayer/issues/153

**Comment by Aaronwk** [comment]
> @Aaronwk @theflybirds试试这个[＃153](https://github.com/changsanjiang/SJVideoPlayer/issues/153)

感谢
