### ISSUE TITLE
列表自动播放第三个视频

### ISSUE THREAD

**Issue by NicholasBxt** [changsanjiang/SJVideoPlayer#158]
列表自动播放第三个视频，中间一个自动跳过

**Comment by NicholasBxt** [comment]
江哥求解

**Comment by NicholasBxt** [comment]
@changsanjiang

**Comment by changsanjiang** [comment]
这个之前是个Bug,  https://github.com/changsanjiang/SJVideoPlayer/issues/136  我在后面的版本修复了
