### ISSUE TITLE
想要保持控制界面不隐藏 player 调用 controlLayerAppearManager.keepAppearState()无效

### ISSUE THREAD

**Issue by xujinhui** [changsanjiang/SJVideoPlayer#159]
想要保持控制界面不隐藏， player调用 controlLayerAppearManager.keepAppearState()无效, 
- (void)keepAppearState {
    [self needAppear];
    [self _clear];
}
看代码调用 [self _clear];时会清除定时器，但是在播放时还是会自动隐藏

**Comment by changsanjiang** [comment]
keep之后, 禁用一下吧. 
[_player.controlLayerAppearManager keepAppearState];
_player.controlLayerAppearManager.disabled = YES;

**Comment by xujinhui** [comment]
已验证，多谢了 @changsanjiang
