### ISSUE TITLE
退到后台，播放视频暂停了。

### ISSUE THREAD

**Issue by Aaronwk** [changsanjiang/SJVideoPlayer#162]
设置了_player.pauseWhenAppDidEnterBackground = NO;依然暂停。iOS13.1
偶尔还伴随这个错误：Can't end BackgroundTask: no background task exists with identifier 3 (0x3), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by changsanjiang** [comment]
之前已经修复了, 更新一下吧.  https://github.com/changsanjiang/SJVideoPlayer/releases/tag/v3.0.2

**Comment by Aaronwk** [comment]
> 之前已经修复了，更新一下吧。 https://github.com/changsanjiang/SJVideoPlayer/releases/tag/v3.0.2

pod update SJVideoPlayer --verbose --no-repo-update  为啥还是  - SJVideoPlayer, 2.5.7
