### ISSUE TITLE
续播的全屏问题

### ISSUE THREAD

**Issue by dota2AndTI** [changsanjiang/SJVideoPlayer#166]
我遇到了一个问题：视屏的跳入下一界面继续播放，但是在下级界面点击全屏上一界面也会旋转，导致全屏按返回时最上面的控制器还是全屏的控制器。无法与用户交互

**Comment by changsanjiang** [comment]
这几个方法掉一下

![Uploading image.png…]()

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/66812715-03257580-ef66-11e9-8174-3c116bd1dc04.png)

**Comment by dota2AndTI** [comment]
我发现，把自动旋转关了就行了
