### ISSUE TITLE
江哥,支持rtmp么

### ISSUE THREAD

**Issue by spiritbuild** [changsanjiang/SJVideoPlayer#168]
江哥,支持rtmp么

**Comment by changsanjiang** [comment]
马上就支持了, 今晚发版本

**Comment by spiritbuild** [comment]
爱你~😘

**Comment by changsanjiang** [comment]
试试按这个操作切换成 ijkplayer 来播放 rtmp.  https://github.com/changsanjiang/SJVideoPlayer#avplayer-%E5%88%87%E6%8D%A2%E4%B8%BA-ijkplayer-%E5%85%B6%E4%BB%96%E5%8A%9F%E8%83%BD%E4%B8%8D%E5%8F%98
