### ISSUE TITLE
偶尔出现 视频加载失败，请确认网络后重试，然后一直这样

### ISSUE THREAD

**Issue by LiYuLong012** [changsanjiang/SJVideoPlayer#173]
-[SJAVMediaPlayer observeValueForKeyPath:ofObject:change:context:] - Error Domain=NSURLErrorDomain Code=-1200 "发生了SSL错误，无法建立与该服务器的安全连接。" UserInfo={NSUnderlyingError=0x283b159e0 {Error Domain=NSOSStatusErrorDomain Code=-1200 "(null)"}, NSLocalizedDescription=发生了SSL错误，无法建立与该服务器的安全连接。, NSLocalizedRecoverySuggestion=您仍要连接此服务器吗？}

**Comment by NicholasBxt** [comment]
那是你播放流有问题

**Comment by Project112224** [comment]
我的狀況是網址本身沒問題     虛擬機重開後就好了
