### ISSUE TITLE
最新版本的SDK，竖屏视频点击全屏失效，无法全屏，且导致后续横屏视频也无法全屏

### ISSUE THREAD

**Issue by LokiRename** [changsanjiang/SJVideoPlayer#178]
最新版本的SDK，竖屏视频点击全屏失效，无法全屏，且导致后续横屏视频也无法全屏

**Comment by changsanjiang** [comment]
@LokiRename 参考这个: https://github.com/changsanjiang/SJVideoPlayer/issues/148

**Comment by e21169191** [comment]
我也遇到了，不是设置配置的问题。是竖屏排的，它播放出来是全屏的，所以再点击右下角的全屏按钮时，就没有效果了，它不横屏了。应该是SJFitOnScreenManager造成的
