### ISSUE TITLE
跳转新的控制器无法暂停播放

### ISSUE THREAD

**Issue by YangYus** [changsanjiang/SJVideoPlayer#180]
你可以在colloctionView的那个demo加个按钮跳个新的控制器就会出现问题

**Comment by YangYus** [comment]
无法暂停播放 即使调了api

**Comment by changsanjiang** [comment]
好的, 我试试

**Comment by YangYus** [comment]
又重复走了你的懒加载 又调了次播放

**Comment by changsanjiang** [comment]
好的, [先改一下这个地方吧](https://github.com/changsanjiang/SJVideoPlayer/blob/d97d1497e535f2f51d40d73237ed25a97a3a936d/Example/Pods/SJBaseVideoPlayer/SJBaseVideoPlayer/UIScrollView%2BListViewAutoplaySJAdd.m#L67)


```Objective-C
        queue.empty();
        ///
        /// Thanks @YangYus
        ///
        /// Fix [#180](https://github.com/changsanjiang/SJVideoPlayer/issues/180)
        ///
        if ( self.window == nil ) {
            return;
        }

        queue.enqueue(^{
            self.sj_hasDelayedEndScrollTask = YES;
            [self performSelector:@selector(sj_playNextAssetAfterEndScroll) withObject:nil afterDelay:0.4];
        });
```

**Comment by YangYus** [comment]
Thank you

**Comment by YangYus** [comment]
- (void)presentViewReadyForDisplayDidChange:(NSNotification *)note
- (BOOL)isReadyForDisplay {
    return self.layer.isReadyForDisplay;
}

 if ( _placeholderImageView.isHidden == YES )
这几个方法错误
-[UIView isHidden] must be used from main thread only

**Comment by changsanjiang** [comment]
已修复
