### ISSUE TITLE
拖动进度条快进会卡住

### ISSUE THREAD

**Issue by moxcomic** [changsanjiang/SJVideoPlayer#181]
拖动进度条或者双击边缘快进会卡住，再次重复操作的话可能会继续播放也可能会卡住，文件格式是m3u8 ，但是放到Demo里播放又没有这种问题，请问这个是什么原因造成的

**Comment by changsanjiang** [comment]
BasePlayer 更新到最新版本试试看看

**Comment by moxcomic** [comment]
> BasePlayer 更新到最新版本试试看看

更新了快进还是会卡住，但是时间还在走的，内容是已经缓冲好了就是画面卡住时间还在动

**Comment by changsanjiang** [comment]
加群(930508201)或者QQ(1779609779)发我个链接吧, 我测试一下
