### ISSUE TITLE
你好,有个断点问题

### ISSUE THREAD

**Issue by xyl-private** [changsanjiang/SJVideoPlayer#184]
在播放视频再关闭后,添加的All exceptions 断点会不停的被断点截住,调试的时候经常出现,麻烦看一下

**Comment by changsanjiang** [comment]
@xyl-private 右键改一下拦截类型, 试试看

![image](https://user-images.githubusercontent.com/25744224/68122860-57f55400-ff46-11e9-8942-f9d0839268d8.png)

**Comment by xyl-private** [comment]
尝试了一下 好使了 谢谢了
