### ISSUE TITLE
使用IJKPlayer第一次调用会卡很久

### ISSUE THREAD

**Issue by liurenqiu520** [changsanjiang/SJVideoPlayer#185]
如题

**Comment by changsanjiang** [comment]
系统检测到ijk内部在子线程调用了UI相关的方法, 可以尝试把检测关闭. 

![Uploading image.png…]()

**Comment by changsanjiang** [comment]
<img width="906" alt="Screen Shot 2019-11-05 at 1 49 57 PM" src="https://user-images.githubusercontent.com/25744224/68181750-69d10880-ffd3-11e9-804e-177f46880b23.png">

**Comment by liurenqiu520** [comment]
赞
