### ISSUE TITLE
大神，请问在当组件隐藏时不变成浮窗

### ISSUE THREAD

**Issue by hponiang** [changsanjiang/SJVideoPlayer#186]
普通视图中播放,播放器创建代码如下：
`
 _player = [SJVideoPlayer player];
        _player.defaultEdgeControlLayer.hiddenBackButtonWhenOrientationIsPortrait = YES;
        _player.showMoreItemToTopControlLayer = YES;
        _player.floatSmallViewController.enabled = YES;
        _player.pauseWhenScrollDisappeared = NO;
      
        [self addSubview:_player.view];
`

貌似没有触发
` (void)observeValueForKeyPath:(nullable NSString *)keyPath
                      ofObject:(nullable id)object
                        change:(nullable NSDictionary<NSKeyValueChangeKey,id> *)change
                       context:(nullable void *)context {
    if ( &kContentOffset == context ) {
        __weak typeof(self) _self = self;
        _taskQueue.empty().enqueue(^{
            [_self _scrollViewDidScroll:object];
        });
    }
    else if ( &kState == context ) {
        [self _panGestureStateDidChange:object];
    }
}`这部分代码

**Comment by changsanjiang** [comment]
是针对scrollView中使用的,  普通视图没有做监听

**Comment by hponiang** [comment]
先感谢这么快速回复！
有什么建议不，我是用的第三方工具包加载咱们这个组件 里，里面不提供了一个普通视图

**Comment by changsanjiang** [comment]
…… 没理解…… 可以详细描述一下吗

**Comment by hponiang** [comment]
就是
```
[self addSubview:_player.view];
```
self 继承自uiview

**Comment by changsanjiang** [comment]
加群(930508201)或者QQ(1779609779)吧, 有啥问题到群里来说吧
