### ISSUE TITLE
全屏界面飞出屏幕

### ISSUE THREAD

**Issue by MarkLeef** [changsanjiang/SJVideoPlayer#187]
`self.player.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithURL:[NSURL URLWithString:@"https://xy2.v.netease.com/r/video/20190814/7db8102c-1b18-4a59-ac70-ec03137f1c2e.mp4"]];
    [self.playerContainerView addSubview:self.player.view];
    [_player.view mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.offset(0);
    }];`
大神 我这样子写 然后放在modal 的控制器里面  全屏 视屏界面 飞出屏幕

**Comment by changsanjiang** [comment]
加群(930508201)或者QQ(1779609779)吧, 录个小视频瞅瞅

**Comment by MarkLeef** [comment]
已加QQ通过一下

**Comment by MarkLeef** [comment]
感谢
