### ISSUE TITLE
cocoapods导入报错

### ISSUE THREAD

**Issue by daomoer** [changsanjiang/SJVideoPlayer#2]
SJOrentationObserver.h
- (instancetype)initWithTarget:(__weak UIView *)view container:(__weak UIView *)targetSuperview;
报错   Cannot create __weak reference because the current deployment target does not support weak references

**Comment by changsanjiang** [comment]
你好, 已修复. 抱歉了, 我在xcode9上跑的好好的, 试了x8, 果然报错, 找了下原因, 是因为 pod 没选择ios版本导致的.

**Comment by daomoer** [comment]
👌感谢开源
