### ISSUE TITLE
第一次转屏的有时候全屏的UI不太正确，之后就可以正确了

### ISSUE THREAD

**Issue by Yangshaoyi** [changsanjiang/SJVideoPlayer#204]
第一次转屏的有时候全屏的UI不太正确，之前就可以正确了

**Comment by changsanjiang** [comment]
截几张图瞅瞅

**Comment by oujinlong** [comment]
我也是一样的情况

**Comment by changsanjiang** [comment]
请根据指南配置一下旋转: https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation
