### ISSUE TITLE
全屏播放(控制层隐藏时)后台再切回前台，导致导航栏上移

### ISSUE THREAD

**Issue by Gaozn** [changsanjiang/SJVideoPlayer#205]
**描述bug**
不晓得这个算不算个bug，我之前使用其他sdk时也有遇到，解决办法就是模态弹出一个空的vc，再dismiss。animation：NO.
全屏播放(控制层隐藏时)后台再切回前台，导致导航栏上移，假如当前页面导航栏是隐藏，则会导致播放器上移

**必现/偶发?**
必现

**怎么样重现这个bug**
播放器页面：点击全屏播放(控制层隐藏)-点击Home键后台-再切回前台(显示控制层)-返回
出现的问题：**此时导航栏会向上移动状态栏的高度**，（假如隐藏状态栏，播放器的view也会向上移动状态栏的高度）

**你期望的结果是什么？**
如何解决
**截图**
无法传图
**Demo**
v3.0.6 版Demo
**运行环境**
 - iPhone非刘海系列
 - iOS13以下
 - Xcode 11.1

**Comment by changsanjiang** [comment]
这个问题我之前发现了, 暂时定位不到原因.  目前可以在这个页面 隐藏系统导航栏, 自定义一个.

**Comment by Gaozn** [comment]
> 这个问题我之前发现了, 暂时定位不到原因. 目前可以在这个页面 隐藏系统导航栏, 自定义一个.

好像原因不是在导航栏，而是在状态栏。因为当我去掉导航栏时，整个view都向上移动了20

**Comment by changsanjiang** [comment]
已在新版修复(v3.0.8)
