### ISSUE TITLE
pod ijk版本后打开文件找不到

### ISSUE THREAD

**Issue by kaizhou123** [changsanjiang/SJVideoPlayer#206]
我根据你文档的pod 之后 打开就这样 咋解决哇

![屏幕快照 2019-11-21 下午3 31 15](https://user-images.githubusercontent.com/26211800/69316594-21247b00-0c74-11ea-9cb9-8deb5891498a.png)

![屏幕快照 2019-11-21 下午3 32 52](https://user-images.githubusercontent.com/26211800/69316632-37cad200-0c74-11ea-8f04-58ff24f67c50.png)

**Comment by kaizhou123** [comment]
手机版本 和  bit 都做了操作

**Comment by changsanjiang** [comment]
https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer

**Comment by shiqiaoyun** [comment]
我遇到了一样的问题，pod之后，文件找不到，请问你解决了嘛？

**Comment by kaizhou123** [comment]
需要把pod 文件里的&nbsp; use_frameworks! 给注释掉




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shiqiaoyun"<notifications@github.com&gt;; 
发送时间: 2020年3月18日(星期三) 下午3:13
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "周凯"<775393943@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] pod ijk版本后打开文件找不到 (#206)





 
我遇到了一样的问题，pod之后，文件找不到，请问你解决了嘛？

**Comment by changsanjiang** [comment]
cocoapods使用`gem install cocoapods`升到最新版, podfile里面改成这个再试试: `use_frameworks! :linkage => :static`

**Comment by slash130** [comment]
@changsanjiang 大佬 我在pod里设置use_frameworks! :linkage => :static之后storyboard里用到的第三方库会报错

IB Designables: Failed to render and update auto layout status for xxx_xxl_dantu_cell (KGk-i7-Jjw): dlopen(YYKit.framework, 1): no suitable image found.  Did find:
	YYKit.framework: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A

这个有什么解决的办法吗？
