### ISSUE TITLE
你好问下类似于rtsp这种播放直播这种可以用你这个界面吗

### ISSUE THREAD

**Issue by zhoulincome** [changsanjiang/SJVideoPlayer#207]
问下直播类的地址能播放吗

**Comment by changsanjiang** [comment]
参考这个使用ijk来播放: https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer

**Comment by changsanjiang** [comment]
控制层操作, 参考: https://github.com/changsanjiang/SJVideoPlayer/wiki/Setup-Control-Layer-View

**Comment by sjxt** [comment]
> 参考这个使用ijk来播放: https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer


ld: '/Users/chenzhen/Desktop/ijkplaerDemo/Pods/ijkplayerssl/IJKMediaFrameworkWithSSL.framework/IJKMediaFrameworkWithSSL' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/chenzhen/Desktop/ijkplaerDemo/Pods/ijkplayerssl/IJKMediaFrameworkWithSSL.framework/IJKMediaFrameworkWithSSL' for architecture arm64


bitcode 设置为NO了  按照参考链接还是报这个错  能帮忙看看吗

**Comment by sjxt** [comment]
> 参考这个使用ijk来播放: https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer

这个是我新建的一个demo来做测试的  在原来项目上一样的报这个错误
