### ISSUE TITLE
锁屏情况下默认pauseWhenAppDidEnterBackground=YES还会播放 ? 

### ISSUE THREAD

**Issue by gratefulHeart** [changsanjiang/SJVideoPlayer#208]
是不是在```SJBaseVideoPlayer```  退到后台做一下处理 

_registrar.didEnterBackground = ^(SJVideoPlayerRegistrar * _Nonnull registrar) {
        __strong typeof(_self) self = _self;
        if ( !self ) return ;
        BOOL canPause = self.timeControlStatus == SJPlaybackTimeControlStatusPlaying && self.pauseWhenAppDidEnterBackground;
        if (canPause) {
            [self pause];
        }
        if ( [self.controlLayerDelegate respondsToSelector:@selector(receivedApplicationDidEnterBackgroundNotification:)] ) {
            [self.controlLayerDelegate receivedApplicationDidEnterBackgroundNotification:self];
        }
        [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(_setRotationAbleValue:) object:nil];
        [self _setRotationAbleValue:@(NO)];
    };
    return _registrar;
}

**Comment by changsanjiang** [comment]
好的, 感谢反馈

**Comment by changsanjiang** [comment]
已在新版添加(v3.0.8)
