### ISSUE TITLE
随便提

### ISSUE THREAD

**Issue by wyxuan** [changsanjiang/SJVideoPlayer#209]
1、是否可以添加个缓存功能，如果开启的话播放完后可以缓存到本地。
2、补充下载功能？
3、那个base的库跟着有啥联系？看说明都一样呢

**Comment by changsanjiang** [comment]
缓存功能还在酝酿,  应该不久之后会写吧

BasePlayer 没有控制层, SJVideoPlayer 封装了这些 UI
