### ISSUE TITLE
使用了私有API

### ISSUE THREAD

**Issue by sheodon** [changsanjiang/SJVideoPlayer#212]
ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/SJBaseVideoPlayer.framework/SJBaseVideoPlayer: _setContentOverlayInsets:andLeftMargin:rightMargin:, _updateBarsForCurrentInterfaceOrientation. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by changsanjiang** [comment]
BasePlayer更新到最新版
