### ISSUE TITLE
旋转后SJRotationvc 不移除

### ISSUE THREAD

**Issue by cui30366423** [changsanjiang/SJVideoPlayer#213]
app支持横竖屏，在使用播放器时，由竖屏切换至横屏，有些资源是不会全屏的，这是点击全屏按钮有时无法全屏，如果进入全屏后再恢复，这时播放器内右上角的自定义按钮点击失灵，无法响应。关闭播放器后，有一个SJRotation的viewcontroller 覆盖在屏幕最上方，是看不出来的，经过查看页面发现，这时app全部手势都会无效，因为被遮挡。

**Comment by yangyunzeyz** [comment]
我也遇到了这个问题,发现是window被替换导致的.你可以在SJRotationManager的 - (void)fullscreenModeViewController:(SJFullscreenModeViewController *)vc didRotateFromOrientation:(UIDeviceOrientation)orientation方法 window赋值那里打断点看看.

**Comment by yangyunzeyz** [comment]
我自己处理了下,orientation为UIDeviceOrientationPortrait时手动设置为系统window.
` UIWindow *previousKeyWindow = UIApplication.sharedApplication.windows.firstObject;
            if (self.previousKeyWindow && orientation != UIDeviceOrientationPortrait) {
                previousKeyWindow = self.previousKeyWindow;
            }`

**Comment by changsanjiang** [comment]
[旋转配置](https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation)是否添加?

**Comment by cui30366423** [comment]
发现了是添加了window 占用在最上层。这个情况很容易出现。 还有横屏有时锁屏和截图的按钮有时不出现&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangyunzeyz <notifications@github.com&gt;
发送时间: 2019年12月9日 13:07
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)

**Comment by cui30366423** [comment]
默认的配置 &nbsp; 本来自定义管理类。发现无法解决&nbsp;
还有旋转里面isfullscreen 根据设备方向判断不合理，应该以是否满屏为准



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月9日 13:11
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




旋转配置是否添加?

**Comment by cui30366423** [comment]
屏幕方向还有faceup与facedown 苹果官方也有。目前那几个还不够严谨

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月9日 13:11
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




旋转配置是否添加?

**Comment by yangyunzeyz** [comment]
> [旋转配置](https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation)是否添加?

你好,我已经配置了. 我的情况是在全屏的情况下点击返回到正常竖屏时.无法响应任何事件,从图层看是因为被SJFullscreenModeViewController挡住了

**Comment by cui30366423** [comment]
确实是被他遮挡。 感觉问题还是有的。选了好多播放器 目前这个还算好。但是问题也有。 还有快进也会出现遮挡的情况 这样右侧自定义按钮也会无法点击



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangyunzeyz <notifications@github.com&gt;
发送时间: 2019年12月9日 13:38
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)



 
旋转配置是否添加?
  
你好,我已经配置了. 我的情况是在全屏的情况下点击返回到正常竖屏时.无法响应任何事件,从图层看是因为被SJFullscreenModeViewController挡住了

**Comment by changsanjiang** [comment]
demo中有通用的问题吗?    手机系统是几?

**Comment by cui30366423** [comment]
demo 体验过。demo 是设置只竖直方向的。自己工程是支持其他方向的， 支持左右旋转

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月9日 13:46
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




demo中有通用的问题吗?    手机系统是几?

**Comment by cui30366423** [comment]
系统12和13都有试过&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月9日 13:46
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




demo中有通用的问题吗?    手机系统是几?

**Comment by changsanjiang** [comment]
配置中的第一步和第二步是使App强制竖屏启动.  工程支持哪些方向, 可以在第二步中进行设置.

第三步是将旋转交由最上层的控制器来控制, shouldAutorotation 返回NO, 则不会触发旋转, 如果你的某些界面需要触发旋转, 可以重写 shouldAutorotation 返回 YES, 并设置旋转支持的方向. 

旋转相关的可以看看这个文章: https://www.jianshu.com/p/97acbcf659b8,

**Comment by cui30366423** [comment]
工程需要。需要支持这些方向。看过说明。强制竖屏。并不合理





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月9日 13:56
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




配置中的第一步和第二步是使App强制竖屏启动.  工程支持哪些方向, 可以在第二步中进行设置.
 
第三步是将旋转交由最上层的控制器来控制, shouldAutorotation 返回NO, 则不会触发旋转, 如果你的某些界面需要触发旋转, 可以重写 shouldAutorotation 返回 YES, 并设置旋转支持的方向.
 
旋转相关的可以看看这个文章: https://www.jianshu.com/p/97acbcf659b8,

**Comment by changsanjiang** [comment]
第一步和第二步可以省略,   但第三步是必须添加的.

**Comment by cui30366423** [comment]
3.1.1 依然遮挡  ，配置旋转没有用，主要是逻辑有问题，设备一旦旋转出现全屏后，经常错乱。强制从竖屏启动播放器，最后关闭后也恢复到竖屏也没有用。   更别说从竖屏启动播放器，支持其他旋转。

**Comment by cui30366423** [comment]
代码里面  很多isfullscreen 是根据设备方向判断的，isfiton 跟这个 看着都逻辑都乱

**Comment by changsanjiang** [comment]
Demo有同样问题？  你可以到群里反馈，录个视频，发下相关代码

**Comment by cui30366423** [comment]
demo 考虑过播放器要移除嘛。 可以横屏开启播放器吗&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月21日 12:10
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




Demo有同样问题？  你可以到群里反馈，录个视频，发下相关代码

**Comment by cui30366423** [comment]
功能做的是不错。 但是代码冗余的可怕



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月21日 12:10
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




Demo有同样问题？  你可以到群里反馈，录个视频，发下相关代码

**Comment by changsanjiang** [comment]
我也想删没用的代码，更新兼容这么多版本，我敢吗？

**Comment by cui30366423** [comment]
项目想这几天提交。就剩下播放器了。本来这个功能挺全的。但是 看到代码和最后处理的方式真是寒心了一大截。 使用那么多重名的属性。 &nbsp;是谁看着也犯晕。 使用window 作为播放器主页面。就一定要处理好window的移除，不然会是应用无法正常使用。 还有出现window这个控制层的情况。 连快进都可以用不了，确实你需要重构了，再加功能会让以后维护更加困难



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月21日 12:14
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)

**Comment by changsanjiang** [comment]
哥们，加群，难吗？录个视频看一下啊，说来说去我还是不知道你这问题是啥

**Comment by cui30366423** [comment]
已经替换为zfplayer 完美解决问题。虽然他功能不多，至少没有异常问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: changsanjiang <notifications@github.com&gt;
发送时间: 2019年12月21日 12:28
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com&gt;
抄送: 崔亚鹏 <suoxwd@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[changsanjiang/SJVideoPlayer] 旋转后SJRotationvc 不移除 (#213)




哥们，加群，难吗？录个视频看一下啊，说来说去我还是不知道你这问题是啥
