### ISSUE TITLE
能否在播放正式视频前播放一段几十秒广告（点击可以跳过，跳转H5等），怎么操作合适。

### ISSUE THREAD

**Issue by ZZKll** [changsanjiang/SJVideoPlayer#214]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，在开发中，经常遇到XXX问题，目前框架的功能不足以解决这个问题

**你希望达到的效果**
比如，我希望框架能够帮助我解决XXX问题，实现XXXX那样的效果

**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？

**Comment by changsanjiang** [comment]
需要自定义一个广告控制层

**Comment by ZZKll** [comment]
谢谢

**Comment by MidnightSmokingSoul** [comment]
> 需要自定义一个广告控制层

广告层添加到那个控件上面, 我需要加一个试看结束的购买层, 不知道如何添加
