### ISSUE TITLE
VideoPlayer Full Screen Issue in UITableViewCell

### ISSUE THREAD

**Issue by xiaolin-mm** [changsanjiang/SJVideoPlayer#219]
Hi! I use SJVideoPlayer on my project. My project have video gallery page and use tableview and SJVideoPlayer. It works fine, but when I click full screen button, there's no change on UI and no touchable to any UI, and I should force to close the app. SJvideoplayer is in the UITableViewCell. I hope to listen goods from you. Thank you.

**Comment by changsanjiang** [comment]
Hi @xiaolin-mm , v2.6.5 version and later need to configure rotation in your project, please add the attached file to the project and re-run the project.

[Archive.zip](https://github.com/changsanjiang/SJVideoPlayer/files/3992453/Archive.zip)

**Comment by xiaolin-mm** [comment]
Thanks, I add the attachment but it also has problem as well. I use Portrait only for my app, but it doesn't work. When I check Landscape Left/Right then it works fine. Please let me know how to solve it.

**Comment by changsanjiang** [comment]
ok,  Please try to configure the 1 and 2 steps. https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation

**Comment by xiaolin-mm** [comment]
Thank you, it works fine.
