### ISSUE TITLE
pods绑定的库好多啊

### ISSUE THREAD

**Issue by theHeroisBack** [changsanjiang/SJVideoPlayer#22]
![2018-04-17 2 35 16](https://user-images.githubusercontent.com/30762999/38852479-a361b09a-424c-11e8-8adb-0d9c51c9d7ec.png)
我只想用播放器这个库，其他的库也是这样必须用到的吗？？

**Comment by changsanjiang** [comment]
😁, 每个库在播放器里面都用到啦. 
为了解耦, 我把一些功能拆成了独立组件了....

**Comment by theHeroisBack** [comment]
好的
