### ISSUE TITLE
Definition of 'SJBaseVideoPlayer' must be imported from module 'SJBaseVideoPlayer.SJBaseVideoPlayer' before it is required

### ISSUE THREAD

**Issue by honeybeeSwinging** [changsanjiang/SJVideoPlayer#222]
**描述bug**
清晰简单地描述这个bug是啥

Definition of 'SJBaseVideoPlayer' must be imported from module 'SJBaseVideoPlayer.SJBaseVideoPlayer' before it is required

**必现/偶发?**
必现

**怎么样重现这个bug**
使用cocoapods集成就报错了

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone7plus
 - iOS12.4
 - Xcode10.2.1

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
Podfile 看一下.   是 swift 项目吗?

**Comment by honeybeeSwinging** [comment]
不是swift的，是oc
![image](https://user-images.githubusercontent.com/17585500/71457478-1744e900-27d9-11ea-8e84-f0274195f55b.png)

**Comment by changsanjiang** [comment]
shift + cmd + k , 清理一下, 重新运行项目试试

**Comment by honeybeeSwinging** [comment]
依然是会报错，对了想请问一下，如果直接本地拖入该如何拖入或者拖入哪些文档

**Comment by changsanjiang** [comment]
那就奇怪了,  那你搞个demo, 发我一份吧,  如果直接拖入 pod下来的那些文件  直接拖到主项目里面, 把报错的头文件改成双引号引用

**Comment by honeybeeSwinging** [comment]
直接把pod下来的文件全部拖进去是 吗？

**Comment by changsanjiang** [comment]
[SJVideoPlayer.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4001691/SJVideoPlayer.zip)

**Comment by honeybeeSwinging** [comment]
谢谢，谢谢！我刚才直接用
  pod 'SJVideoPlayer'
  pod 'SJBaseVideoPlayer'
下载下来的库，然后拖进了项目接着报错的地方，按你刚才说的“把报错的头文件改成双引号引用”后，现在可以正常运行项目了，接下来就准备开启其他功能了。

**Comment by honeybeeSwinging** [comment]
同时再请教一个问题，就是我想替换点击全屏按钮时候的事件怎么替换呢？谢谢

**Comment by changsanjiang** [comment]
这里主要反馈bug之类的,  使用问题来群里问吧:  930508201

```Objective-C
    SJEdgeControlButtonItem *item = [_player.defaultEdgeControlLayer.bottomAdapter itemForTag:SJEdgeControlLayerBottomItem_FullBtn];
    [item addTarget:self action:@selector(test)];
```

**Comment by honeybeeSwinging** [comment]
好的，谢谢！那再反馈一个刚才使用最新的版本的问题，就是第一次使用的时候全屏会出现不能全屏的情况，如下图：
![image](https://user-images.githubusercontent.com/17585500/71470082-09f22380-2806-11ea-8a3d-a3e186854ece.png)

**Comment by changsanjiang** [comment]
添加旋转配置.  [Categories.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4002160/Categories.zip)
