### ISSUE TITLE
tableView列表页面点击全屏播放，然后再返回，视图列表下半部分无法点击也无法滑动了

### ISSUE THREAD

**Issue by TTanys** [changsanjiang/SJVideoPlayer#224]
**必现/偶发?**
必现

**描述bug**
tableView列表页面点击全屏播放，然后再返回，视图列表下半部分无法点击也无法滑动了

**你期望的结果是什么?**
不知道怎么修复这个问题，大佬能看一下吗？

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
demo是否遇到了同样的问题?

**Comment by violetXiao** [comment]
确实有同样的问题push了两个播放界面后 在第二个播放界面手机旋转后 当前window被替换了 导致window挡住了界面 demo上也有这个问题  还有一个问题是push到第二个界面后有些手机出现全屏bug 只有左上角的一个小窗口播放 退出全屏再次横屏全屏播放才正常 demo上也有出现  3.1.1版本和以下版本都出现了

**Comment by changsanjiang** [comment]
这3个方法调了吗

```Objective-C
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self.player vc_viewDidAppear];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.player vc_viewWillDisappear];
}

- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    [self.player vc_viewDidDisappear];
} 
```

**Comment by changsanjiang** [comment]
也可以这样, 告诉播放器控制器 disappear了

```Objective-C
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    self.player.vc_isDisappeared = NO;
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    self.player.vc_isDisappeared = YES;
}

- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    [self.player pause];
}
```

**Comment by violetXiao** [comment]
> 也可以这样, 告诉播放器控制器 disappear了
> 
> ``


> 也可以这样, 告诉播放器控制器 disappear了
> 
> ```objc
> - (void)viewDidAppear:(BOOL)animated {
>     [super viewDidAppear:animated];
>     self.player.vc_isDisappeared = NO;
> }
> 
> - (void)viewWillDisappear:(BOOL)animated {
>     [super viewWillDisappear:animated];
>     self.player.vc_isDisappeared = YES;
> }
> 
> - (void)viewDidDisappear:(BOOL)animated {
>     [super viewDidDisappear:animated];
>     [self.player pause];
> }
> ```
确实是没调这三个方法 目前没发现这两个问题 感谢！！！
