### ISSUE TITLE
在tableViewcell上播放的时候（demo里边的开启小浮窗那个页面，保证小浮窗未出现），点击一个按钮使其触发跳转到一个新的视频播放页例如（SJVideoController11）。在新的视频播放页屏幕旋转出问题。

### ISSUE THREAD

**Issue by hoyhank** [changsanjiang/SJVideoPlayer#228]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
...

参考这个: https://github.com/changsanjiang/SJVideoPlayer/issues/224#issuecomment-570141467
