### ISSUE TITLE
视频播放页跳转新的视频播放页，旋转出现bug

### ISSUE THREAD

**Issue by hoyhank** [changsanjiang/SJVideoPlayer#229]
**必现/偶发?**
必现

**描述bug**
在tableViewcell上播放的时候（demo里边的开启小浮窗那个页面，保证小浮窗未出现），点击一个按钮使其触发跳转到一个新的视频播放页例如（SJVideoController11）。在新的视频播放页屏幕旋转出问题。

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
```Objective-C
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self.player vc_viewDidAppear];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.player vc_viewWillDisappear];
}

- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    [self.player vc_viewDidDisappear];
} 
```

**Comment by changsanjiang** [comment]
这三个方法调一下看看,  告诉播放器控制器 disappear了

**Comment by hoyhank** [comment]
已解决，谢谢。------------------ 原始邮件 ------------------
发件人: "changsanjiang"<notifications@github.com>
发送时间: 2020年1月6日(星期一) 晚上7:50
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com>;
抄送: "hoyhank"<1027311512@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [changsanjiang/SJVideoPlayer] 视频播放页跳转新的视频播放页，旋转出现bug (#229)



这三个方法调一下看看,  告诉播放器控制器 disappear了
 
&mdash;
