### ISSUE TITLE
竖屏转横屏之后自定义的控制层约束没有发生变化

### ISSUE THREAD

**Issue by theHeroisBack** [changsanjiang/SJVideoPlayer#23]
如图
![img_0144](https://user-images.githubusercontent.com/30762999/39035791-e1e00ef8-44ad-11e8-9e5a-965c2ce8db5b.PNG)
![img_0145](https://user-images.githubusercontent.com/30762999/39035796-eabfc810-44ad-11e8-8080-86a8232ee983.PNG)

我试着在旋转回调中重新layout
![2018-04-20 3 16 17](https://user-images.githubusercontent.com/30762999/39035830-093a6264-44ae-11e8-8063-11b2754d6880.png)
还是无效

**Comment by theHeroisBack** [comment]
@changsanjiang 嗯嗯，刚才更新了一下pods就好啦

**Comment by changsanjiang** [comment]
👌

**Comment by theHeroisBack** [comment]
又有新的问题好像😂，我没有开始播放视频的时候就全屏，placeholder没有跟着全屏，我刚才没有pods更新你这个库的时候这里还是正常的
![img_0146](https://user-images.githubusercontent.com/30762999/39037009-d51b1f88-44b1-11e8-9ba8-c9bcb2ce5016.PNG)

**Comment by changsanjiang** [comment]
👌, 我检查一下

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/39037811-34280214-44b4-11e8-9aae-a0058b705e8f.png)
你好, 先改下源代码, 加上 dispatch_async , 稍后, 我更新 pod 😁

**Comment by theHeroisBack** [comment]
好的

**Comment by theHeroisBack** [comment]
好像还是不行啊，没有开始播放时全屏，图片还是没有全屏啊

**Comment by changsanjiang** [comment]
是直接设置的旋转方向对吧?, 把那个方法里面也加上 dispatch_async ... 
![image](https://user-images.githubusercontent.com/25744224/39283117-3d761a9c-493f-11e8-81f0-1a048c248047.png)

**Comment by theHeroisBack** [comment]
我用pods倒的库，我不能改里面的代码啊

**Comment by changsanjiang** [comment]
pod update 一下吧, 上次我都加上 dispatch_async 了

**Comment by theHeroisBack** [comment]
其实上次我更新过的，还是不行啊。就刚才我又pods update了一下，现在的版本号是这样的
![2018-04-27 10 03 45](https://user-images.githubusercontent.com/30762999/39340754-71bd8d94-4a02-11e8-8f8d-24b163a0e933.png)
还是不行,是我这里的问题吗？

**Comment by theHeroisBack** [comment]
全屏按钮方法是这样
![2018-04-27 10 25 05](https://user-images.githubusercontent.com/30762999/39341332-4b9870a4-4a05-11e8-981c-c2c32d62761d.png)

**Comment by changsanjiang** [comment]
有 TeamViewer 吗? 要不远程看看

**Comment by theHeroisBack** [comment]
我先去看一下你的demo吧
