### ISSUE TITLE
大佬 有个断点问题 点击全屏按钮  就蹦在这里了

### ISSUE THREAD

**Issue by ChaoYuW** [changsanjiang/SJVideoPlayer#230]
#
![E7CF4372-12E3-40B8-9DBF-BD9B49F9BC0C](https://user-images.githubusercontent.com/8800570/72216198-1510b780-3559-11ea-95b1-a568a504a64c.png)

**Comment by victaie** [comment]
同样问题，点全屏控制层就卡死了
