### ISSUE TITLE
ipad下全屏按钮无效

### ISSUE THREAD

**Issue by frozenthrone** [changsanjiang/SJVideoPlayer#233]
**必现/偶发?**
必现

**描述bug**
点击右下角全屏按钮，没有反应，无法全屏

**Demo中是否存在同样的问题?**
是

**运行环境**
 - ipad mini4
 - iOS 13
 - Xcode 11.3.1
 - Swift

**Comment by ko1o** [comment]
@frozenthrone 这个问题麻烦问下解决了吗？我也遇到了

**Comment by LetsMemo** [comment]
專案設定為橫屏後, 無法切換為全屏幕播放... 畫面卡住了...
請問完整的配置方法? 
感謝....

**Comment by changsanjiang** [comment]
@LetsMemo @ko1o @frozenthrone  需要配置旋转: https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation

**Comment by HannibalRoyal** [comment]
如果按照作者的方案完整的设置后,还是无效的.
请看下 Info.plist 中的 Supported interface orientations (iPad)字段,去掉其他旋转项
