### ISSUE TITLE
视频再准备播放时，点击全屏按钮，横屏后，播放窗口仍为小屏，点击返回，被VideoPlayer视图覆盖，导致app假死

### ISSUE THREAD

**Issue by stoneUoU** [changsanjiang/SJVideoPlayer#234]
**必现/偶发?**
偶发

**描述bug**
视频再准备播放时，点击全屏按钮，横屏后，播放窗口仍为小屏，点击返回，被VideoPlayer视图覆盖，导致app假死

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
视频再准备播放时，点击全屏按钮，横屏后，播放窗口为横屏，点击返回，页面视图层级正常

**运行环境**
 - iPhone 6
 - iOS 12
 - Xcode 11.3
 - Objective-C

**截图**

![](https://s2.ax1x.com/2020/01/22/1AYyse.jpg)
![](https://s2.ax1x.com/2020/01/22/1Ad991.png)

**额外的**
最好能提供出现bug的Demo

**Comment by stoneUoU** [comment]
[

![](https://s2.ax1x.com/2020/01/22/1Ad991.png)
](url)

**Comment by stoneUoU** [comment]
![](https://s2.ax1x.com/2020/01/22/1Ad991.png)

**Comment by changsanjiang** [comment]
需要配置旋转: https://github.com/changsanjiang/SJVideoPlayer/wiki/Getting-Started#configure-rotation

**Comment by Wirlo** [comment]
同样出现该问题，希望能解决，卡死的问题。

**Comment by changsanjiang** [comment]
@Wirlo   配置一下....:   https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
