### ISSUE TITLE
视频过大的时候，画面卡顿，音频在播放，这个有办法解决吗

### ISSUE THREAD

**Issue by Flybor** [changsanjiang/SJVideoPlayer#236]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by zhangle520** [comment]
是的，我这里也出现的这个问题，播放的是一小时三十分钟的电影，拉动进度条到二十几分钟，画面就卡帧了

**Comment by zhangle520** [comment]
上面说的这个问题，后来发现是由于后台上传的电影视频比较老，帧率过低导致的画面卡顿，用比较新的视频就不会出现这个问题了
