### ISSUE TITLE
大神大神大神 ，导入的AliPlayer，如何使用SJVideoPlayer的UI啊

### ISSUE THREAD

**Issue by lgwResources** [changsanjiang/SJVideoPlayer#238]
大神大神大神 ，导入的AliPlayer，如何使用SJVideoPlayer的UI啊，希望和SJVideoPlayer的UI一致，可以大小屏切换

**Comment by changsanjiang** [comment]
参考这个, 修改一下podfile就可以了 https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-AliPlayer

**Comment by lgwResources** [comment]
大神  我pod的就是您的这个地址  
但是控制层如何添加呢？现在就是一个空的播放器

**Comment by changsanjiang** [comment]
你那边怎么写的呢?  是下面这样吗?

```Objective-C
// 1. import header file
#import "SJAliMediaPlaybackController.h"

_player = SJVideoPlayer.player;
// 2. Switch playback control to SJAliMediaPlaybackController
_player.playbackController = SJAliMediaPlaybackController.new;
// 3. play video
AVPUrlSource *source = [AVPUrlSource.alloc urlWithString:@"https://....mp4"];
_player.URLAsset = [SJVideoPlayerURLAsset.alloc initWithSource:source];
```

**Comment by lgwResources** [comment]
- (SJVideoPlayer *)videoPlay {
    if (!_videoPlay) {
        _videoPlay = [SJVideoPlayer player];
        _videoPlay.defaultEdgeControlLayer.hiddenBackButtonWhenOrientationIsPortrait = YES;
        _videoPlay.playbackController = SJAliMediaPlaybackController.new;
        [self.videoBJView addSubview:_videoPlay.playbackController.playerView];
        RB_WEAKSELF;
        [_videoPlay.playbackController.playerView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.offset(0);
            make.left.right.offset(0);
            make.height.offset(weakSelf.videoBJView.height);
        }];
    }
    return _videoPlay;
}


self.videoPlay.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithURL:[NSURL URLWithString:@"rtmp://58.200.131.2:1935/livetv/hunantv"]];

**Comment by lgwResources** [comment]
大神 您看下这样写有啥问题么

**Comment by changsanjiang** [comment]
```Objective-C
    - (SJVideoPlayer *)videoPlay {
        if (!_videoPlay) {
            _videoPlay = [SJVideoPlayer player];
            _videoPlay.defaultEdgeControlLayer.hiddenBackButtonWhenOrientationIsPortrait = YES;
            _videoPlay.playbackController = SJAliMediaPlaybackController.new;
            [self.videoBJView addSubview:_videoPlay.view];
            RB_WEAKSELF;
            [_videoPlay.view mas_makeConstraints:^(MASConstraintMaker *make) {
                make.top.offset(0);
                make.left.right.offset(0);
                make.height.offset(weakSelf.videoBJView.height);
            }];
        }
        return _videoPlay;
    }
```

**Comment by changsanjiang** [comment]
只是一开始修改playbackController即可,  其他操作不变

**Comment by lgwResources** [comment]
非常感谢、非常感谢、非常感谢😄
