### ISSUE TITLE
是否可以取消轉屏動畫(animated)

### ISSUE THREAD

**Issue by LetsMemo** [changsanjiang/SJVideoPlayer#239]
我看程式碼api的定義 多數有 animated 參數可帶入,
但是追code到深層套用動畫參數時, 它會帶入 YES, 而非帶入 animated參數...
這部分是否可以修一下... 否則不容易繼承改寫.... 

因為某些時候需要讓畫面直接轉屏而不需要動畫.. 
特別是控制方向有問題需要強制轉屏的時候就露餡了...

辛苦了.. 麻煩一下...

**Comment by changsanjiang** [comment]
好的,  晚上我会修一下, 感谢指出
