### ISSUE TITLE
請問可以在背景繼續播放影音檔嗎？

### ISSUE THREAD

**Issue by tommyz** [changsanjiang/SJVideoPlayer#24]
請問可以在背景繼續播放影音檔嗎？

**Comment by changsanjiang** [comment]
你好, 可以设置 `pauseWhenAppResignActive` 为NO, 即可在后台继续播放.

**Comment by changsanjiang** [comment]
你好, 请问资源是视频还是音频?

**Comment by changsanjiang** [comment]
你好, 后台播放视频和音乐需要设置 [pauseWhenAppDidEnterBackground] == NO(https://github.com/changsanjiang/SJVideoPlayer/blob/91711913a1e03e348242af549dfac8f3a1019935/SJVideoPlayerProject/Pods/SJBaseVideoPlayer/SJBaseVideoPlayer/SJBaseVideoPlayer.h#L327);

**Comment by woodssunny** [comment]
在ios13.3.1上 设置后台播放后，报错 Can't end BackgroundTask: no background task exists with identifier 19 (0x13), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
但是在ios12.4.5上后台播放正常。

**Comment by changsanjiang** [comment]
@woodssunny 这个应该是 iOS 13的Bug, 参考这个: https://stackoverflow.com/questions/23882495/cant-endbackgroundtask-no-background-task-exists-with-identifier-or-it-may-ha/58358986#58358986
