### ISSUE TITLE
Xcode 11.3.1 

### ISSUE THREAD

**Issue by ChineseXiaoYu** [changsanjiang/SJVideoPlayer#241]
**必现/偶发?**
必现/

**描述bug**
代码如下
 _player = SJVideoPlayer.player;
    [self.view addSubview:_player.view];
    [_player.view mas_makeConstraints:^(MASConstraintMaker *make) {
        if (@available(iOS 11.0, *)) {
            make.top.equalTo(self.view.mas_safeAreaLayoutGuideTop);
        } else {
            make.top.offset(20);
        }
        make.left.right.offset(0);
        make.height.equalTo(self.player.view.mas_width).multipliedBy(9/16.0);
    }];
    SJVideoPlayerURLAsset *asset = [SJVideoPlayerURLAsset.alloc initWithURL:[NSURL URLWithString:@"url"] specifyStartTime:0.f];
    _player.URLAsset = asset;

在模拟器跑的时候，当返回上一页面时。程序崩溃。cash到如下代码
- (void)dealloc {
    @try {
        [_target removeObserver:self forKeyPath:_keyPath];
    } @catch (NSException *__unused exception) { }
}

有时候没加载出视频的时候重新加载也会出现crash的情况。

当屏蔽掉一下代码不会出现闪退问题
SJVideoPlayerURLAsset *asset = [SJVideoPlayerURLAsset.alloc initWithURL:[NSURL URLWithString:@"url"] specifyStartTime:0.f];
    _player.URLAsset = asset;

**Demo中是否存在同样的问题?**
否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - pro 模拟器
 - iOS 13
 - Xcode 11.3.1
 - Objective-C

**Comment by changsanjiang** [comment]
#153

**Comment by ChineseXiaoYu** [comment]
我按照其他人的方法做了 还是返回的时候还是有问题啊 我pod版本1.8.3应该最新的啊

**Comment by ChineseXiaoYu** [comment]
153的方法并没有解决问题
