### ISSUE TITLE
播放本地缓存的视频，如果开启飞行模式会弹出网络提示覆盖掉，如何禁止

### ISSUE THREAD

**Issue by yaojunguang** [changsanjiang/SJVideoPlayer#243]
HI
您的播放器非常棒，最近发现一个问题，播放本地缓存的视频，如果开启飞行模式会弹出网络提示覆盖掉，如何禁止呢？
PS:
player.defaultEdgeControlLayer.isDisabledPromptWhenNetworkStatusChanges = true
这个开关无效

**Comment by changsanjiang** [comment]
@yaojunguang 你好, 查看一下版本是否是最新的. 在新版本中我修复过这个问题

**Comment by yaojunguang** [comment]
我用的就是最新的3.2.5，还是会出现同样的问题。
我用的aliyunplayer内核，调用是：
SJVideoPlayerURLAsset(source: source)

**Comment by changsanjiang** [comment]
好的, 我测试一下,  方便贴一下播放资源设置时的代码吗

**Comment by yaojunguang** [comment]
let source = AVPUrlSource()
                    if let link = VideoCacheService.tryGetCachePath(videoURL: item.link){
                        source.fileURL(withPath: link)
                        print("命中缓存，采用缓存播放")
                        //播放缓存的时候不检测网络
                        sjVideoPlayer?.defaultEdgeControlLayer.isDisabledPromptWhenNetworkStatusChanges = true
                    }else{
                        source.url(with: item.link)
                        //source.playerUrl = KTVHTTPCache.proxyURL(withOriginalURL: URL(string: item.link))
                    }
                    sjVideoPlayer!.urlAsset = SJVideoPlayerURLAsset(source: source)

麻烦了
