### ISSUE TITLE
iOS9 中間的緩衝轉圈圈控件不會消失

### ISSUE THREAD

**Issue by LetsMemo** [changsanjiang/SJVideoPlayer#244]
**必现/偶发?**
必现

**描述bug**
iOS9 中間的緩衝轉圈圈的View不會消失 (iOS12正常)

**Demo中是否存在同样的问题?**
iOS12正常, iOS9設備 (iPad3/the New iPad) 會出現

**你期望的结果是什么?**
緩衝完畢後轉圈圈的元件會自動隱藏

**运行环境**
 - Objective-C
 - iOS9

**截图**
如果有必要的话，请上传几张截图
![相片 2020-3-18 下午2 52 16](https://user-images.githubusercontent.com/61005073/76934672-85a5cd00-692a-11ea-8cc5-c5771adf3a51.jpg)
![相片 2020-3-18 下午2 52 23](https://user-images.githubusercontent.com/61005073/76934680-8b031780-692a-11ea-8e84-6762f0ebd9e4.jpg)

**额外的**
 (App還沒有上架, 目前無法提供)

**Comment by changsanjiang** [comment]
好的, 感谢提出, 晚上看看

**Comment by changsanjiang** [comment]
很抱歉这么晚回复，这个Bug在3.2.5.1(SJBaseVideoPlayer)中应该修复了。

**Comment by LetsMemo** [comment]
修復了... 感謝~ ^^
