### ISSUE TITLE
m3u8流暂停后恢复播放,怎么让视频流刷新到最新的进度,而不是从暂停的地方继续播

### ISSUE THREAD

**Issue by kingstal** [changsanjiang/SJVideoPlayer#246]

**Comment by changsanjiang** [comment]
试试这个:

```Objective-C
    _player.playbackObserver.timeControlStatusDidChangeExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {
        if ( player.assetStatus == SJAssetStatusReadyToPlay && player.isEvaluating ) {
            [player seekToTime:0 completionHandler:nil];
        }
    };
```

**Comment by kingstal** [comment]
> 试试这个:
> 
>     _player.playbackObserver.timeControlStatusDidChangeExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {
>         if ( player.assetStatus == SJAssetStatusReadyToPlay && player.isEvaluating ) {
>             [player seekToTime:0 completionHandler:nil];
>         }
>     };
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

我的版本还是3.0.3,还没有isEvaluating的属性,还有其他方案吗

**Comment by changsanjiang** [comment]
那个属性等价于这个, 直接替换吧
```Objective-C
- (BOOL)isEvaluating { return player.timeControlStatus == SJPlaybackTimeControlStatusWaitingToPlay && player.reasonForWaitingToPlay == SJWaitingWhileEvaluatingBufferingRateReason; }
```

**Comment by kingstal** [comment]
> 那个属性等价于这个, 直接替换吧
> 
> - (BOOL)isEvaluating { return player.timeControlStatus == SJPlaybackTimeControlStatusWaitingToPlay && player.reasonForWaitingToPlay == SJWaitingWhileEvaluatingBufferingRateReason; }
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

[player seekToTime:0 completionHandler:nil];  这个方法是从头开始播放,能不能刷新流到最新的进度,我的意思是例如暂停5s,恢复播放后,直接跳过这5s播放最新的

**Comment by changsanjiang** [comment]
我下午的时候测试过, 如果是直播, seek到0, 它的实际效果就是播放最新的.

**Comment by kingstal** [comment]
> 我下午的时候测试过, 如果是直播, seek到0, 它的实际效果就是播放最新的.

多谢解答,我再试试看.

**Comment by kingstal** [comment]
发现可以通过重新重新设置`URLAsset` 达到刷新流的目的
