### ISSUE TITLE
RTSP 集成的问题

### ISSUE THREAD

**Issue by sjxt** [changsanjiang/SJVideoPlayer#247]
参考这个使用ijk来播放: https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer

ld: '/Users/chenzhen/Desktop/ijkplaerDemo/Pods/ijkplayerssl/IJKMediaFrameworkWithSSL.framework/IJKMediaFrameworkWithSSL' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/chenzhen/Desktop/ijkplaerDemo/Pods/ijkplayerssl/IJKMediaFrameworkWithSSL.framework/IJKMediaFrameworkWithSSL' for architecture arm64

bitcode 设置为NO了 按照参考链接还是报这个错 能帮忙看看吗

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**运行环境**
 - iPhone 8
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**Comment by changsanjiang** [comment]
@sjxt podfile中如果使用了`use_frameworks!`, 就按照下面来操作吧

1. 终端先执行一下这个命令, 把 cocoapods 更新到最新版本
```ruby
gem install cocoapods
```

2. podfile 中的`use_frameworks!`修改为`use_frameworks! :linkage => :static`

**Comment by sjxt** [comment]
ok了  谢谢大佬

**Comment by sjxt** [comment]
ok了  谢谢大佬

**Comment by LS502311932** [comment]
![截屏2020-10-29 下午4 16 44](https://user-images.githubusercontent.com/19722504/97542682-281a4880-1a02-11eb-9242-fc89781c0d9d.png)
YYModel 跟YYKit冲突 怎么解决啊？？？？？？

**Comment by slash130** [comment]
> ![截屏2020-10-29 下午4 16 44](https://user-images.githubusercontent.com/19722504/97542682-281a4880-1a02-11eb-9242-fc89781c0d9d.png)
> YYModel 跟YYKit冲突 怎么解决啊？？？？？？

用这个
pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'

**Comment by slash130** [comment]
使用了 use_frameworks! :linkage => :static 后可以编译运行了，但是有些pod库在storyboard里报@IB错误。能只对IJK静态化吗？

**Comment by LS502311932** [comment]
> 使用了 use_frameworks! :linkage => :static 后可以编译运行了，但是有些pod库在storyboard里报@ib错误。能只对IJK静态化吗？

ok 解决了

**Comment by xzzgith** [comment]
> > 使用了 use_frameworks! :linkage => :static 后可以编译运行了，但是有些pod库在storyboard里报@ib错误。能只对IJK静态化吗？
> 
> ok 解决了
大佬是只对ijk静态化了吗

**Comment by changpk** [comment]
@sjxt 项目是OC，但是里面用的有其它的swift库，所以需要use_frameworks!这个标记，改完之后use_frameworks! :linkage => :static ,项目中的swift的库会报错，这个怎么处理呢？

**Comment by sjxt** [comment]
> @sjxt 项目是OC，但是里面用的有其它的swift库，所以需要use_frameworks!这个标记，改完之后use_frameworks! :linkage => :static ,项目中的swift的库会报错，这个怎么处理呢？

swift的库可以考虑用Carthage集成

**Comment by changpk** [comment]
> > @sjxt 项目是OC，但是里面用的有其它的swift库，所以需要use_frameworks!这个标记，改完之后use_frameworks! :linkage => :static ,项目中的swift的库会报错，这个怎么处理呢？
> 
> swift的库可以考虑用Carthage集成

测试了下，Carthage打包的framework引用进去的话，配置完之后，会提示桥接swift的头文件不存在！方便的话有邮箱或者QQ沟通一下么！

**Comment by sjxt** [comment]
> > > @sjxt 项目是OC，但是里面用的有其它的swift库，所以需要use_frameworks!这个标记，改完之后use_frameworks! :linkage => :static ,项目中的swift的库会报错，这个怎么处理呢？
> > 
> > 
> > swift的库可以考虑用Carthage集成
> 
> 测试了下，Carthage打包的framework引用进去的话，配置完之后，会提示桥接swift的头文件不存在！方便的话有邮箱或者QQ沟通一下么！我的邮箱是[x670990709@126.com](mailto:x670990709@126.com)

这个我也没啥办法，只能百度了，我对于个别swift库没法用，就直接手动导入进去的，再不行就换个库
