### ISSUE TITLE
全屏时  弹出viewcontroller 会导致异常

### ISSUE THREAD

**Issue by nicknull** [changsanjiang/SJVideoPlayer#248]
**必现/偶发?**
必现

**描述bug**
通过[UIApplication sharedApplication].keyWindow.rootViewController方式找到视频全屏播放的顶层controller  调用presentViewController  会导致[UIApplication sharedApplication].keyWindow.rootViewController对应的rootViewController消失
**Demo中是否存在同样的问题?**
是
**运行环境**
 - iPhone X
 - iOS 12.4.5
 - Xcode 11.3.1
 - Objective-C

**Comment by changsanjiang** [comment]
@nicknull 可以提供一下示例代码吗

**Comment by nicknull** [comment]
UIViewController *t =[[UIViewController alloc] init];
                t.title = @"测试";
                UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:t];
                [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:nav animated:YES completion:nil];


其中[[UIApplication sharedApplication].keyWindow.rootViewController  指向的是SJFullscreenModeViewController

**Comment by nicknull** [comment]
系统原因

**Comment by slash130** [comment]
@nicknull 请问这个系统问题有解吗？
