### ISSUE TITLE
从指定位置播放失效

### ISSUE THREAD

**Issue by mgcms** [changsanjiang/SJVideoPlayer#252]
**描述bug**

先调用：
self.videoPlayer.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithURL:[NSURL URLWithString:urlStr]];
后：
[self.videoPlayer seekToTime:timeInterval completionHandler:nil];
结果：还是从00:00开始播放

**你期望的结果是什么?**
能够从我设置的timeInterval的位置开始播放

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/77985022-d9121500-7345-11ea-8427-8c622b4a2f9e.png)
