### ISSUE TITLE
播放器全屏切后台再返回前台UI展示问题

### ISSUE THREAD

**Issue by kingstal** [changsanjiang/SJVideoPlayer#253]
你好,今天发现在iOS13的刘海屏上,播放器全屏切后台再回到前台,会导致UI变形,UI向中间压缩,两边空白,请问是什么原因?

版本:SJVideoPlayer 3.0.3

**Comment by changsanjiang** [comment]
在对应vc加上这个试试看:
```Objective-C
- (BOOL)shouldAutorotate {
    return NO;
}
```

**Comment by kingstal** [comment]
你好,这个问题暂时解决了,现在我想监听m3u8直播流的结束状态,用了`_player.playbackObserver.didPlayToEndTimeExeBlock`没有监听到.
请问有其他办法吗

**Comment by weiwei1991** [comment]
我也遇到了这样的问题,加上 - (BOOL)shouldAutorotate {
    return NO;
} 后，在iPhoneX、iPhone PRO MAX上还是俩边空白,中间变窄了,在iPhone8,8plus上没有问题

**Comment by kingstal** [comment]
> 我也遇到了这样的问题,加上 - (BOOL)shouldAutorotate {
> return NO;
> } 后，在iPhoneX、iPhone PRO MAX上还是俩边空白,中间变窄了,在iPhone8,8plus上没有问题

是不是iOS13的刘海屏会有这个问题? 试试用Xcode11打包

**Comment by weiwei1991** [comment]
我的就是xcode 11,iOS13.3,只要是superClass是UITableviewController就会是那样的问题,我刚把superClass改成UIViewController就好了,不知道在其他系统上还会有这样的问题吗

**Comment by VikBob** [comment]
我的系统导航栏也会出现这样的问题，并且加上 - (BOOL)shouldAutorotate {
return NO;
}还是解决不了问题。

**Comment by changsanjiang** [comment]
@VikBob  SJBaseVideoPlayer 更新到最新版 3.6.3 以上
