### ISSUE TITLE
真机模式下 视频无法播放

### ISSUE THREAD

**Issue by zzw19880707** [changsanjiang/SJVideoPlayer#254]
**必现/偶发?**
必现

**描述bug**
真机模式下，http://qn.yqdxcity.com/li3rthOE0mcwG2ZzPgR5GDVYcGvj  这个无法播放。日志为
SJAVMediaPlayer: 114 - -[SJAVMediaPlayer observeValueForKeyPath:ofObject:change:context:] - Error Domain=AVFoundationErrorDomain Code=-11821 "无法解码" UserInfo={NSLocalizedFailureReason=媒体数据无法被解码，可能已损坏。, NSLocalizedDescription=无法解码, NSUnderlyingError=0x28380c900 {Error Domain=NSOSStatusErrorDomain Code=-12911 "(null)"}}

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
能够正常播放
**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by zzw19880707** [comment]
七牛和b站的都能播放

**Comment by changsanjiang** [comment]
通过这个步骤, 切换至七牛的播吧 https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-PLPlayerKit
