### ISSUE TITLE
oc版本播放本地视频怎么播呢大神？直接播放就播放失败，unsupported URL

### ISSUE THREAD

**Issue by codeliu6572** [changsanjiang/SJVideoPlayer#256]
oc版本播放本地视频怎么播呢大神？没找到啊，直接播放就播放失败，unsupported URL

**Comment by codeliu6572** [comment]
怎么直接播放本地资源呢？

**Comment by changsanjiang** [comment]
试一下这个: [NSURL fileURLWithPath:@""]

**Comment by codeliu6572** [comment]
> 试一下这个: [NSURL fileURLWithPath:@""]

SJAVMediaPlayer: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x600002144300 {Error Domain=NSOSStatusErrorDomain Code=-1002 "(null)"}}


还是不行，我是这么写的，麻烦帮忙看下
            SJVideoPlayerURLAsset *asset = [[SJVideoPlayerURLAsset alloc] initWithURL:[NSURL fileURLWithPath:[_playUrl stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]]];

**Comment by changsanjiang** [comment]
@codeliu6572  playUrl 打印出来看看

**Comment by codeliu6572** [comment]
> @codeliu6572 playUrl 打印出来看看

SJAVMediaPlayer: Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x6000000342d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

SJAVMediaPlayer: Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x6000000342d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

file:///Users/Codeliu/Library/Developer/CoreSimulator/Devices/8F3F1114-8C2E-4B11-8F67-3C762E764D49/data/Containers/Data/Application/A57DB0BA-71EA-4039-894B-13C884711CA0/Documents/LXYDownloadMusic/%25E8%2593%259D%25E7%25AD%25B1%25E7%258E%2589vip.mp3
这是本地资源的路径

**Comment by codeliu6572** [comment]
我找到原因了，是因为我对本地路径进行了utf8转码，去掉本地路径转码就好了，感谢🙏这也算得上一个坑了，一般不太知道，又长知识了。 @changsanjiang

**Comment by codeliu6572** [comment]
一般在线播放链接带中文的是要转码的，本地资源转码后就找不到对应的资源文件了，所以本地资源不需要转码，尴尬呀，感谢，播放器很好用，赞👍
