### ISSUE TITLE
autoplay in collection view view自动播放：SJListViewAutoplayViewController只要播放新的视频然后返回列表页内存一直无法释放。

### ISSUE THREAD

**Issue by 214070779** [changsanjiang/SJVideoPlayer#264]
**必现/偶发?**
必现

**描述bug**
使用demo中SJListViewAutoplayViewController只要播放新的视频内存就无法释放。

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
进入SJListViewAutoplayViewController这个里面，然后退出内存可以得到释放

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**截图**
如果有必要的话，请上传几张截图
![image](https://user-images.githubusercontent.com/30347253/80942238-df008780-8e16-11ea-89b6-ebcb74a4e290.png)
![image](https://user-images.githubusercontent.com/30347253/80942314-10795300-8e17-11ea-9f55-33ac4b7905b3.png)

**额外的**
这个是杂们demo的bug。
autoplay in collection view view自动播放

**Comment by changsanjiang** [comment]
我刚测了一下, 这个泄漏貌似是系统级的, 咱们自己的代码没出现泄漏

**Comment by changsanjiang** [comment]
用模拟器跑一下, 可以定位具体的泄漏位置

**Comment by 214070779** [comment]
咋们这个没有大的内存泄漏，只是播放视频之后，内存一直无法释放，并非内存泄漏。我定位了下问题，是sdwebimage中的memCache的问题，清掉这个.就正常了。
