### ISSUE TITLE
想让返回键竖屏时常驻，全屏时取消常驻应该怎么弄？

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#266]
我想竖屏时让返回键常驻，这个在sdk里有配置项，进去全屏时想取消常驻，返回竖屏时再恢复常驻。这个需求应该怎么做？是否是监听全屏变化然后修改showResidentBackButton的设置？

**Comment by changsanjiang** [comment]
嗯，旋转之前改一下
