### ISSUE TITLE
pod关联了Masonry下载到项目

### ISSUE THREAD

**Issue by Chauvetok** [changsanjiang/SJVideoPlayer#267]
**你的新功能建议是否牵扯到某个常见的问题？**
我用这种方式下载库时：
pod 'SJBaseVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJBaseVideoPlayer.git'
pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'
发现SJ自动关联下载了Masonry？？而且这个还不是最新的Masonry！！

**你希望达到的效果**
我希望SJ的这种方式下载库时能做外部依赖，不应该绑定Masonry的

**Comment by changsanjiang** [comment]
pod update 试试,  我在依赖中没对 Masonry 做版本限制.

**Comment by Chauvetok** [comment]
我试过了，只要pod下载SJ的库，就会自动关联下载Masonry的，至于不是最新版本我至今也没找到原因所在，我删除本地索引库重新更新也不行。
另外，我发现添加自定义的button到player的view时，我添加到中心位置centerAdapter：[self.player.defaultEdgeControlLayer.centerAdapter addItem:item]是没有显示出来的，但是我使用topAdapter和bottomAdapter都是可以的，麻烦您抽空看看，谢谢

**Comment by changsanjiang** [comment]
向中间添加, 内部的约束需要自撑满(约束子视图撑满父视图)才能显示

**Comment by Chauvetok** [comment]
我用这个类方法添加到center位置是正常的：+ (instancetype)frameLayoutWithCustomView:(__kindof UIView *)customView tag:(SJEdgeControlButtonItemTag)tag
我以为也是和其它几个一样用这种方法：- (instancetype)initWithCustomView:(nullable __kindof UIView *)customView tag:(SJEdgeControlButtonItemTag)tag;这个方法添加到center是不行的，建议您注释说明一下吧。

**Comment by WIndFate** [comment]
<img width="452" alt="スクリーンショット 2020-05-14 10 39 48" src="https://user-images.githubusercontent.com/14509638/81883106-57153d00-95cf-11ea-9b3d-c9b5dd92c2a9.png">
确实依赖了1.1的Masonry

**Comment by WIndFate** [comment]
<img width="861" alt="スクリーンショット 2020-05-14 10 58 06" src="https://user-images.githubusercontent.com/14509638/81884057-d0159400-95d1-11ea-9be8-885f22489699.png">
想问下，我用xcode 11.3.1导入后编译会报这个错，是什么原因呢

**Comment by WIndFate** [comment]
> <img alt="スクリーンショット 2020-05-14 10 58 06" width="861" src="https://user-images.githubusercontent.com/14509638/81884057-d0159400-95d1-11ea-9be8-885f22489699.png">
> 
> 想问下，我用xcode 11.3.1导入后编译会报这个错，是什么原因呢

解决了，把编译环境设置成Legacy Build System就好了

**Comment by changsanjiang** [comment]
我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的

**Comment by Chauvetok** [comment]
大佬，我还有一个问题就是，我想在视频view中间自定义添加个播放暂停的按钮，和其它控件一起显示和隐藏，但是我一遵守了self.player.controlLayerDelegate = self 这个代理，想获取点击视频空白处回调的代理，但原来默认的进度条、播放等控件都没有了，请问下该如何处理呢，感谢。
另外我看了您的demo，使用centerAdapter添加到中心位置的控件是不和其它默认的控件一起显示或隐藏的，但是使用topAdapter和bottomAdapter却是可以的，我搞不明白centerAdapter为啥和其它位置的逻辑不一样？！

**Comment by WIndFate** [comment]
> 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的

恩恩，我刚也去确认了是最新版本，忘了回复了

**Comment by Chauvetok** [comment]
> > 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的
> 
> 恩恩，我刚也去确认了是最新版本，忘了回复了

你现在下载的Masonry版本，是否有mas_safeAreaLayoutGuideHeight这个属性的呢？

**Comment by Chauvetok** [comment]
> 大佬，我还有一个问题就是，我想在视频view中间自定义添加个播放暂停的按钮，和其它控件一起显示和隐藏，但是我一遵守了self.player.controlLayerDelegate = self 这个代理，想获取点击视频空白处回调的代理，但原来默认的进度条、播放等控件都没有了，请问下该如何处理呢，感谢。
> 另外我看了您的demo，使用centerAdapter添加到中心位置的控件是不和其它默认的控件一起显示或隐藏的，但是使用topAdapter和bottomAdapter却是可以的，我搞不明白centerAdapter为啥和其它位置的逻辑不一样？！


上面的问题还是没解决。但是我用另外一个办法解决了。就是不用代理，直接用self.player.controlLayerAppearObserver.appearStateDidChangeExeBlock的回调来监听处理，在里面再判断控制层是否显示controlLayerAppeared，来决定我加的按钮是否显示！这样原来默认的控件样式有，我自定义加的控件逻辑也正常处理好了。

**Comment by WIndFate** [comment]
> > > 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的
> > 
> > 
> > 恩恩，我刚也去确认了是最新版本，忘了回复了
> 
> 你现在下载的Masonry版本，是否有mas_safeAreaLayoutGuideHeight这个属性的呢？

<img width="564" alt="スクリーンショット 2020-05-14 11 45 46" src="https://user-images.githubusercontent.com/14509638/81886819-a0b65580-95d8-11ea-94b7-07b26a09305a.png">
有的，应该没什么问题

**Comment by WIndFate** [comment]
> > > > 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的
> > > 
> > > 
> > > 恩恩，我刚也去确认了是最新版本，忘了回复了
> > 
> > 
> > 你现在下载的Masonry版本，是否有mas_safeAreaLayoutGuideHeight这个属性的呢？
> 
> <img alt="スクリーンショット 2020-05-14 11 45 46" width="564" src="https://user-images.githubusercontent.com/14509638/81886819-a0b65580-95d8-11ea-94b7-07b26a09305a.png">
> 
> 有的，应该没什么问题

看错了，没有Height、但是版本确实是最新的，我再看看

**Comment by Chauvetok** [comment]
> > > > 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的
> > > 
> > > 
> > > 恩恩，我刚也去确认了是最新版本，忘了回复了
> > 
> > 
> > 你现在下载的Masonry版本，是否有mas_safeAreaLayoutGuideHeight这个属性的呢？
> 
> <img alt="スクリーンショット 2020-05-14 11 45 46" width="564" src="https://user-images.githubusercontent.com/14509638/81886819-a0b65580-95d8-11ea-94b7-07b26a09305a.png">
> 
> 有的，应该没什么问题

不是，这几个属性早就有了的，你直接输入这个mas_safeAreaLayoutGuideHeight，看有没有，我不知道是我本地索引库的问题还是三方库本身没有更新到pods上的问题，麻烦你看看确认一下，感谢。。

**Comment by Chauvetok** [comment]
> > > > > 我去确认了一下, Masonry 的最新版是1.1.0, 你拉下来的就是最新版的
> > > > 
> > > > 
> > > > 恩恩，我刚也去确认了是最新版本，忘了回复了
> > > 
> > > 
> > > 你现在下载的Masonry版本，是否有mas_safeAreaLayoutGuideHeight这个属性的呢？
> > 
> > 
> > <img alt="スクリーンショット 2020-05-14 11 45 46" width="564" src="https://user-images.githubusercontent.com/14509638/81886819-a0b65580-95d8-11ea-94b7-07b26a09305a.png">
> > 有的，应该没什么问题
> 
> 看错了，没有Height、但是版本确实是最新的，我再看看

 
那就是了三方库本身的问题了，我已经反馈过了，但是还没回复。感谢你和作者大佬的及时回复，谢谢。。
