### ISSUE TITLE
[SJEdgeControlLayerAdapters]刘海屏全屏后返回竖屏edgeControl的safeArea未更新

### ISSUE THREAD

**Issue by szdkkk** [changsanjiang/SJVideoPlayer#270]
如图所示
<img width="415" alt="img" src="https://user-images.githubusercontent.com/5537174/81890426-8aa89500-95d8-11ea-9a03-77ceee82e981.png">

**Comment by JunLi0053** [comment]
大佬，请问怎么解决？

**Comment by changsanjiang** [comment]
额…… Demo有同样的问题吗？

**Comment by JunLi0053** [comment]
> 额…… Demo有同样的问题吗？

没有啊，就是好奇怪，我也是图片的那个问题

**Comment by changsanjiang** [comment]
你看看能不能搞个又这个问题的demo

**Comment by JunLi0053** [comment]
> 你看看能不能搞个又这个问题的demo

找到原因了，有导航控制器的要在appdelegate那里添加controller的扩展，我觉得应该写到readme那比较好吧
