### ISSUE TITLE
如何禁止拖动进度条之后视频自动播放了

### ISSUE THREAD

**Issue by Chauvetok** [changsanjiang/SJVideoPlayer#274]
**你希望达到的效果**
我拖动完进度条之后，不要自动播放视频，只有我手动点击播放时才可播放

**你能考虑到的可选实现方案**
看了下文档，没有看到进度条的监听回调之类的，设置了autoplayWhenSetNewAsset = NO，也没有用。
麻烦大佬告之一下，感谢

**Comment by changsanjiang** [comment]
player.resumePlaybackWhenPlayerHasFinishedSeeking = NO

**Comment by Chauvetok** [comment]
解决了，感谢大佬。
