### ISSUE TITLE
和JXCategoryView库一起用，tableviewcell中添加播放器，旋转全屏，在推出，会导致黑屏

### ISSUE THREAD

**Issue by ZhouChengLong** [changsanjiang/SJVideoPlayer#275]
**必现/偶发?**
必现

**描述bug**

https://github.com/ZhouChengLong/bug

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.3
 - Objective-C

**Comment by changsanjiang** [comment]
感觉是播放器没有正常释放, 贴一下播放器使用的代码或者你查查有没有循环引用

**Comment by changsanjiang** [comment]
另外还有一个小问题是你那边应该没有配置旋转. 底部的控制器也触发了旋转了, 最好是配置一下
