### ISSUE TITLE
可以解析并修改m3u8文件吗？

### ISSUE THREAD

**Issue by WIndFate** [changsanjiang/SJVideoPlayer#278]
公司给的.m3u8视频地址，需要我解析m3u8后修改内部.ts文件名，保持和m3u8文件名一致才能播放，框架有办法解析编辑当前链接的m3u8文件吗？

**Comment by changsanjiang** [comment]
暂时没有这个功能,  目前的解析都是各家播放器内部封装好的.  后续可能会结合本地代理服务器做视频缓存这块, 这个功能到时候可以考虑一下.

**Comment by changsanjiang** [comment]
@WIndFate 我目前在做的一个边播边缓存的库, https://github.com/changsanjiang/SJMediaCacheServer, 理论上可以实现自己解析m3u8文件, 可以加我QQ: 1779609779, 或者加群: 930508201 探讨一下.
