### ISSUE TITLE
我输出总是遇到这个Log,是怎么回事?

### ISSUE THREAD

**Issue by shenguanjiejie** [changsanjiang/SJVideoPlayer#28]
(lldb) po imageView.size
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here
warning: property access result unused - getters should not be used for side effects
declared here with type 'SJDisappearType'
error: instance method 'disappearType' has incompatible result types in different translation units ('SJViewDisappearType' vs. 'SJDisappearType')
instance method 'disappearType' also declared here

**Comment by changsanjiang** [comment]
这个是在swift里面的吧?

**Comment by changsanjiang** [comment]
两个分类方法重名了, 我后面处理一下

**Comment by shenguanjiejie** [comment]
@changsanjiang 嗯嗯 好 不是swift 我做了一些处理 能让LLDB直接打印CGSize

**Comment by shenguanjiejie** [comment]
我写错了 上面应该是po imageView.frame 不过是一个意思
