### ISSUE TITLE
播放高大于宽的视屏，点击全屏后旋转手机，页面跟随旋转的BUG

### ISSUE THREAD

**Issue by ChrisChen888** [changsanjiang/SJVideoPlayer#281]
**必现/偶发?**
必现

**描述bug**
下载了您的简书横竖屏demo之后（地址：https://www.jianshu.com/p/3ec96c663486），使用播放器播放高大于宽的视屏，全屏是直接充满屏幕的，但全屏后手机或模拟器旋转之后视视屏却跟随旋转了，并且已经重写了当前控制器的shouldAutorotate方法返回false。
但是使用您项目的Demo跑就没有问题，我也对比了代码，除了您简书文章中提到的三个step，也没有找到其他的不同配置。
请问该怎么处理才能高大于宽的视屏全屏播放后即使旋转手机始终保持竖屏播放呢？

**Demo中是否存在同样的问题?**
横竖屏demo存在问题
项目demo没有问题

**你期望的结果是什么?**
播放高大于宽的视屏，点击全屏，即使旋转手机始终保持竖屏播放

**运行环境**
 - iPhone X
 - iOS 13.4.1
 - Xcode 11.4.1

 Objective-C和Swift都存在

**截图**
![Uploading WX20200526-120639@2x.png…]()

**额外的**

[OCTestDemo2.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4679856/OCTestDemo2.zip)

**Comment by ChrisChen888** [comment]
<img width="810" alt="WX20200526-120639@2x" src="https://user-images.githubusercontent.com/62169936/82863680-59738180-9f55-11ea-9822-1ca926326cde.png">
请查看这个截图

**Comment by changsanjiang** [comment]
@ChrisChen888 感谢指出, 已定位到问题.  弹出的`SJFitOnScreenModeViewController`需要包一层导航控制器, 才不会触发旋转.  我下版本个给修修 .

**Comment by ChrisChen888** [comment]
感谢回复，今天上午定位时觉得可能是这个问题，但是我进到SJFitOnScreenModeViewController中您自定义的弹出全屏控制器的转场方法（如图），尝试包装了导航控制器，仍然不能修复这个问题，由于项目紧迫，所有没有更深入的看您的代码。
由于项目中正在使用您封装的这个库，烦请告知一下有没有稍快捷的修复方法呢，或者您有空可否辛苦您发一个demo给我呢？
[SJVideoPlayerDemo_new.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4680442/SJVideoPlayerDemo_new.zip)
![WX20200526-150422](https://user-images.githubusercontent.com/62169936/82870449-8f6b3280-9f62-11ea-9348-c284a4881660.png)

**Comment by ChrisChen888** [comment]
![WX20200526-150422](https://user-images.githubusercontent.com/62169936/82870562-bde90d80-9f62-11ea-9bda-132415b37232.png)

**Comment by ChrisChen888** [comment]
`@synthesize viewController = _viewController;
- (SJFitOnScreenModeViewController *)viewController {
    if ( _viewController == nil ) {
        _viewController = SJFitOnScreenModeViewController.alloc.init;
        NSTimeInterval duration = self.duration;
        __weak typeof(self) _self = self;
        [_viewController setTransitionDuration:duration presentedAnimation:^(__kindof UIViewController * _Nonnull vc, SJAnimationCompletionHandler  _Nonnull completion) {
            __strong typeof(_self) self = _self;
            if ( !self ) return;
            [self _presentedAnimationWithDuration:duration completionHandler:completion];
        } dismissedAnimation:^(__kindof UIViewController * _Nonnull vc, SJAnimationCompletionHandler  _Nonnull completion) {
            __strong typeof(_self) self = _self;
            if ( !self ) return;
            [self _dismissedAnimationWithDuration:duration completionHandler:completion];
        }];
    }
    return _viewController;
}`

**Comment by changsanjiang** [comment]
直接更新吧,  我刚刚修复了

**Comment by ChrisChen888** [comment]
已经更新了，非常感谢大神！鞠躬！
