### ISSUE TITLE
 默认的边缘控制层的bottomAdapter调用 removeItemForTag后，只保留了全屏button，如何保持全屏按钮在最后显示

### ISSUE THREAD

**Issue by hYRamos** [changsanjiang/SJVideoPlayer#282]
`[_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_Separator];
    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_DurationTime];
    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_Play];
    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_CurrentTime];

    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_Separator];
    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_Progress];
    [_player.defaultEdgeControlLayer.bottomAdapter removeItemForTag:SJEdgeControlLayerBottomItem_LIVEText];
    [_player.defaultEdgeControlLayer.topAdapter removeItemForTag:SJEdgeControlLayerBottomItem_LIVEText];
    _player.showMoreItemToTopControlLayer = NO;
    _player.defaultEdgeControlLayer.hiddenBottomProgressIndicator = YES;
    _player.defaultEdgeControlLayer.hiddenTitleItemWhenOrientationIsPortrait = YES;
    _player.defaultEdgeControlLayer.hiddenBackButtonWhenOrientationIsPortrait = YES;
    [_player.defaultEdgeControlLayer.bottomAdapter reload];`
此时全屏按钮显示在了最左侧，如何在最右侧显示，最新的版本

**Comment by changsanjiang** [comment]
往前面插入一个item，设置这个item.fill=YES。

**Comment by hYRamos** [comment]
> 往前面插入一个item，设置这个item.fill=YES。

感谢大佬
