### ISSUE TITLE
接入播放器后出现内存泄露问题

### ISSUE THREAD

**Issue by ChrisChen888** [changsanjiang/SJVideoPlayer#285]
**必现/偶发?**
必现

**描述bug**
在我的项目中接入的播放器，在使用到改播放器的页面，也调用了对应的如下方法，但是使用leaks调试发现出现大量的内存泄露，导致内存异常，App调用处理内存警告的方法。于是我新开项目，发现只要接入了您的SJVideoPlayer，没有做任何引用操作，就会报附件如图所示NSPathStore的内存泄露，看调用栈像是初始化图片做了一些I/O的操作，可能次内存泄露只是导致我的App内存异常的一部分原因，因为我本人对于处理内存泄露经验较少，所以您能分析并告知我此内存泄露对于App的影响吗，或则有其他的修复方案吗？
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        if self.player != nil {
            self.player.vc_viewWillDisappear()
        }
        self.clearAllNotice()
    }

    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        if self.player != nil {
            self.player.vc_viewDidDisappear()
        }
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if self.player != nil {
            self.player.vc_viewDidAppear()
        }
    }

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
处理内存泄露

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
![leaks](https://user-images.githubusercontent.com/62169936/84099005-3956be80-aa3b-11ea-9bb6-c859390a855b.png)
![leaks2](https://user-images.githubusercontent.com/62169936/84099080-5e4b3180-aa3b-11ea-92f3-766122442159.png)

**额外的**
[tinyduo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4749575/tinyduo.zip)

**Comment by changsanjiang** [comment]
这个泄漏是系统级的, 暂时不用考虑它.

**Comment by ChrisChen888** [comment]
明白了，那大神再问您个问题，就是我的App在进行网络请求的时候，也会报很多如图所示的CFNetwork 和 newJSONString的问题，看调用栈又定位不到代码，能给我点处理的建议吗，非常感谢！
![leaks3](https://user-images.githubusercontent.com/62169936/84100503-96a03f00-aa3e-11ea-9456-4b333a51d066.png)

**Comment by ChrisChen888** [comment]
![image](https://user-images.githubusercontent.com/62169936/84100653-e848c980-aa3e-11ea-9b9c-18eff4f756c7.png)

**Comment by changsanjiang** [comment]
用真机不行, 需要用模拟器调试, 可以看到调用堆栈

**Comment by ChrisChen888** [comment]
好的，我刚才接入了腾讯阅读的库MLeaksFinder，再使用到SJvideoPlayer的页面，调用了以下方法,页面可以正常退出，并且调用了deinit方法（如图所示），但是MLeaksFinder却报了内存泄露，感觉应该是类单例的问题，但是MLeaksFinder不智能错误的报告了，上传了具体log烦请您帮忙看下，谢谢。

`
override func viewWillDisappear(_ animated: Bool) {
super.viewWillDisappear(animated)
if self.player != nil {
self.player.vc_viewWillDisappear()
}
self.clearAllNotice()
}
override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated)
    if self.player != nil {
        self.player.vc_viewDidDisappear()
        self.player` = nil
    }
}
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    if self.player != nil {
        self.player.vc_viewDidAppear()
    }
}`
![image](https://user-images.githubusercontent.com/62169936/84104017-39f55200-aa47-11ea-9809-55c251ad4995.png)
