### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by iHZW** [changsanjiang/SJVideoPlayer#287]
必现/偶发?
必现

描述bug
首先使用 iOS 8.1.2 系统的手机 进入视频会crash 原因是[self->_window.rootViewController loadViewIfNeeded];这个方法需要 ios9系统才可以使用,我做了 判断 if (@available(iOS 9.0, *)), 但是进入视频之后横屏,会导致视频偏移屏幕, 多试几次之后还容易导致crash

Demo中是否存在同样的问题?
是

你期望的结果是什么?
旋转正常使用就好,crash应该和这个旋转有关系

运行环境

iPhone 5s
iOS 8.1.2
Xcode 11.2.1
Objective-C
截图
如果有必要的话，请上传几张截图

额外的
最好能提供出现bug的Demo

**Comment by iHZW** [comment]
问题解决了  ios8 系统导致的crash  和 横屏视图消失问题
解决方案如下
1: 解决crash
SJRotationManager  类中
搜索  [self->_window.rootViewController loadViewIfNeeded]
loadViewIfNeeded 方法ios9才可以使用
修改为如下
            if (@available(iOS 9.0, *)) {
                [self->_window.rootViewController loadViewIfNeeded];
            }else{
                [self->_window.rootViewController loadView];
                [self->_window.rootViewController viewDidLoad];
            }
 然后在dealloc添加如下代码 (有个通知没有移除)
- (void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
这样ios8 上crash的问题就解决了

2: 解决横屏视图消失的问题
使用为ios8系统下使用   self->_window = [SJFullscreenModeWindow new];  获得的到window的frame为(0,0,0,0),  我的解决方案是如果为空,则给一个frame,代码如下
       
         self->_window = [SJFullscreenModeWindow new];
            /**< 解决iOS 8.0系统得到的window 的frame为空 导致旋转视图消失的问题 */
            if (self.window.frame.size.width == 0 &&
                self.window.frame.size.height == 0) {
                self.window.frame = [UIScreen mainScreen].bounds;
            }

**Comment by changsanjiang** [comment]
@iHZW 感谢指出,  我手头没有 8.0的测试机了, 这块的测试不到位, 再次感谢.

**Comment by changsanjiang** [comment]
已修

**Comment by iHZW** [comment]
大佬这技术很厉害,代码写的扩展性很强,感谢分享
