### ISSUE TITLE
如何后台连续播放声音

### ISSUE THREAD

**Issue by hponiang** [changsanjiang/SJVideoPlayer#291]
我想当用户将整个程序切换到后台时，仍播放声音，并自动播放下一集，这个有比较方便的实现方法吗

**Comment by changsanjiang** [comment]
1. 配置后台播放(https://github.com/changsanjiang/SJVideoPlayer#3.18)
2.配置播放列表(Demo中的`播放列表控制`)

**Comment by hponiang** [comment]
这速度，谢谢哈，我试一下
