### ISSUE TITLE
cocoapods 集成，报很多mas_safeAreaLayoutGuideLeft masonry库的error，对比了一下masonry，版本一样，但是masonry文件内容不一样。

### ISSUE THREAD

**Issue by zhoustarstar** [changsanjiang/SJVideoPlayer#292]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
饿…… mas最新的是1.1.0，你看看版本，应该不是最新版的

**Comment by DengJu** [comment]
问题：在collectionviewcell中播放视频（类似抖音），一直上下滑动界面，出现了看不到视频，只有音频的问题，应该怎么解决这个问题呢？
