### ISSUE TITLE
在tableview中使用

### ISSUE THREAD

**Issue by abc8312111** [changsanjiang/SJVideoPlayer#293]
**必现/偶发?**
必现

**描述bug**
清晰简单地描述这个bug是啥
tableview中使用 player的pan手势消失，无法使用
**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果
我希望能增加一个参数，或者告知下，怎样能在tableview中也开启左右滑动的手势

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
///
/// 在cell中播放时, 是否允许水平方向触发Pan手势.
///
///         default value is NO
///
@property (nonatomic) BOOL allowHorizontalTriggeringOfPanGesturesInCells;

@abc8312111  设置 yes

**Comment by abc8312111** [comment]
谢谢作者大大秒回复

**Comment by abc8312111** [comment]
请您和咖啡，有微信么？文档图挂了
