### ISSUE TITLE
Error=-25300 和Error Domain=AVFoundationErrorDomain Code=-11828

### ISSUE THREAD

**Issue by 674397611** [changsanjiang/SJVideoPlayer#294]
https://v.youku.com/v_show/id_XNDI2NjIzMTU1Mg==
播放上面链接无法播放，报
Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}
Error Domain=AVFoundationErrorDomain Code=-11828

**Comment by changsanjiang** [comment]
这个地址对应的一个网页, 不是真实的视频地址. 需要传递视频URL才可以播放
