### ISSUE TITLE
直接全屏播放界面会卡死 必现的 bug ，3.2.4 之后的版本就会出现这个问题

### ISSUE THREAD

**Issue by AlexBang** [changsanjiang/SJVideoPlayer#298]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
Demo里的 旋转控制 3 有同样的问题吗？

**Comment by AlexBang** [comment]
[光子 2020-07-07 09.31.05.mp4.zip](https://github.com/changsanjiang/SJVideoPlayer/files/4906102/2020-07-07.09.31.05.mp4.zip)录屏了 3.2.5版本，进入全屏播放操作界面都没用，直接卡死

**Comment by AlexBang** [comment]
我只pod 了SJVideoPlayer这个有控制层的，会不会是SJBaseVideoPlayer版本问题。他是最新的 3.3.3

**Comment by changsanjiang** [comment]
@AlexBang 参考Demo 中的 旋转控制 3,  用 modal的方式呈现vc
