### ISSUE TITLE
上下滑音量闪动,手机音量键不管用

### ISSUE THREAD

**Issue by kilent** [changsanjiang/SJVideoPlayer#3]

**Comment by changsanjiang** [comment]
你好, 已修复. 
之前音量视图使用的是自定义的. 现在改回使用系统的了.

**Comment by kilent** [comment]
谢谢,辛苦了! 不知道是不是错觉,我觉得滑动调音量有点卡,调亮度的就感觉非常顺畅

**Comment by changsanjiang** [comment]
可能是pan手势偏移的计算加的有点少了. 我再看看

**Comment by changsanjiang** [comment]
兄弟, 改好了, 你看看效果咋样

**Comment by kilent** [comment]
感觉没怎么变,只滑一下的话还好,不松手反复滑就非常明显了,你可以试一下,另外反复滑动调亮度CPU最高14,调音量却能到24
