### ISSUE TITLE
如何自定义默认控制层

### ISSUE THREAD

**Issue by kingstal** [changsanjiang/SJVideoPlayer#301]
`@property (nonatomic, strong, readonly) SJEdgeControlLayer *defaultEdgeControlLayer;`

你好,defaultEdgeControlLayer是只读属性,.m文件通过懒加载创建.
现在产品要求自定义控制层的样式,请问该如何替换?

**Comment by changsanjiang** [comment]
用这个的方法替换控制层. 
```
player.switcher addControlLayerForIdentifier:SJControlLayer_Edge lazyLoading:...
```

**Comment by kingstal** [comment]
好的 多谢
