### ISSUE TITLE
Implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99

### ISSUE THREAD

**Issue by abc8312111** [changsanjiang/SJVideoPlayer#305]
**必现/偶发?**
必现

**描述bug**
pod 'SJMediaCacheServer' 时会引入CocoaHTTPServer 然后就报上面的错。求助怎么解决

**Demo中是否存在同样的问题?**
否

**你期望的结果是什么?**
希望正确引入 

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
替换一下这个文件:  https://github.com/changsanjiang/SJMediaCacheServer/issues/2
