### ISSUE TITLE
在tableviewcell中播放时不响应tableview的上下滚动

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#308]
Xcode版本：11.3
swift版本：5

我先创建了一个自定义类，继承自UIView添加继承SJPlayModelSuperview。然后创建一个tableviewcell的类，添加了一个继承自定义UIView的视图。在tableview类的didselect方法里通过官方说明V2的方法配置Model然后播放视频。视频播放正常但是正在播放视频的部分只响应播放器的控制手势无法上下滚动tableview。还有在cell播放视频的时候横向滑动的手势确实是没弹出进度调整的那个视图，但是横向滑动并没有失效，横向滑动视频会重新开始播放。

**Comment by changsanjiang** [comment]
已修复

**Comment by slash130** [comment]
@changsanjiang 在3.2.6上修复的吗？还是稍晚有新版本？

**Comment by changsanjiang** [comment]
不在这里, 是basePlayer更了

**Comment by slash130** [comment]
@changsanjiang 好的 谢谢！
