### ISSUE TITLE
How can I set auto play on video in CollectionView?

### ISSUE THREAD

**Issue by Sothearath** [changsanjiang/SJVideoPlayer#31]
I want to add auto play on CollectionViewCell but auto play video doesn't work properly.

**Comment by changsanjiang** [comment]
Sorry, this property is the meaning of autoplay after the asset is initialized. not automatically played in the view.
The feature you said, I will implement the next version.

**Comment by changsanjiang** [comment]
Hello, @Sothearath , The latest version I have added the list view auto play function, as follows. You can use it with `pod update`

![image](https://user-images.githubusercontent.com/25744224/42548354-37fa3990-84f9-11e8-8834-3d7314ce5599.png)

**Comment by Sothearath** [comment]
@changsanjiang It works well. Thanks for a nice solution.
