### ISSUE TITLE
大佬  ios 14 beat 系统下 m3u8 进入后台 后手机锁屏一会儿，再回到前台 ，无法继续播放视频

### ISSUE THREAD

**Issue by lzylzy1991** [changsanjiang/SJVideoPlayer#315]
ios 14 beat 系统下 m3u8 进入后台 后手机锁屏一会儿，再回到前台 ，无法继续播放视频

**Comment by WXinYi** [comment]
我也遇到同样的问题了

**Comment by WM520** [comment]
SJUIKit/SJSQLite3+Private.h' file not found 有遇到过吗

**Comment by CoderQifly** [comment]
> ios 14 beat 系统下 m3u8 进入后台 后手机锁屏一会儿，再回到前台 ，无法继续播放视频

我也遇到了,请问有解决方案吗?

**Comment by changsanjiang** [comment]
更新一下

**Comment by LongJiangSB** [comment]
> 更新一下

请问应该更新到那个版本呢？当前使用版本 SJVideoPlayer (3.2.9)，还是有锁屏后，无法继续播放的情况。

**Comment by changsanjiang** [comment]
@LongJiangSB  Demo中是最新的代码, 在Demo试试看.  如果还有这个问题的话, 就把链接发我一个, 我测试一下.

**Comment by LongJiangSB** [comment]
> @LongJiangSB Demo中是最新的代码, 在Demo试试看. 如果还有这个问题的话, 就把链接发我一个, 我测试一下.

好的，改成demo的代码后可以了，配置问题，谢谢
