### ISSUE TITLE
这个就是播放不了rtsp的视频吗

### ISSUE THREAD

**Issue by zhouZhiYonglog** [changsanjiang/SJVideoPlayer#317]
这个就是不能播放rtsp的视频吗？

**Comment by changsanjiang** [comment]
按这指南, 播放控制模块可以切换至第三方SDK:

    - [Use ijkplayer](https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-ijkplayer)
    - [Use AliPlayer](https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-AliPlayer)
    - [Use AliyunVodPlayer](https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-AliVodPlayer)
    - [Use PLPlayerKit](https://github.com/changsanjiang/SJVideoPlayer/wiki/Use-PLPlayerKit)

**Comment by zhouZhiYonglog** [comment]
好的，谢谢！
