### ISSUE TITLE
在tableviewcell中播放时，tableview上拉加载造成播放视频的cell错位。

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#320]
这个不知道是不是个例，比如一页数据有10个视频，把tableview上滑到第7或第8个cell时点击播放视频，在播放状态下接着上拉tableview触发mj的上拉加载，加载第二页成功后之前播放视频那个cell会往上跳一个格，之前如果是在第8个cell中播放那就会变成在第7个cell里播放，上下多滚动几次tableview播放视频的cell就又恢复成在第8个cell里播放了。

**Comment by slash130** [comment]
这个问题发现是因为上拉加载下一页的数据后reloaddata造成的错位，有人知道这个需要怎么解决吗？

**Comment by slash130** [comment]
此问题已解决

**Comment by Arya-Wang** [comment]
您好  请问您是怎么解决的呢
