### ISSUE TITLE
how i get updated with realtime video time interval listener

### ISSUE THREAD

**Issue by Najamus** [changsanjiang/SJVideoPlayer#322]
Basically i want to add ads when user watch half video.

there is any delegate method or other way to get realtime video progress (time interval).

**Comment by guanerlin** [comment]
_player.playbackObserver.timeControlStatusDidChangeExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {
            __strong typeof(_self) self = _self;
            if ( !self ) return;
            [player.prompt show:[NSAttributedString sj_UIKitText:^(id<SJUIKitTextMakerProtocol>  _Nonnull make) {
                make.append(player.isPaused ? @"已暂停" : @"正在播放中"); // 提示
                make.textColor(UIColor.whiteColor);
            }] duration:-1];
            
            // 播放器处于播放中时, 纠正`pageHeaderView`的位置
            if ( player.isPlaying ) {
                UITableViewController *tableViewController = self.pageViewController.focusedViewController;
                UIView *pageHeaderView = self.pageViewController.headerView;
                UITableView *tableView = tableViewController.tableView;
                CGPoint offset = tableView.contentOffset;
                CGRect rect = [pageHeaderView convertRect:pageHeaderView.bounds toView:tableView.superview];
                offset.y += rect.origin.y;
                // 加个动画, 顺畅一些
                [UIView animateWithDuration:0.4 animations:^{
                    CGRect frame = pageHeaderView.frame;
                    frame.origin.y -= rect.origin.y;
                    pageHeaderView.frame = frame;
                    [tableViewController.tableView setContentOffset:offset animated:NO];
                }];
            }
        };
