### ISSUE TITLE
从指定的位置开始播放，seek 不准确, accurateSeeking 怎么修改值

### ISSUE THREAD

**Issue by Hukandi** [changsanjiang/SJVideoPlayer#327]
SJBaseVideoPlayer 中的accurateSeeking，没有传递给SJAVMediaPlaybackController中的accurateSeeking
导致SJAVMediaPlayer中accurateSeeking也是NO

在使用SJVideoPlayerURLAsset 中
- (nullable instancetype)initWithURL:(NSURL *)URL startPosition:(NSTimeInterval)startPosition
的初始化

        if ( self.needSeekToStartPosition && !self.seekingInfo.isSeeking && assetStatus == SJAssetStatusReadyToPlay ) {
            __weak typeof(self) _self = self;
            [self seekToTime:CMTimeMakeWithSeconds(self.startPosition, NSEC_PER_SEC) completionHandler:^(BOOL finished) {
                __strong typeof(_self) self = _self;
                if ( !self ) return;
                self.needSeekToStartPosition = NO;
                [self _toEvaluating];
            }];
            return;
        }
这个地方seek不准确

**Comment by changsanjiang** [comment]
已修改为精确跳转, 更新一下 SJBaseVideoPlayer(3.4.2) 吧
