### ISSUE TITLE
YYModel与主工程的YYKit冲突

### ISSUE THREAD

**Issue by YoungXKing** [changsanjiang/SJVideoPlayer#328]
**你的新功能建议是否牵扯到某个常见的问题？**
主项目用导入了YYKit,导入SJVideoPlayer时重复导入了YYModel

**你希望达到的效果**
希望规避冲突

**你能考虑到的可选实现方案**

**Comment by changsanjiang** [comment]
pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'

**Comment by YoungXKing** [comment]
> 试试这个
> 
> pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'

谢谢  解决啦！！
另外问一下，现在没有开放自动重播的接口是吧？如果想实现，目前的api哪种方法比较简单一点呢

**Comment by changsanjiang** [comment]
_player.playbackObserver.playbackDidFinishExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {
        [player replay];
    };

**Comment by YoungXKing** [comment]
> _player.playbackObserver.playbackDidFinishExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {
>     [player replay];
> };

嗯嗯 我现在就是这样弄的 谢谢大佬

**Comment by LS502311932** [comment]
pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
大佬 这个最近pod install 不成功 怎么解决

**Comment by PenguinAndy** [comment]
> pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
> 大佬 这个最近pod install 不成功 怎么解决

first :
# pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
pod 'SJUIKit', '~> 0.0.0.58'

**Comment by PenguinAndy** [comment]
> pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
> 大佬 这个最近pod install 不成功 怎么解决


first vim the Podfile:
`
# pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
pod 'SJUIKit', '~> 0.0.0.58'
`
& pod install

& then vim the Podfile:
`
pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
# pod 'SJUIKit', '~> 0.0.0.58'
`

**Comment by changsanjiang** [comment]
如果主项目引用了YYKit，`podfile`修改如下：
```ruby
 # YYKit
 pod 'SJUIKit/SQLite3', :git => 'https://gitee.com/changsanjiang/sjuikit2'
```

**Comment by changsanjiang** [comment]
> pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
> 大佬 这个最近pod install 不成功 怎么解决

按这个来： https://github.com/changsanjiang/SJVideoPlayer/issues/328#issuecomment-909779829

**Comment by adampei** [comment]
> pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYKit.podspec'
> 大佬 这个最近pod install 不成功 怎么解决

把demo中的这一行注释掉
> `#pod 'SJUIKit/PlaybackListController'`
