### ISSUE TITLE
Logo Design for SJVideoPlayer

### ISSUE THREAD

**Issue by anharismail** [changsanjiang/SJVideoPlayer#33]
Hi @changsanjiang , Here the edited logo for SJVideoPlayer. What types and sizes I should provide?

Hope you like it.

![sjvideoplayer ver 1](https://user-images.githubusercontent.com/37614260/43706674-3d01a8a0-9990-11e8-8290-8560d822bd83.png)

**Comment by changsanjiang** [comment]
Hi @anharismail , Thanks for your design.
I like the first design style. you can push it to this repository.  
In addition, i want a 1024pt app icon, can you send it to my email?

**Comment by anharismail** [comment]
Hi @changsanjiang , thanks for your kind response.

I've sent attachment files on your email. Please check it out.

Regards.

**Comment by changsanjiang** [comment]
Hi @anharismail , Can its background color be changed to white? 

![image](https://user-images.githubusercontent.com/25744224/52557510-9d0eae80-2e2a-11e9-8a14-4a2c14c37dda.png)
