### ISSUE TITLE
iOS10系统初始化播放器crash

### ISSUE THREAD

**Issue by kingstal** [changsanjiang/SJVideoPlayer#330]
**必现/偶发?**
必现

**描述bug**
iOS10系统初始化播放器crash

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
不再crash

**运行环境**
 - iPhone SE
 - iOS 10
 - Xcode 12.0
 - Objective-C

**截图**
![image](https://user-images.githubusercontent.com/5668852/92574670-f9150f80-f2b9-11ea-8391-574bd0cad009.png)

**Comment by changsanjiang** [comment]
@kingstal  感谢指出, 已修复
