### ISSUE TITLE
建议添加：试看结束之后的处理

### ISSUE THREAD

**Issue by purple-T** [changsanjiang/SJVideoPlayer#331]
**我的新功能建议**
在开发中，经常遇到试看结束处理的问题，比如爱奇艺或者优酷，需要购买vip或者付费。

**我希望达到的效果**
我希望框架能够帮助我解决试看结束之后的ui问题，实现像爱奇艺或者优酷那样的效果

**我能考虑到的可选实现方案**
我看了demo提供的SJLoadFailedControlLayer、SJNotReachableControlLayer。但是我没法拦截点击按钮之后的回调事件。所以想问一下，这种情况，试看之后的购买vip我需要怎么实现？

**Comment by taojeff** [comment]
@purple-T 你找到方法去做试看结束后的block回调了吗
