### ISSUE TITLE
There is any event triggered when vidoe finished ?

### ISSUE THREAD

**Issue by Najamus** [changsanjiang/SJVideoPlayer#338]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by changsanjiang** [comment]
It will be called after the playback is finish.

```Objective-C
    _player.playbackObserver.playbackDidFinishExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull player) {

    };
```
