### ISSUE TITLE
How play a AVAsset or it's subclass?

### ISSUE THREAD

**Issue by FengDeng** [changsanjiang/SJVideoPlayer#34]
Hello,
It's great.
But,How play a AVAsset or it's subclass??

**Comment by changsanjiang** [comment]
Can you create it using a URL?

**Comment by changsanjiang** [comment]
![231533695317_ pic_hd](https://user-images.githubusercontent.com/25744224/43812852-d1bae8a6-9af5-11e8-9350-0cbc0678b4de.jpg)

**Comment by FengDeng** [comment]
@changsanjiang I can't.It's AVComposition.

**Comment by changsanjiang** [comment]
OK, Wait a moment, I will add it.

**Comment by FengDeng** [comment]
<img width="701" alt="default" src="https://user-images.githubusercontent.com/9567443/43812925-28eb5048-9af6-11e8-88f8-8a91adef1aa5.png">

I public you SJPlayAsset,and imp it.But it's not work.
It's auto play,but control layer no response.

**Comment by FengDeng** [comment]
@changsanjiang thanks your great project.
Could you tell me how long will it be done.Could i use it afternoon?Sorry to have troubled you。

**Comment by changsanjiang** [comment]
Yes, you can use it in the afternoon, I am coding.

**Comment by changsanjiang** [comment]
Hi, @FengDeng 
I added some methods to SJVideoPlayerURLAsset, you can use it with `pod update`.
![image](https://user-images.githubusercontent.com/25744224/43815904-9c6b32be-9b04-11e8-88a0-26f58532f2d5.png)

**Comment by FengDeng** [comment]
Thanks,It's work!
