### ISSUE TITLE
UIScrollView 多个视频支持

### ISSUE THREAD

**Issue by shafujiu** [changsanjiang/SJVideoPlayer#341]
**你的新功能建议是否牵扯到某个常见的问题？**
有这样一种场景，我的当前控制器 就是一个简单的ScrollView，我的视频不多，可能就需要2-5个；这里就没有用到UITableView去承载我的视频了；我们又需要作者写好的UIScrollView 对于播放的一些控制，比如滑出页面暂停。

目前框架支持到的UIScrollView 的视频只有一个，多个的时候是没办法对应找到其位置的，除非用UITableView，但是有的场景并不是很适合将视频放与UITableView上。

**你希望达到的效果**

UIScrollView上面可以有多个视频的支持

**你能考虑到的可选实现方案**

希望能够为SJScrollViewPlayModel类 增加tag的方式，去承载多个视频、比如：

```
- (instancetype)initWithScrollView:(UIScrollView *__weak)scrollView containerTag:(NSInteger)containerTag {
    self = [super init];
    if ( self ) {
        _scrollView = scrollView;
        _containerTag = containerTag;
        _hasTag = YES;
    }
    return self;
}
```

稍后 可能会给您 pull request

**Comment by changsanjiang** [comment]
ok

**Comment by shafujiu** [comment]
@changsanjiang 已经提交啦，交给你去审查了哦

**Comment by changsanjiang** [comment]
Thanks @shafujiu , 这块代码稍微调整了一下, 已经发到最新的版本上了(SJBaseVideoPlayer 3.4.1), 使用如下: 

```Objective-C
    SJPlayModel *model = [SJPlayModel playModelWithScrollView:scrollView];
    model.superviewTag = superviewTag;
```
