### ISSUE TITLE
av后台播放设置和画中画功能冲突

### ISSUE THREAD

**Issue by trial** [changsanjiang/SJVideoPlayer#343]
**必现/偶发?**
必现

**描述bug**
如果使用avplayer，设置player.pauseWhenAppDidEnterBackground = false，则第二次进入画中画会没有画面，一直转圈

**Demo中是否存在同样的问题?**
Demo中player.pauseWhenAppDidEnterBackground是true

**运行环境**
 - iPhone Xs max
 - iOS 14
 - Xcode 12
 - Swift

**Comment by changsanjiang** [comment]
@trial 感谢指出,  已修复(SJBaseVideoPlayer 3.4.1)
