### ISSUE TITLE
拖动手势关闭不起作用

### ISSUE THREAD

**Issue by CallLiven** [changsanjiang/SJVideoPlayer#348]
**必现/偶发?**
必现

**描述bug**
player.gestureRecognizerShouldTrigger 返回值是NO，单击和双击能屏蔽，但是拖动手势不行

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone 7Plus
 - iOS 14
 - Xcode 12.0
 - Objective-Ct

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
你好, 我这边在demo中测试是正常的, 可以给我一份有这个问题的demo吗
