### ISSUE TITLE
pod install报错，使用pod update 仍然报错

### ISSUE THREAD

**Issue by BleachCC** [changsanjiang/SJVideoPlayer#35]
[!] Error installing SJBaseVideoPlayer
[!] /usr/bin/git clone https://github.com/changsanjiang/SJBaseVideoPlayer.git /var/folders/h3/wkw1c8wd4jn2ytqwb_rptg5h0000gn/T/d20180808-2907-1r9ge0v --template= --single-branch --depth 1 --branch v1.3.2

Cloning into '/var/folders/h3/wkw1c8wd4jn2ytqwb_rptg5h0000gn/T/d20180808-2907-1r9ge0v'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by changsanjiang** [comment]
这个被是墙了, 我把源切换到OSChina上吧, 稍等一下.

**Comment by BleachCC** [comment]
回复好快啊👍

**Comment by changsanjiang** [comment]
也可以多试几次, 你先试着, 我去切换源.

**Comment by Loveying** [comment]
[!] Error installing SJVideoPlayerAssetCarrier
[!] /usr/bin/git clone https://github.com/changsanjiang/SJVideoPlayerAssetCarrier.git /var/folders/mc/8_b7799s30q5l33wtmw8gfch0000gn/T/d20180808-12820-1lvnbxx --template= --single-branch --depth 1 --branch v1.1.6

Cloning into '/var/folders/mc/8_b7799s30q5l33wtmw8gfch0000gn/T/d20180808-12820-1lvnbxx'...
remote: Repository not found.
fatal: repository 'https://github.com/changsanjiang/SJVideoPlayerAssetCarrier.git/' not found

**Comment by changsanjiang** [comment]
@Loveying 用 `pod update`吧

**Comment by changsanjiang** [comment]
@BleachCC 我把源切换到OSChina上了. 用`pod update`试一下看看

**Comment by BleachCC** [comment]
可以了👍

**Comment by Loveying** [comment]
感觉里面东西挺多的 这个应该是从项目抽出来的视频播放器吧! 底层是基于系统的AVPlayer 封装的吧? 
Masonry 也是SJVideoPlayer 默认的依赖安装吗?

**Comment by changsanjiang** [comment]
恩, 功能类抽了不少

**Comment by Loveying** [comment]
pod 安装之后 编译报错了
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Products/Debug-iphonesimulator/SJVideoPlayer/libSJVideoPlayer.a(SJVideoPlayerTopControlView.o)
duplicate symbol _OBJC_IVAR_$_SJVideoPlayerControlSettingRecorder._settings in:
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Intermediates.noindex/SJVideoPlayerDemo.build/Debug-iphonesimulator/SJVideoPlayerDemo.build/Objects-normal/x86_64/UIView+SJVideoPlayerSetting.o
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Products/Debug-iphonesimulator/SJVideoPlayer/libSJVideoPlayer.a(UIView+SJVideoPlayerSetting.o)
duplicate symbol _OBJC_CLASS_$_SJVideoPlayerControlSettingRecorder in:
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Intermediates.noindex/SJVideoPlayerDemo.build/Debug-iphonesimulator/SJVideoPlayerDemo.build/Objects-normal/x86_64/UIView+SJVideoPlayerSetting.o
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Products/Debug-iphonesimulator/SJVideoPlayer/libSJVideoPlayer.a(UIView+SJVideoPlayerSetting.o)
duplicate symbol _OBJC_METACLASS_$_SJVideoPlayerControlSettingRecorder in:
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Intermediates.noindex/SJVideoPlayerDemo.build/Debug-iphonesimulator/SJVideoPlayerDemo.build/Objects-normal/x86_64/UIView+SJVideoPlayerSetting.o
    /Users/xyy/Library/Developer/Xcode/DerivedData/SJVideoPlayerDemo-gundybsfrwtveffmirqnfuioqhsw/Build/Products/Debug-iphonesimulator/SJVideoPlayer/libSJVideoPlayer.a(UIView+SJVideoPlayerSetting.o)
ld: 522 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by changsanjiang** [comment]
可以发我这个DEMO吗, 我看看什么问题

**Comment by changsanjiang** [comment]
或者搜一下重复文件, 把不在pod里面的删掉. `UIView+SJVideoPlayerSetting` & `SJVideoPlayerTopControlView`

**Comment by Loveying** [comment]
之前文件直接移入进去的 和 pods 冲突 了 没问题的
