### ISSUE TITLE
播放地址按照之前的Issues配置请求头，使用第三方播放器时播放不了。

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#352]
参考之前的issues配置请求头，使用系统播放器时可以播放，使用第三方播放器时播放不了。
        //ijk播放器
        self.sjplayer.playbackController = SJIJKMediaPlaybackController()
        let avasset = AVURLAsset(url: URL(string: bofangdizhi)!, options: ["AVURLAssetHTTPHeaderFieldsKey": headers])
        self.sjplayer.urlAsset = SJVideoPlayerURLAsset.init(avAsset: avasset)
使用AVURLAsset初始化播放地址的时候即使不设置options第三方播放器也播放不了，不知道是不是我哪里配置错了。

**Comment by slash130** [comment]
在网上查了一下，ijk的请求头有单独的配置方式
        //ijk播放器
        let options:IJKFFOptions = IJKFFOptions.byDefault()
        options.setOptionValue("key:value\r\n", forKey: "headers", of: kIJKFFOptionCategoryFormat)
        let playbackcontroller = SJIJKMediaPlaybackController()
        playbackcontroller.options = options
        
        self.sjplayer.playbackController = playbackcontroller
        self.sjplayer.urlAsset = SJVideoPlayerURLAsset.init(url: URL(string: bofangdizhi)!)

**Comment by trial** [comment]
aliplayer应该怎么设置
