### ISSUE TITLE
您好，我把SJVideoPlayer 放在自定义的cell上，向上滑动这个cell是，tableView无法响应如何解决？

### ISSUE THREAD

**Issue by SuiFengLiuNian** [changsanjiang/SJVideoPlayer#353]
您好，我把SJVideoPlayer 放在自定义的cell上，手势放在这个cell向上滑动时，tableView无法响应向上滑动如何解决？

**Comment by SuiFengLiuNian** [comment]
因为我希望点击手势存在，但是不能影响向上滑动的手势

**Comment by changsanjiang** [comment]
@SuiFengLiuNian  更新一下版本吧, 之前修复过这个问题

**Comment by SuiFengLiuNian** [comment]
我的pod.lock 文件中的版本，这个版本对吗？是哪个版本大神

**Comment by changsanjiang** [comment]
最新的是3.2.7,  你在demo试试, 看看有这个问题没
