### ISSUE TITLE
怎么能让控制层一直显示停留

### ISSUE THREAD

**Issue by LS502311932** [changsanjiang/SJVideoPlayer#355]
你好，怎么能让控制层（defaultEdgeControlLayer）
![截屏2020-10-30 下午3 11 09](https://user-images.githubusercontent.com/19722504/97670918-3760cb00-1ac2-11eb-9ecf-643aea3898cb.png)
一直显示 常驻显示

**Comment by changsanjiang** [comment]
需 SJBaseVideoPlayer 3.4.6 以上
```Objective-C
    [_player.controlLayerAppearManager keepAppearState];
    _player.controlLayerAppearManager.disabled = YES;
```
