### ISSUE TITLE
xcode12.2,ios13.6,在swift中使用时，除了第一个cell的横屏可以返回，其他的都不能返回

### ISSUE THREAD

**Issue by huoda1237** [changsanjiang/SJVideoPlayer#363]
**运行环境**
 - iPhone X
 - iOS 13.6
 - Xcode 12.2.
 -Swift
问题：除了第一个cell的横屏可以返回，其他的都不能返回（必现）

**Comment by changsanjiang** [comment]
按[这个指南](https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B) 配置一下
