### ISSUE TITLE
修改视频未铺及区域为透明

### ISSUE THREAD

**Issue by Marcusias** [changsanjiang/SJVideoPlayer#365]
请问使用ijkplayer时 如何修改 标记区域的背景色为clear呢？尝试了很多方式没有实现
或者增加背景为首帧的高斯模糊图
<img width="448" alt="WX20201126-185652@2x" src="https://user-images.githubusercontent.com/13980779/100343292-21d7b600-301a-11eb-88e5-3d5d83dccec1.png">
<img width="627" alt="WX20201126-185914@2x" src="https://user-images.githubusercontent.com/13980779/100343299-243a1000-301a-11eb-97e1-98e76b98ee4a.png">

**Comment by changsanjiang** [comment]
背景默认黑色, 修改clearColor就行
```Objective-C
    _player.view.backgroundColor = UIColor.clearColor;
    _player.presentView.backgroundColor = UIColor.clearColor;
```
