### ISSUE TITLE
DY Demo跳转指定视频播放问题

### ISSUE THREAD

**Issue by jozdee** [changsanjiang/SJVideoPlayer#366]
NSIndexPath *selectedIndexPath = [NSIndexPath indexPathForRow:5 inSection:0];
通过设置 setSj_currentPlayingIndexPath：selectedIndexPath 不能指定直接播放，如第五个
试了以下方法也不行：
[self.tableView scrollToRowAtIndexPath:selectedIndexPath atScrollPosition:UITableViewScrollPositionMiddle animated:NO];//cell滚动到选中指定cell位置
 [self.tableView setContentOffset:CGPointMake(0, self.tableView.mj_h*self.index) animated:YES];
期待大佬给个方案呀

**Comment by changsanjiang** [comment]
@jozdee 暂时没这个接口, 晚上我改一下, 明天了再更一下吧

**Comment by jozdee** [comment]
> @jozdee暂时没这个接口，晚上我改一下，明天了再更一下吧

谢谢大佬

**Comment by jozdee** [comment]
没看到开放接口呀？

**Comment by jozdee** [comment]
> @jozdee暂时没这个接口，晚上我改一下，明天了再更一下吧

下载看了下，还是没有相关接口呀，辛苦抽空开放下接口呢
