### ISSUE TITLE
全屏播放时弹出admob激励视频广告  返回播放器 闪退

### ISSUE THREAD

**Issue by nicknull** [changsanjiang/SJVideoPlayer#367]
**必现/偶发?**
必现

**描述bug**
全屏播放时弹出admob激励视频广告  返回播放器 闪退

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
不闪退
**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图
<img width="1146" alt="WeChatc5ed960c54089bca08c76000c72c693b" src="https://user-images.githubusercontent.com/5275571/100704485-90cd5a00-33e0-11eb-83c4-1ac2e5e39815.png">

**Comment by changsanjiang** [comment]
@nicknull  来个demo吧

**Comment by nicknull** [comment]
[Quick.zip](https://github.com/changsanjiang/SJVideoPlayer/files/5620919/Quick.zip)

**Comment by changsanjiang** [comment]
@nicknull 先修改一下吧:  

```Objective-C

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    switch ( _currentOrientation ) {
        case UIDeviceOrientationPortraitUpsideDown:
            return UIInterfaceOrientationPortraitUpsideDown;
        case UIDeviceOrientationLandscapeLeft:
            return UIInterfaceOrientationLandscapeRight;
        case UIDeviceOrientationLandscapeRight:
            return UIInterfaceOrientationLandscapeLeft;
        default:
            return UIInterfaceOrientationPortrait;
    }
}
```

**Comment by changsanjiang** [comment]
貌似直接删除这个方法也不奔...

**Comment by nicknull** [comment]
好的 谢谢
