### ISSUE TITLE
Example 运行不了

### ISSUE THREAD

**Issue by boyXiong** [changsanjiang/SJVideoPlayer#373]
提示 有API 没有了 _player.floatSmallViewController.layoutPosition = SJFloatViewLayoutPositionBottomRight;

注销后，还是不可以, pod 更新 提示

pod update --no-repo-update
Update all pods
Analyzing dependencies
[!] No podspec found for `SJVideoPlayer` in `../../SJVideoPlayer`

**Comment by changsanjiang** [comment]
@boyXiong  已修
