### ISSUE TITLE
视频播放器退入后台，过一会在进入前台，会有黑色的效果，在显示视频预览，这个是怎么回事，可以去掉吗

### ISSUE THREAD

**Issue by jozdee** [changsanjiang/SJVideoPlayer#374]
对占位图进行操作隐藏，也没用，希望直接展示视频预览，不要黑色那个过渡效果

**Comment by changsanjiang** [comment]
好的, 我晚上看看

**Comment by jozdee** [comment]
> 好的，我晚上看看

我看demo挂入后台后，操作一些其他APP啥的，播放状态，从后台进去前台的时候，也会有黑色渐隐的效果存在

**Comment by changsanjiang** [comment]
更新到最新版本 (SJBaseVideoPlayer 3.5.2) 再试试
