### ISSUE TITLE
在pod 的情况下，怎么去更改 控制层的 UI视图啊，另外，控制层没有方法可以永久隐藏吗

### ISSUE THREAD

**Issue by boyXiong** [changsanjiang/SJVideoPlayer#378]
因为要自定义  控制层的UI， 谢谢
库很优秀

**Comment by changsanjiang** [comment]
操作控制层参考这个: 
 https://github.com/changsanjiang/SJVideoPlayer/wiki/%E6%8E%A7%E5%88%B6%E5%B1%82%E4%B8%8A%E7%9A%84%E6%8C%89%E9%92%AE%E5%A6%82%E4%BD%95-%E6%B7%BB%E5%8A%A0-%E5%88%A0%E9%99%A4-%E4%BF%AE%E6%94%B9%3F
