### ISSUE TITLE
iOS 14 锁屏/进入后台 20s以上,视频黑屏,无法继续播放

### ISSUE THREAD

**Issue by CoderQifly** [changsanjiang/SJVideoPlayer#379]
**必现/偶发?**
必现
**描述bug**
iOS 14 锁屏/进入后台 20s以上,视频黑屏,无法继续播放

**Comment by changsanjiang** [comment]
@CoderQifly Code 在demo试一下, 如果存在问题给个测试链接

**Comment by LongJiangSB** [comment]
> **必现/偶发?**
> 必现
> **描述bug**
> iOS 14 锁屏/进入后台 20s以上,视频黑屏,无法继续播放

请问你解决了吗？我也遇见了相同的问题

**Comment by CoderQifly** [comment]
> > **必现/偶发?**
> > 必现
> > **描述bug**
> > iOS 14 锁屏/进入后台 20s以上,视频黑屏,无法继续播放
> 
> 请问你解决了吗？我也遇见了相同的问题
> 视图会进入失败 稍后重试的状态，点击重试按钮，马上会输出以下log，并且页面会进入 失败，稍后重试
> ![image](https://user-images.githubusercontent.com/9586684/104005893-ba984e80-51e0-11eb-9abd-804286280804.png)

我自己处理的,监听解锁和回到前台的通知,然后重新加载视频

**Comment by LongJiangSB** [comment]
@CoderQifly co 感谢你的回复，我也是因为我使用吐流库未做监听，我在对应状态里面重新初始化库解决了
