### ISSUE TITLE
视频详情页面画面卡顿但是有声音

### ISSUE THREAD

**Issue by LiYuLong012** [changsanjiang/SJVideoPlayer#38]
当我在列表页面，播放一段时间，或者快进一段时间的时候，进入详情页面，它会接着上一个时间段播放，这时候有一个问题，画面卡顿，音频在走，是不是应该有一个菊花，等缓冲那个点再播放。

**Comment by changsanjiang** [comment]
Hi @LiYuLong012  
这几个方法调用了吗？
![image](https://user-images.githubusercontent.com/25744224/46120316-b3ccb400-c241-11e8-9c29-8fceb97866d4.png)
