### ISSUE TITLE
有没有播放视图不可见回调

### ISSUE THREAD

**Issue by dingyongg** [changsanjiang/SJVideoPlayer#387]
有没有播放视图不可见回调， 被覆盖或划出屏幕， 目前播放视图被覆盖或划出屏幕还在继续播放， 需求是要在视图播放不可见的时候停止播放，可见的时候回复播放

**Comment by changsanjiang** [comment]
https://github.com/changsanjiang/SJVideoPlayer/wiki/UITableView%E5%8F%8AUICollectionView%E4%B8%AD%E6%92%AD%E6%94%BE%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88v2
