### ISSUE TITLE
播放本地avi视频如何设置？

### ISSUE THREAD

**Issue by zp0605** [changsanjiang/SJVideoPlayer#389]
播放本地视频代码：
`        
NSString *cachesPath = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES)lastObject];
        NSString *path = [NSString stringWithFormat:@"%@/vedio/2020-12-28_18_12_06.avi",  cachesPath];
        NSURL * URL = [NSURL URLWithString:path];
        player.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithURL:URL];
        [player play];
`

一开始播放就提示：The server is not correctly configured
具体错误打印：
 SJAVMediaPlayer: Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x2802e46f0 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}

**Comment by changsanjiang** [comment]
+ (NSURL *)fileURLWithPath:(NSString *)path;
