### ISSUE TITLE
利用scrollView实现滚动切换效果时，多个界面会存在同时播放的情况。

### ISSUE THREAD

**Issue by liuchunlao** [changsanjiang/SJVideoPlayer#39]
利用scrollView实现滚动切换效果，而非pageViewController，控制视图声明周期方法不会执行，所以就会有多个界面在播放视频。
解决办法：
在确定切换了界面时，发出通知，收到通知后将播放器stopAndFadeout即可。
根据页码索引的改变确实界面是否切换。

给遇到同样问题的朋友，提供个思路。

感谢作者牛逼的框架！

**Comment by changsanjiang** [comment]
确实没考虑到这个问题，Thanks  @liuchunlao 。

**Comment by loveuqian** [comment]
我用的那个分屏框架，分屏滑动时能正确触发那几个 appear 方法

**Comment by liuchunlao** [comment]
> 我用的那个分屏框架，分屏滑动时能正确触发那几个 appear 方法

什么框架呢？求推荐

**Comment by loveuqian** [comment]
WMPage


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 刘春牢 <notifications@github.com>
发送时间: 2019年4月15日 17:09
收件人: changsanjiang/SJVideoPlayer <SJVideoPlayer@noreply.github.com>
抄送: 王胜峰 <loveuqian@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[changsanjiang/SJVideoPlayer] 利用scrollView实现滚动切换效果时，多个界面会存在同时播放的情况。 (#39)

**Comment by liuchunlao** [comment]
好，谢谢啦
