### ISSUE TITLE
APP退到后台，再进入前台后，视频播放时只有声音，画面不动了。

### ISSUE THREAD

**Issue by nol876** [changsanjiang/SJVideoPlayer#395]
demo里边DY和旋转控制1没问题，旋转控制2和uiscrollview tableview 都会出现这个问题。

**Comment by changsanjiang** [comment]
ok, 正在修复

**Comment by changsanjiang** [comment]
@nol876  感谢反馈.   bug 已经修复, 半小时后更新一下吧,  SJBaseVideoPlayer(3.5.1)
