### ISSUE TITLE
横竖屏切换后输入法的高度获取不准

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#396]
我的控制器需要在播放器控制层加入一个按钮，点击后弹出输入法和一个自定义view。我直接在默认边缘控制层添加了一个item，然后点击触发弹出输入法和view。在进入控制器页面后竖屏状态下点击按钮获取弹出输入法的高度没问题，手机横置画面切换到横屏后再点击按钮弹出输入法，这时获取到的输入法高度不正确，我测试的手机是XR，竖屏输入法的y值是529，横屏后获取到的是606。如果进入控制器页面不触发弹出输入法先横屏播放视频点击按钮弹出输入法获取到的y值是178，这时显示是正常的，切换回竖屏后再弹出输入法获取的y值又不对了。
谁知道这问题怎么解决，这问题造成自定义view距离输入法的上边只有一个方向是准的。

**Comment by changsanjiang** [comment]
Demo里参考一下 1 TextField 试试

**Comment by slash130** [comment]
@changsanjiang 大神，最新的代码git下载后直接编译运行有个报错
SJUIKitAttributesDefines.h的第166行，报的 Unknown type name 'NSLineBreakStrategy'

**Comment by changsanjiang** [comment]
Xcode版本需要12以上了

**Comment by changsanjiang** [comment]
把报错的统统注视调试试

**Comment by slash130** [comment]
我运行了一下老版本的git代码，TextField的示例竖屏点击发送评论的item弹出键盘和带发送按钮的输入框正常，但是横屏后再点item弹出的只有输入法没有带发送的视图了。

**Comment by slash130** [comment]
我注释掉了有问题的代码，最新版的demo弹出带发送的视图没问题，我参考一下。
