### ISSUE TITLE
横屏进入后台在回到前台，退出横屏navbar和tabbar位置错乱

### ISSUE THREAD

**Issue by bandy101** [changsanjiang/SJVideoPlayer#397]
**必现/偶发?**
必现

**描述bug**
项目有tabbar+navbar，当横屏播放是按home进入后台后，再打开，返回半屏，navbar和tabbar位置错乱

**Demo中是否存在同样的问题?**
否
![image](https://user-images.githubusercontent.com/1021201/104004560-d00c7900-51de-11eb-8bcb-051d29fdab50.png)

![image](https://user-images.githubusercontent.com/1021201/104004590-dbf83b00-51de-11eb-9614-6d23d69470d5.png)

https://user-images.githubusercontent.com/1021201/104004506-c420b700-51de-11eb-87e3-ebbe25326bca.MP4

**Comment by changsanjiang** [comment]
@bandy101  demo发出来看看

**Comment by changsanjiang** [comment]
配置3和配置4 有添加吗?
https://github.com/changsanjiang/SJVideoPlayer/wiki/%E7%82%B9%E5%87%BB%E6%97%8B%E8%BD%AC%E5%8D%A1%E6%AD%BB%E6%88%96%E8%80%85%E6%97%8B%E8%BD%AC%E5%87%BA%E7%8E%B0%E5%BC%82%E5%B8%B8%3F

**Comment by bandy101** [comment]
感谢回复，附件是demo
[demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/5786673/demo.zip)

**Comment by bandy101** [comment]
[demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/5786689/demo.zip)
感谢回复，这是demo

**Comment by changsanjiang** [comment]
@bandy101  分类没写全,   需要加上以下代码: 

```Objective-C
@implementation UIViewController (RotationControl)
- (BOOL)shouldAutorotate { 
    return NO;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}

@end
```

**Comment by bandy101** [comment]
[demo2.zip](https://github.com/changsanjiang/SJVideoPlayer/files/5786751/demo2.zip)
重新加了这个分类，请查阅，好像还是一样。
iPhone 8  ios 13.5.1

**Comment by changsanjiang** [comment]
UIViewController+SJRotationPrivate_FixSafeArea.h 第 10, 38 行注释掉
UIViewController+SJRotationPrivate_FixSafeArea.m 第 8, 83 行注释掉

**Comment by changsanjiang** [comment]
@bandy101  最好用pod管理, 拉最新的代码.

**Comment by bandy101** [comment]
好的，感谢，手动点赞👍
