### ISSUE TITLE
可以加一个是否需要拦截功能吗？部分地方不需要进度视图

### ISSUE THREAD

**Issue by zhouzhou94alone** [changsanjiang/SJVideoPlayer#398]
![截屏2021-01-11 上午10 13 41](https://user-images.githubusercontent.com/17922986/104142405-6d8dc580-53f6-11eb-8e09-521c9726f1f5.png)

**Comment by changsanjiang** [comment]
控制层都在 SJVideoPlayer.player 中, 不需要控制层的话就用 SJBaseVideoPlayer.player 初始化播放器.
