### ISSUE TITLE
是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频

### ISSUE THREAD

**Issue by Liyongcong** [changsanjiang/SJVideoPlayer#399]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，在开发中，经常遇到XXX问题，目前框架的功能不足以解决这个问题

**你希望达到的效果**
比如，我希望框架能够帮助我解决XXX问题，实现XXXX那样的效果

**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？

**Comment by changsanjiang** [comment]
是AES加密的吗?

**Comment by Liyongcong** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 中午1:07
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
是AES加密的吗?

**Comment by changsanjiang** [comment]
AVPlayer 本身就支持的.

如果你想要边下边播, 可以配合这个库使用:  https://github.com/changsanjiang/SJMediaCacheServer

**Comment by Liyongcong** [comment]
不是边下边播，是可以直接下载到本地后，找到本地的路径，在没有网的情况下也可以播放



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 中午1:13
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
AVPlayer 本身就支持的.
 
如果你想要边下边播, 可以配合这个库使用:  https://github.com/changsanjiang/SJMediaCacheServer

**Comment by changsanjiang** [comment]
本地m3u8一般是开个本地代理去播放的. 试试用这个库下载和播放吧 https://github.com/changsanjiang/SJM3U8Downloader

**Comment by Liyongcong** [comment]
好的，我试试，多谢，Github已关注



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 下午2:27
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
本地m3u8一般是开个本地代理去播放的. 试试用这个库下载和播放吧 https://github.com/changsanjiang/SJM3U8Downloader

**Comment by Liyongcong** [comment]
用你刚发这个点击下载直接闪退http://new.storage.public.uy123.net/course/lnTvER-nR2uogYRy7R13lRKHrKFd.m3u8



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 下午2:27
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
本地m3u8一般是开个本地代理去播放的. 试试用这个库下载和播放吧 https://github.com/changsanjiang/SJM3U8Downloader

**Comment by changsanjiang** [comment]
已修 [SJM3U8Downloader 0.0.5](https://github.com/changsanjiang/SJM3U8Downloader/releases/tag/0.0.5)

**Comment by Liyongcong** [comment]
好的，我再试试，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月16日(星期六) 上午10:10
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
已修 SJM3U8Downloader 0.0.5

**Comment by Liyongcong** [comment]
你好，如果我想存储一些视频相关的信息，比如图片，视频URL，ID，视频title和视频subTitle，然后在另一个下载界面的控制器显示，该在哪个地方去扩展你的三方呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月16日(星期六) 上午10:10
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
已修 SJM3U8Downloader 0.0.5

**Comment by changsanjiang** [comment]
1. 可以临时扩展如下: 
```Objective-C
#import "SJM3U8DownloadListItem.h"
#import <objc/message.h>

///
/// 添加自定义字段
///
@interface SJM3U8DownloadListItem (TestExtended)
@property (nonatomic, copy, nullable) NSString *name;
@property (nonatomic, copy, nullable) NSString *title;
@end

@implementation SJM3U8DownloadListItem (TestExtended)
- (void)setName:(NSString *)name {
    objc_setAssociatedObject(self, @selector(name), name, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (NSString *)name {
    return objc_getAssociatedObject(self, _cmd);
}

- (void)setTitle:(NSString *)title {
    objc_setAssociatedObject(self, @selector(title), title, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

- (NSString *)title {
    return objc_getAssociatedObject(self, _cmd);

}
@end
```

2. 添加下载时, 设置值
```Objective-C
    NSString *url = nil;
    NSInteger idx = [SJM3U8DownloadListController.shared addItemWithUrl:url];
    SJM3U8DownloadListItem *item = (id)[SJM3U8DownloadListController.shared itemAtIndex:idx];
    item.delegate = self;
    item.name = @"asdfds";
    // ..
    // ..
    item.title = @"adsafsd";
    [SJM3U8DownloadListController.shared updateContentsForItemAtIndex:idx];
```

3. 视频下载完成后, 这条数据就会从`SJM3U8DownloadListController`中删除,  需要在代理方法中保存到自己的数据库中
```Objective-C
- (void)downloadItemStateDidChange:(SJM3U8DownloadListItem *)item {
    if ( item.state == SJDownloadStateFinished ) { 
          // .. 保存到自己的数据库中
    }
}
```

**Comment by Liyongcong** [comment]
好的，明白了，还有一个问题，就是下载进度先后的问题，比如我在你这个列表下载了有进度比如10%，我想在另一个下载控制器页面也显示10%并且在下载控制器页面也实时更新这个下载进度，用你那个progress可以么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月16日(星期六) 下午3:12
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





  
可以临时扩展如下:
  #import "SJM3U8DownloadListItem.h" #import <objc/message.h&gt; /// /// 添加自定义字段 /// @interface SJM3U8DownloadListItem (TestExtended) @property (nonatomic, copy, nullable) NSString *name; @property (nonatomic, copy, nullable) NSString *title; @end @implementation SJM3U8DownloadListItem (TestExtended) - (void)setName:(NSString *)name {     objc_setAssociatedObject(self, @selector(name), name, OBJC_ASSOCIATION_RETAIN_NONATOMIC); } - (NSString *)name {     return objc_getAssociatedObject(self, _cmd); } - (void)setTitle:(NSString *)title {     objc_setAssociatedObject(self, @selector(title), title, OBJC_ASSOCIATION_RETAIN_NONATOMIC); } - (NSString *)title {     return objc_getAssociatedObject(self, _cmd); } @end
  
添加下载时, 设置值
      NSString *url = nil;     NSInteger idx = [SJM3U8DownloadListController.shared addItemWithUrl:url];     SJM3U8DownloadListItem *item = (id)[SJM3U8DownloadListController.shared itemAtIndex:idx];     item.delegate = self;     item.name = @"asdfds";     // ..     // ..     item.title = @"adsafsd";     [SJM3U8DownloadListController.shared updateContentsForItemAtIndex:idx];
  
视频下载完成后, 这条数据就会从SJM3U8DownloadListController中删除,  需要在代理方法中保存到自己的数据库中
  - (void)downloadItemStateDidChange:(SJM3U8DownloadListItem *)item {     if ( item.state == SJDownloadStateFinished ) {            // .. 保存到自己的数据库中     } }

**Comment by changsanjiang** [comment]
可以

**Comment by Liyongcong** [comment]
我在那个地方可以打印出来你下载的ts片段存储的路径，以及整合ts片段然后通过本地服务器去播放，我想看看这学习下这个东西



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "changsanjiang"<notifications@github.com&gt;; 
发送时间: 2021年1月16日(星期六) 下午3:53
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com&gt;; 
抄送: "有bug的程序猿"<570703516@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [changsanjiang/SJVideoPlayer] 是否可以支持m3u8加密和不加密视频下载，以及下载后播放本地的m3u8视频 (#399)





 
可以
