### ISSUE TITLE
新界面继续播放，进度条在走，但是视频画面是卡住不动的

### ISSUE THREAD

**Issue by steven326** [changsanjiang/SJVideoPlayer#40]
_player.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithOtherAsset:_asset playModel:[SJPlayModel new]];

今天在使用过程中遇到了一个问题，新界面继续播放Demo，点击next进入下一个VC，进度条在走，但是视频是卡住不动的。劳烦作者有空看下？

另外为作者开源精神点赞。

**Comment by changsanjiang** [comment]
Thanks @steven326 ,  已定位到问题, 是控制层切换器少加了一个判断.  已修复.

**Comment by steven326** [comment]
我这重新下载了Demo，但是还是会有问题。可能之前没描述清楚。

新界面继续播放Demo，A_VC点击播放后，点击“next”进入B_VC，B_VC视频画面播放大概1s后画面停止，进度条还在走。

**Comment by steven326** [comment]
> Thanks @steven326 , 已定位到问题, 是控制层切换器少加了一个判断. 已修复.
> 
> [SJVideoPlayer/SJVideoPlayer/Switcher/SJControlLayerSwitcher.m](https://github.com/changsanjiang/SJVideoPlayer/blob/19b0bf636ea146139eaa041a608e61d699658f35/SJVideoPlayer/Switcher/SJControlLayerSwitcher.m#L57)
> Line 57 in [19b0bf6](/changsanjiang/SJVideoPlayer/commit/19b0bf636ea146139eaa041a608e61d699658f35)
>  if ( old && (old.identifier == self.currentIdentifier) ) {

我这重新下载了Demo，但是还是会有问题。可能之前没描述清楚。

新界面继续播放Demo，A_VC点击播放后，点击“next”进入B_VC，B_VC视频画面播放大概1s后画面停止，进度条还在走。

**Comment by flyuqian** [comment]
问题依然存在啊

**Comment by changsanjiang** [comment]
@flyuqian 是最新版的吗?

**Comment by flyuqian** [comment]
我刚才在手机上试了一下, 在手机上没问题, 在模拟器上有问题.   那这应该就没有问题了 @changsanjiang , 如果您还想看这个问题, 您可以在模拟器上跑下您的demo. 还有是最新版本
