### ISSUE TITLE
打开直播视频m3u8格式时, 播放器的时间和进度条都不显示了. 也无法针对性的修改.

### ISSUE THREAD

**Issue by MQL9011** [changsanjiang/SJVideoPlayer#406]
[SJPlay.zip](https://github.com/changsanjiang/SJVideoPlayer/files/5864016/SJPlay.zip)

这个压缩包中是demo, 直播的测试地址有效期12小时, 您可以更换成其他直播地址测试一下.

**Comment by changsanjiang** [comment]
@MQL9011  😁，还到这里提了, 现在应该没问题了吧

**Comment by MQL9011** [comment]
感谢作者提供的帮助

**Comment by ashen-zhao** [comment]
请问下，这个不显示进度条和时间的问题，怎么解决的呢

**Comment by sauchye** [comment]
@changsanjiang 作者你好，我用tableView header 播放mp4 视频，也出现不显示进度条，暂停⏸按钮。播放完之后重播不起作用，作者可以看看嘛，Demo中 tableView header 播放mp4 视频是没问题😭
