### ISSUE TITLE
https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b   这个地址不能播放

### ISSUE THREAD

**Issue by xmhongyue** [changsanjiang/SJVideoPlayer#414]
**必现/偶发?**
必现

**描述bug**
播放器无法播放这个地址：https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b
我猜想是不是缺少header？

**Demo中是否存在同样的问题?**
是/否
是，我下载了官方demo跑，也是播放不了
**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone11
 - iOS 13.6
 - Xcode 12.3
 - Objective-C

**截图**
如果有必要的话，请上传几张截图
![WechatIMG434](https://user-images.githubusercontent.com/77982775/108621659-f58fd200-746e-11eb-9501-851b2f291984.png)

**额外的**
最好能提供出现bug的Demo

**Comment by xmhongyue** [comment]
iPhone Safair浏览器是可以播放的

**Comment by 290138645** [comment]
> iPhone Safair浏览器是可以播放的

解决了吗？

**Comment by changsanjiang** [comment]
这个url指向一个网页， 请用视频url播放

https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8

**Comment by stoneUoU** [comment]
> 这个url指向一个网页， 请用视频url播放
> 
> https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8



> 这个url指向一个网页， 请用视频url播放
> 
> https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8

大佬，这个地址你是怎么由https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b 转过来的呢？

**Comment by stoneUoU** [comment]
> 这个url指向一个网页， 请用视频url播放
> 
> https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8

大佬，这个地址你是怎么由https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b 转过来的呢？

**Comment by xmhongyue** [comment]
> > iPhone Safair浏览器是可以播放的
> 
> 解决了吗？
大佬给我提示了，但我还没明白https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8
您是怎么通过https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b转过来的
F12也看不到具体地址
是有视频地址解析吗？

**Comment by xmhongyue** [comment]
> > iPhone Safair浏览器是可以播放的
> 
> 解决了吗？

大佬给我提示了，但我还没明白https://qingxi.xi-zuida.com/20210212/1108_81a53028/1000k/hls/index.m3u8
您是怎么通过https://qingxi.xi-zuida.com/share/b9d487a30398d42ecff55c228ed5652b转过来的
F12也看不到具体地址
是有视频地址解析吗？
