### ISSUE TITLE
demo 上cell 里面SJPlayerSuperImageView添加的手势不被触发无法实现代理回调预加载

### ISSUE THREAD

**Issue by yuhangjob** [changsanjiang/SJVideoPlayer#417]
//
//  SJVideoCollectionViewCell.m
//  SJVideoPlayer_Example
//
//  Created by 畅三江 on 2019/6/26.
//  Copyright © 2019 changsanjiang. All rights reserved.
//

#import "SJVideoCollectionViewCell.h"

UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTapGesture:)];
[_coverImageView addGestureRecognizer:tap];

- (void)handleTapGesture:(id)sender {
    if ( [(id)_delegate respondsToSelector:@selector(coverItemWasTapped:)] ) {
        [_delegate coverItemWasTapped:self];
    }
}
handleTapGesture方法不会调用

**Comment by changsanjiang** [comment]
首次点击生效， 播放器被添加上去后， 只会响应播放器上的手势。
