### ISSUE TITLE
抖音预加载和自动播放怎么处理

### ISSUE THREAD

**Issue by yuhangjob** [changsanjiang/SJVideoPlayer#418]
- (void)sj_playerNeedPlayNewAssetAtIndexPath:(NSIndexPath *)indexPath {
    if ( indexPath == nil )
        return;
    // 进行播放
    NSURL *URL = _list[indexPath.row].URL;
    NSURL *playbackURL = [SJMediaCacheServer.shared playbackURLWithURL:URL];
    _player.URLAsset = [SJVideoPlayerURLAsset.alloc initWithURL:playbackURL playModel:[SJPlayModel playModelWithTableView:_tableView indexPath:indexPath]];
    [_player play];
    
    // 进行预加载
    [_prePrefetchTask cancel];
    [_nextPrefetchTask cancel];
    _prePrefetchTask = [self _prefetchTaskWithIndex:indexPath.row - 1]; // 预加载前一个视频
    _nextPrefetchTask = [self _prefetchTaskWithIndex:indexPath.row + 1]; // 预加载后一个视频
}
这个方法什么时候调用?设置了自动播放怎么避免触发两次播放

**Comment by changsanjiang** [comment]
@yuhangjob 刚刚简化了一下demo， 用最新的吧
