### ISSUE TITLE
SJVideoPlayerSettings的placeholder是UIImage

### ISSUE THREAD

**Issue by chjsun** [changsanjiang/SJVideoPlayer#42]
SJVideoPlayerSettings的placeholder是UIImage，所以不能设置UIImageView的contentMode属性，这样会导致如果展位图不够全屏，会被强制拉伸到全屏。而视频播放的时候，是居中，上下留白（黑）的。想要实现的是 占位图是视屏的第一帧，占位图完全贴合播放的真实大小，这样就会看起来流畅些。若占位是UIImageview或者吧contentMode暴露出来就好了。会更加灵活

**Comment by changsanjiang** [comment]
恩, 这个地方没有注意到,  下一版本我完善一下

**Comment by changsanjiang** [comment]
@chjsun 新版已更新了.

**Comment by chjsun** [comment]
兄弟，placeholderImageView是readonly的，不过我可以通过下方的方式进行设置。
![image](https://user-images.githubusercontent.com/13481443/48062426-f8624c80-e1fc-11e8-9492-9c3dbe5d8853.png)
