### ISSUE TITLE
播放m3u8视频时，设置显示底部进度条，依然无法显示出进度条，怎么解决

### ISSUE THREAD

**Issue by ashen-zhao** [changsanjiang/SJVideoPlayer#423]
**必现/偶发?**
播放m3u8视频时，设置显示底部进度条，依然无法显示出进度条，怎么解决

**描述bug**
播放m3u8视频时，设置显示底部进度条，依然无法显示出进度条，怎么解决

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
播放m3u8视频时，可以显示进度条

**运行环境**
 - iPhone 12pro 
 - iOS 14
 - Xcode 11.2.1
- Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
在这里直接return吧.  SJEdgeControlLayer.m

- (void)videoPlayer:(__kindof SJBaseVideoPlayer *)videoPlayer playbackTypeDidChange:(SJPlaybackType)playbackType {
    return;
    // ......
    }

**Comment by ashen-zhao** [comment]
谢谢你的回复，我这边设置return后，进度条和时间是出来了，但是显示的比较乱，不像mp4那样显示的完美。
截图如下：
<img width="372" alt="WX20210322-173356@2x" src="https://user-images.githubusercontent.com/11596525/111969225-f599f500-8b34-11eb-9450-4ab11396ec62.png">

**Comment by changsanjiang** [comment]
直播中的流无法获取时长信息, 把这些item移除了吧

**Comment by ashen-zhao** [comment]
好的， 多谢大佬协助
