### ISSUE TITLE
弱网下播放视频，在视频没有加载成功的时候，压入后台再进入前台 App会卡死

### ISSUE THREAD

**Issue by HopeBill** [changsanjiang/SJVideoPlayer#430]
**必现/偶发?**
必现

**描述bug**
弱网下播放视频，在视频没有加载成功的时候，压入后台再进入前台 App会卡死

**Demo中是否存在同样的问题?**
是

**运行环境**
 - 所有苹果手机
 - Version 12.2
 - Objective-C

**额外的**
作者Demo也有这个问题，参考demo：旋转控制2

**Comment by changsanjiang** [comment]
https://github.com/changsanjiang/SJVideoPlayer/blob/b788e68b06d30d64e3ff815fc8eae16370b6e5fd/Example/Pods/SJBaseVideoPlayer/SJBaseVideoPlayer/AVPlayer/SJAVMediaPlaybackController.m#L115

@HopeBill  先修改一下这里吧, 后面的版本我更新上去:  

```Objective-C
    if ( self.pauseWhenAppDidEnterBackground && self.assetStatus == SJAssetStatusReadyToPlay /*fix #430 */ )
```
