### ISSUE TITLE
自定义控制层无法响应点击事件

### ISSUE THREAD

**Issue by chensunwang** [changsanjiang/SJVideoPlayer#432]
我是通过addControlLayer添加的自定义控制层
切换也是正常 但是控制层上无法响应事件 比如添加了一个分享的控制层  点击某个分享按钮 不起作用

**Comment by changsanjiang** [comment]
@chensunwang  可以提供一些相关代码吗

**Comment by chensunwang** [comment]
`///
    /// 添加控制层到切换器中
    ///     只需添加一次, 之后直接切换即可.
    ///
    func addCustomControlLayerToSwitcher() {
        player.switcher.addControlLayer(forIdentifier: SJControlLayerShareIdentifier) { [weak self] (identifier) -> SJControlLayer in
            let vc = ShareLayerViewController()
            vc.centerContainerView.shareBtnClickBlock = { index in
                print("点击第\(index)个按钮")
            }
            vc.delegate = self
            return vc
        }
    }

// 这边是centerContainerView中创建的按钮
for i in 0...5 {
            let btn = UIButton(frame: CGRect(x: 40 + 76*i, y: 20, width: 40, height: 40))
            btn.setImage(UIImage.init(named: imageArr[i]), for: .normal)
            btn.tag = 1000 + i
            btn.extendEdgeInsets = UIEdgeInsets(top: 20, left: 20, bottom: 40, right: 20)
            btn.addTarget(self, action: #selector(shareBtnAction(sender: )), for: .touchUpInside)
            
            centerContainerView.addSubview(btn)
            
            let lab = UILabel()
            centerContainerView.addSubview(lab)
            lab.sizeToFit()
            lab.text = titleArr[i]
            lab.font = UIFont.regular(12)
            lab.textColor = .white
            lab.snp.makeConstraints { (make) in
                make.top.equalTo(66)
                make.centerX.equalTo(btn)
                make.height.equalTo(17)
            }
        }

// 点击事件我是通过block回调出去的
@objc func shareBtnAction(sender: UIButton) {
        if shareBtnClickBlock != nil {
            shareBtnClickBlock!(sender.tag - 1000)
        }
    }`

但是不会走这个block回调  我试过isUserInteractionEnabled的问题 但是并不能解决

**Comment by changsanjiang** [comment]
检测一下 centerContainerView 的frame看看

**Comment by chensunwang** [comment]
打印出来的centerContainerView.frame: (195.0, 195.0, 500.0, 100.0) 也是没问题的 控制层能正常显示

**Comment by changsanjiang** [comment]
@chensunwang  在这个demo里试试吧
[CustomControlLayer.zip](https://github.com/changsanjiang/SJVideoPlayer/files/6396214/CustomControlLayer.zip)

**Comment by changsanjiang** [comment]
@chensunwang 是否还存在问题呢?
