### ISSUE TITLE
Domain=AVFoundationErrorDomain Code=-11850操作停止如何解决

### ISSUE THREAD

**Issue by Clemmie-L** [changsanjiang/SJVideoPlayer#433]
**必现/偶发?**
必现

**描述bug**
Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSUnderlyingError=0x7f927ede4210
{Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}
, NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped})

**Demo中是否存在同样的问题?**
是

**运行环境**
 - iPhone 11
 - iOS 14.4
 - Xcode 12.4
 - Objective-C

eg: 使用sjvideoplayer简单接入

视频地址：https://savsg-dev.propertyraptor.com/hornet/src?p=/sav_sg/hornet/prp/video/164a60444c6a427f969aa4d1da2922bc.mp4

**Comment by Clemmie-L** [comment]
视频地址：https://savsg-dev.propertyraptor.com/hornet/src?p=/sav_sg/hornet/prp/video/164a60444c6a427f969aa4d1da2922bc.mp4

**Comment by changsanjiang** [comment]
让后台支持一下206请求
