### ISSUE TITLE
有缓存功能吗

### ISSUE THREAD

**Issue by WuXiaoTu** [changsanjiang/SJVideoPlayer#44]
第一次播放完成，第二次播放读取缓存播放

**Comment by changsanjiang** [comment]
使用[这个库](https://github.com/ChangbaDevs/KTVHTTPCache)配置一下URL进行播放, 就可以实现边播边缓存.

**Comment by changsanjiang** [comment]
```Objective-C
    NSURL *proxyURL = [KTVHTTPCache proxyURLWithOriginalURL:originalURL];
    _player = SJVideoPlayer.player;
    _player.URLAsset = [SJVideoPlayerURLAsset.alloc initWithURL:proxyURL];
```

**Comment by Jean1992** [comment]
设置了
NSURL *proxyURL = [KTVHTTPCache proxyURLWithOriginalURL:originalURL];
_player.URLAsset = [SJVideoPlayerURLAsset.alloc initWithURL:proxyURL];
对同一个视频多次尝试，发现proxyURL还是视频原链接originalURL的值，并没有缓存下来

**Comment by changsanjiang** [comment]
启动了吗

![image](https://user-images.githubusercontent.com/25744224/67187290-758dce00-f41c-11e9-91ef-f323eb8f8eab.png)

**Comment by Jean1992** [comment]
start是全局的吗？写在delegate还是用一次写一次？

**Comment by changsanjiang** [comment]
一次

**Comment by Jean1992** [comment]
> 一次

感谢解答
