### ISSUE TITLE
如何设置截图的清晰度

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [changsanjiang/SJVideoPlayer#443]
[self.player screenshotWithTime:_player.currentTime size:UIApplication.sharedApplication.keyWindow.rootViewController.view.size 
completion:^(__kindof SJBaseVideoPlayer * _Nonnull videoPlayer, UIImage * _Nullable image, NSError * _Nullable error) {

            }];

通过以上方法，传入了全屏时的size，截取到了当前播放的截图，但是与暂停时的停留画面相比，感觉截图不清晰，像素很低，如何保持和视频一样的清晰度呢？

**Comment by changsanjiang** [comment]
player.videoPresentationSize

**Comment by liunianhuaguoyanxi** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/17978155/120420673-619ba380-c397-11eb-9636-9e0f85f87797.png">
这个只读属性 设置不了
