### ISSUE TITLE
iOS 14.2 ，设置国外cdn的mp4后，马上进入后台，再进来会卡住

### ISSUE THREAD

**Issue by aleejin** [changsanjiang/SJVideoPlayer#445]
**必现/偶发?**
必现

**描述bug**
iOS 14.2 ，设置国外cdn的mp4后，开始转圈，马上进入后台，再进来会卡住。
这是我的视频链接 http://cdn-media-de.hala.icu/prod/53838549/202008042156.mp4
用你的不会卡住，因为你的一进去就马上加载成功了，我的加载比较慢，会出现这个情况。

**Demo中是否存在同样的问题?**
未测试

**你期望的结果是什么?**
我希望进入后台，再进来是不会卡住线程。

**运行环境**
 - iPhone 8p
 - iOS 14.2
 - Xcode 12.5
 - Objective-C
[Player.zip](https://github.com/changsanjiang/SJVideoPlayer/files/6682041/Player.zip)

**截图**
如果有必要的话，请上传几张截图

**额外的**
具体请查看我上传的demo
[Player.zip](https://github.com/changsanjiang/SJVideoPlayer/files/6682042/Player.zip)

**Comment by changsanjiang** [comment]
明早了我看看...

**Comment by aleejin** [comment]
麻烦了额，非常感谢，🙏🙏

> 明早了我看看...

**Comment by changsanjiang** [comment]
@aleejin 先手动改一下吧  https://github.com/changsanjiang/SJVideoPlayer/issues/430
