### ISSUE TITLE
画中画的按钮删除不了

### ISSUE THREAD

**Issue by ZXCheng** [changsanjiang/SJVideoPlayer#449]
**必现/偶发?**
必现

**描述bug**
player.defaultEdgeControlLayer.topAdapter.removeItem(forTag: SJEdgeControlLayerTopItem_PictureInPicture)
画中画的按钮删除不了

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone 11 Pro max
 - iOS 14.5
 - Xcode 12.5
 - Swift

**Comment by changsanjiang** [comment]
```oc
    if (@available(iOS 14.0, *)) {
        _player.defaultEdgeControlLayer.automaticallyShowsPictureInPictureItem = NO;
    }
```
