### ISSUE TITLE
环信发送的视频消息，视频链接不能播放，必现，测试链接地址见内容。

### ISSUE THREAD

**Issue by veryip7** [changsanjiang/SJVideoPlayer#450]
**必现/偶发?**
必现

**描述bug**
测试链接：https://a1-hw.easemob.com/1100210416094480/xiaolingtong/chatfiles/c8ac3b30-decb-11eb-8184-0f8d8be35234
但是在网页中视频能正常下载。
返回结果：SJAVMediaPlayer: Error Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。" UserInfo={NSLocalizedDescription=网络连接已中断。, NSUnderlyingError=0x2831bccf0 {Error Domain=NSOSStatusErrorDomain Code=-1005 "(null)"}}

**Demo中是否存在同样的问题?**
是
demo返回结果：SJAVMediaPlayer: Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x280591f20 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}

**运行环境**
 - iPhone 8
 - iOS 14.4
 - Xcode 12.5.1
 - Objective-C

**Comment by veryip7** [comment]
@jozdee @xyhuangjia @liangzcn @SummerZhuQiong

**Comment by changsanjiang** [comment]
![image](https://user-images.githubusercontent.com/25744224/124695869-a080c400-df16-11eb-8d1d-4269a6aa7d4b.png)

 contentType 不对

**Comment by changsanjiang** [comment]
再让服务器支持一下206请求

**Comment by veryip7** [comment]
> 再让服务器支持一下206请求

谢谢回复，另外可以提一个需求吗？如果链接不支持边下边播，可否让sdk支持下载完再播放？

**Comment by veryip7** [comment]
> 再让服务器支持一下206请求

好的，谢谢回复
