### ISSUE TITLE
请问iOS14的画中画功能，点击自带的画中画按键没有反应？

### ISSUE THREAD

**Issue by 290138645** [changsanjiang/SJVideoPlayer#451]
**必现/偶发?**
必现

**描述bug**
点击自带的画中画按键没有反应

**Demo中是否存在同样的问题?**
否

**你期望的结果是什么?**
需要怎么设置吗？

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
![IMG_1700](https://user-images.githubusercontent.com/12107017/124876836-09db0280-dffd-11eb-90e8-e1cbdf8078a5.PNG)

**Comment by 290138645** [comment]
` if (@available(iOS 14.0, *)) {
            _player.playbackObserver.pictureInPictureStatusDidChangeExeBlock = ^(SJBaseVideoPlayer  *_Nonnull player) {
                 switch ( player.playbackController.pictureInPictureStatus ) {
                    case SJPictureInPictureStatusUnknown:
                    case SJPictureInPictureStatusStarting:
                    case SJPictureInPictureStatusStopping:
                        break;
                    case SJPictureInPictureStatusRunning: {
                        // retain self
                     }
                        break;
                    case SJPictureInPictureStatusStopped: {
                       
                    }
                        break;
                }
            };
        }`

执行的是SJPictureInPictureStatusStopping

**Comment by LaiFengHai** [comment]
而且我发现画中画的按钮还无法通过topadapter移除

**Comment by m3u8playlist** [comment]
而且我发现画中画的按钮还无法获取item然后设置image

**Comment by changsanjiang** [comment]
开启项目后台权限, 如图: 

![image](https://user-images.githubusercontent.com/25744224/132087964-21aa9ba2-d46c-45ad-9bcd-baa55970979f.png)
