### ISSUE TITLE
video buffering  issue

### ISSUE THREAD

**Issue by DGP13** [changsanjiang/SJVideoPlayer#46]
If video buffering is state called.  

I'm work like insta story app. story in video is buffering is pause. 

==== here my code == . this code only for check is ready for play

 override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {

        if object as AnyObject? === self.SJplayer {
            if keyPath == "playStatus" {

                if self.SJplayer?.playStatus == .readyToPlay {

Thanks in advance

**Comment by changsanjiang** [comment]
I don't quite understand what you mean. Can you describe it in detail?
When the playback state is buffered, I will change the `pauseReason` to buffering and play status to pause.
