### ISSUE TITLE
demo中“collectionView.cell.collectionView.cell”会崩溃

### ISSUE THREAD

**Issue by gongsunqingyang** [changsanjiang/SJVideoPlayer#469]
**必现/偶发?**
必现

**描述bug**
collectionView嵌套时会崩溃

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
~

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C

**截图**
~

**额外的**
~

**Comment by changsanjiang** [comment]
已修复(SJBaseVideoPlayer v3.6.7)
