### ISSUE TITLE
能否支持.qsv格式的视频播放？

### ISSUE THREAD

**Issue by stoneUoU** [changsanjiang/SJVideoPlayer#476]
SJAVMediaPlayer: 118 - -[SJAVMediaPlayer observeValueForKeyPath:ofObject:change:context:] - Error Domain=AVFoundationErrorDomain Code=-11828 "无法打开" UserInfo={NSLocalizedFailureReason=不支持此媒体的格式。, NSLocalizedDescription=无法打开, NSUnderlyingError=0x280b056e0 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}}

**Comment by stoneUoU** [comment]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/24381761/138576446-9bf64703-19d3-4c92-a832-93e9347a3cf8.png">

https://file.panbaidu.cn/mbox/202110/24_407b2594/mortalkombat.mkv
.mkv格式也不支持

**Comment by pstkqzy** [comment]
这是播放器内核的问题，SJVideoPlayer默认用的AVPlyer，AVPlayer不支持它就不支持

**Comment by stoneUoU** [comment]
> 用ijk，如果还不行自行编译ijk把要用到的解码器都enable
好的，谢谢   我自己尝试下

**Comment by stoneUoU** [comment]
> 这是播放器内核的问题，SJVideoPlayer默认用的AVPlyer，AVPlayer不支持它就不支持

好的，谢谢    了解了，我看下怎么才能很好的解决

**Comment by stoneUoU** [comment]
亲测，有效    感谢提示

**Comment by KeynoWu** [comment]
请问自己编译ijk是咋弄的，有没有可参考的方案
