### ISSUE TITLE
Unable to install Pod file

### ISSUE THREAD

**Issue by vinayakpal** [changsanjiang/SJVideoPlayer#48]
[!] Error installing SJBaseVideoPlayer
[!] /usr/bin/git clone https://gitee.com/changsanjiang/SJBaseVideoPlayer.git /var/folders/ky/gx0qy0q106v_pz025qh4qvmh0000gn/T/d20181130-9861-k3qjoq --template= --single-branch --depth 1 --branch v1.5.0

Cloning into '/var/folders/ky/gx0qy0q106v_pz025qh4qvmh0000gn/T/d20181130-9861-k3qjoq'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by changsanjiang** [comment]
You can try again.
