### ISSUE TITLE
给tabbleview的headerview设置视频自动播放，点击全屏无响应

### ISSUE THREAD

**Issue by Z740732126** [changsanjiang/SJVideoPlayer#484]
**必现/偶发?**
必现

**描述bug**
给tabbleview的headerview设置视频，并进入直接自动播放，点击全屏无响应

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
告诉我如何解决当前问题

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

![1E369545-B95C-4084-B1D6-4D60915451CF](https://user-images.githubusercontent.com/15721655/144017978-31d64613-d1f8-47fd-ab5a-238f526243a8.png)
**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
```oc
// 1 自定义一个 headerView
@interface YourTableHeaderView : UIView
@property (...) UIView *playerSuperview;
@end

// 2 用这个方法初始化
SJPlayerModel *playModel = [SJPlayModel playModelWithTableView:self.tableView tableHeaderView:headerView superviewSelector:NSSelectorFromString(@"playerSuperview")];
```

**Comment by Z740732126** [comment]
谢谢，搞定
