### ISSUE TITLE
不能播放某些m3u8

### ISSUE THREAD

**Issue by xiezuan** [changsanjiang/SJVideoPlayer#489]
**必现/偶发?**
必现

**描述bug**
以下这个m3u8很奇怪，目前SJVideoPlayer无法播放，包括ijk,aliplayer,PLPlayerKit 那几个第三方的Sdk 也都试了都不行
https://d006.eduyun.cn/videoworks/mda-kicm2pcquni18ccd/ykt_tbkt_hls_1080_7/video/%E9%AB%98%E4%B8%80%E3%80%90%E8%8B%B1%E8%AF%AD%EF%BC%88%E4%BA%BA%E6%95%99%E7%89%88%EF%BC%89%E3%80%91Unit1%20Teenage%20Life%20%20Listening%20and%20Talking.m3u8

其它的m3u8可以播放,如以下这个
https://d006.eduyun.cn/videoworks/mda-kidbwu5qyv603cyt/ykt_tbkt_hls_1080_7/video/%E4%BA%8C%E5%B9%B4%E7%BA%A7%E6%95%B0%E5%AD%A6%EF%BC%88%E4%BA%BA%E6%95%99%E7%89%88%EF%BC%89%E3%80%8A100%E4%BB%A5%E5%86%85%E7%9A%84%E8%BF%9B%E4%BD%8D%E5%8A%A0%E6%B3%95%E3%80%8B.m3u8

但这两个m3u8文件我实在没不出有啥区别，不知道是在哪个环节有加密还是什么，上面的m3u8  直接用safari 是可以播的，用ios夸克浏览器显示是超级解码时可以播放，换成系统解码（应该也是AVPlayer）时无法播放。其它很多播放器都播不了。

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
这两个m3u8有什么区别，能否都支持播放

**运行环境**
 - iPhone X
 - iOS 15.0
 - Xcode 13
 - Objective-C

**截图**
无

**Comment by UrbanHooker** [comment]
像是因为第一个地址里每个切片都包含空格: 高一【英语（人教版）】Unit1 Teenage Life  Listening and Talking.m3u8.0.ts

**Comment by xiezuan** [comment]
> 像是因为第一个地址里每个切片都包含空格: 高一【英语（人教版）】Unit1 Teenage Life Listening and Talking.m3u8.0.ts

确实是空格的问题，非常感谢，参照 https://www.jianshu.com/p/700a3887ff52  的处理方式，转义处理了这个空格问题，可以用avplayer播放这个视频了。
