### ISSUE TITLE
第一次单击屏幕，topView和bottomView会闪一下。第二次单击才正常

### ISSUE THREAD

**Issue by JingHongMuYun** [changsanjiang/SJVideoPlayer#49]
1、开始播放视频之后，第一次单击屏幕，topView和bottomView会闪一下。第二次单击才正常显示和自动消失
2、播放高清网络视频，有两处异常：
①经常会出现转圈并暂停播放，双击后，视频可以正常继续播放（网络状态良好）
②转圈圈情况下，点击剪辑，完成后取消，圈停止转动，并悬浮在屏幕上。

**Comment by changsanjiang** [comment]
播放新资源时, 默认一秒后, 会显示控制层.  显示过程中, 再点击, 会触发隐藏, 这个可能就是你说的一闪而过的问题.... 

网络缓冲状态, 我晚上调整一下.

**Comment by JingHongMuYun** [comment]
> 播放新资源时, 默认一秒后, 会显示控制层. 显示过程中, 再点击, 会触发隐藏, 这个可能就是你说的一闪而过的问题....
> 
> 网络缓冲状态, 我晚上调整一下.

我仔细看了一下，确实是播放视频后，默认一秒显示控制层，这时恰巧我点击了，造成了闪现。

关于网络缓冲，您可以用我这个链接测试一下:https://www.apple.com/105/media/cn/mac/family/2018/46c4b917_abfd_45a3_9b51_4e3054191797/films/bruce/mac-bruce-tpl-cn-2018_1280x720h.mp4
等您调整完毕后，我再仔细研究下，谢谢分享

**Comment by changsanjiang** [comment]
缓冲的处理已优化 😁
