### ISSUE TITLE
部分视频（默认满屏）播放，点击横屏播放无效。

### ISSUE THREAD

**Issue by developerjet** [changsanjiang/SJVideoPlayer#495]
1.部分视频（尺寸大小占满屏）播放，点击切换横屏无效；
2.而大小未占满全屏的视频，点击横竖屏切换是正常的；

请问是什么原因呢，难道内部有做满屏检测处理。
NSString *videoURL = @"https://monkeyspace.blob.core.windows.net/cssg/CSSG864250c8e68bbb25ac1c36b532f183e2.mp4";

Tips：目前已按照Demo有进行UIViewController、UITabBarController、UINavigationController的分类配置。

**Comment by changsanjiang** [comment]
关闭这个选项， 只允许旋转
```oc
    _player.automaticallyPerformRotationOrFitOnScreen = NO;
```

**Comment by developerjet** [comment]
> 只允许旋转

好的，我试试
