### ISSUE TITLE
能不能在SJPlaybackRecord再加一个字符串参数

### ISSUE THREAD

**Issue by jieruian** [changsanjiang/SJVideoPlayer#508]
能不能在SJPlaybackRecord再加一个字符串参数，比如可以用来保存视频海报地址，大类视频id等等

**Comment by changsanjiang** [comment]
@jieruian https://github.com/changsanjiang/SJVideoPlayer/wiki/%E6%92%AD%E6%94%BE%E8%AE%B0%E5%BD%95#%E4%B8%80%E4%BA%9B%E8%A1%A5%E5%85%85

**Comment by trial** [comment]
如果想根据字符串来判断数据存不存在，而不是根据mediaId和userId，应该怎么做?
类似这样
 var record = SJPlaybackHistoryController.shared().record(forMedia: mediaUrl, mediaType: SJMediaTypeVideo)

**Comment by changsanjiang** [comment]
[SJPlaybackHistoryController.shared recordsForConditions:@[
        [SJSQLite3Condition conditionWithColumn:@"url" value:@"http://...mp4"],
        [SJSQLite3Condition conditionWithColumn:@"mediaType" value:SJMediaTypeVideo],
    ] orderBy:nil];

**Comment by changsanjiang** [comment]
@trial 调整对应搜索条件进行搜索
