### ISSUE TITLE
为什么在UICollectionViewCell上添加Player,isPlayOnScrollView这个属性是0?

### ISSUE THREAD

**Issue by 969990431** [changsanjiang/SJVideoPlayer#511]
_player = [SJVideoPlayer player];
    [self.contentView addSubview:self.player.view];
    [self.backImageView layoutIfNeeded];
    [self.player.view mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.mas_equalTo(self.backImageView);
    }];

**Comment by changsanjiang** [comment]
@969990431  内部是根据 Asset.playModel 给的视图信息确定的. 

这里有介绍: https://github.com/changsanjiang/SJVideoPlayer/wiki/UITableView%E5%8F%8AUICollectionView%E4%B8%AD%E6%92%AD%E6%94%BE%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88v3
