### ISSUE TITLE
aliplayer 播放结束点击重播异常

### ISSUE THREAD

**Issue by CH305426** [changsanjiang/SJVideoPlayer#516]
**必现/偶发?**
必现

**描述bug**
aliplayer 播放结束后点击重播, player是播放了, defaultEdgeControlLayer状态没刷新

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone 12 pro max
 - iOS 15.3.1
 - Xcode 13.2.1
 - Objective-C

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
好的, 我看一下

**Comment by changsanjiang** [comment]
已修复
