### ISSUE TITLE
播放器视图使用playModel.superviewSelector 在tableViewCell 上无法播放视频，遵循协议SJPlayModelPlayerSuperview就可以

### ISSUE THREAD

**Issue by ChoshimWy** [changsanjiang/SJVideoPlayer#527]

**Comment by changsanjiang** [comment]
在cell中需要实现 superviewSelector, 里面返回将要添加播放器的父视图;
例如 想要在 cell.contentView 上添加播放器, 则 superviewSelector 为 @selector(contentView);

**Comment by ChoshimWy** [comment]
> 在cell中需要实现 superviewSelector, 里面返回将要添加播放器的父视图;
> 例如 想要在 cell.contentView 上添加播放器, 则 superviewSelector 为 @selector(contentView);

这个也只能使用contentView吗，  我使用代码自定义创建的coverView就无效，Demo中使用的是Xib创建的Cell是不是这个问题影响了Selector查找的问题

**Comment by ChoshimWy** [comment]
> > 在cell中需要实现 superviewSelector, 里面返回将要添加播放器的父视图;
> > 例如 想要在 cell.contentView 上添加播放器, 则 superviewSelector 为 @selector(contentView);
> 
> 这个也只能使用contentView吗， 我使用代码自定义创建的coverView就无效，Demo中使用的是Xib创建的Cell是不是这个问题影响了Selector查找的问题

我知道了，Swift添加的视图元素需要增加@objc的声明才能通过Selector去查找到该元素
