### ISSUE TITLE
你好，请问外挂字幕支持实时替换吗？

### ISSUE THREAD

**Issue by fangyuxi** [changsanjiang/SJVideoPlayer#531]
你好，请问外挂字幕支持实时替换吗？
比如 asset.subtitles = subtitles, 在播放的时候替换这个subtitles会在不影响播放的情况下实时替换吗？

另外目前支持直接提供srt字幕文件，框架自动解析文件吗？我看demo目前需要手动解析字幕后创建subtitles数组。

谢谢大佬。

**Comment by fangyuxi** [comment]
self.player.subtitlesPromptController.subtitles = subtitles_replace;

我找到一个办法，运行起来效果可以，但是不知道是否有问题。

**Comment by changsanjiang** [comment]
可以根据那个协议, 自定义一个, 试试扩展一些方法看看

**Comment by hainuo** [comment]
> self.player.subtitlesPromptController.subtitles = subtitles_replace;
> 
> 我找到一个办法，运行起来效果可以，但是不知道是否有问题。

请问 您找到可以播放中替换字幕的方法了吗
