### ISSUE TITLE
App横屏模式下的页面 视频全屏界面会错乱

### ISSUE THREAD

**Issue by mazhao1609** [changsanjiang/SJVideoPlayer#533]
你好作者，我们app支持横竖屏，在横屏状态进入视频页面的时候 切换到全屏播放器页面布局会错乱 看代码好像只支持竖屏模式
期望作者可以完善

**Comment by changsanjiang** [comment]
使用`fitOnScreen`功能, 参考Demo中的 iPadDemo 部分;

https://github.com/changsanjiang/SJVideoPlayer/blob/8242b5cc1e63f91e1bf9ed588eac84ac005eb69d/Example/iPadDemo/ViewController.m#L22
