### ISSUE TITLE
使用AirPlay的时候能否做到跟画中画一样显示系统的背景

### ISSUE THREAD

**Issue by chenfengfeng** [changsanjiang/SJVideoPlayer#536]
**你希望达到的效果**
使用AirPlay的时候，希望能够达到跟画中画一样的背景，我用系统的avplay默认的就有这个实现，不清楚是不是因为被视频的layer挡住了所以看不到，希望能够显示出来。

**Comment by chenfengfeng** [comment]
查询文档发现avplayer有个属性isExternalPlaybackActive
希望能够公开这个属性，或者公开avplayer的属性，这样就可以直接调用
就可以在currentTimeDidChangeExeBlock回调里面查询是否打开了airplay，从而显示一个AirPlay正在播放的页面挡住主画面

**Comment by chenfengfeng** [comment]
通过查阅源代码，发现还是有可行性的方案，以下是我的方案：

```swift
player.playbackObserver.currentTimeDidChangeExeBlock = {[weak self] player in
    guard let self = self else {
        return
    }
    if let backController = player.playbackController as? SJAVMediaPlaybackController {
        if let mediaPlayer = backController.currentPlayer {
            self.airplayView.isHidden = !mediaPlayer.avPlayer.isExternalPlaybackActive
        }
    }
}
```

self.airplayView是我自己建立的一个view，添加：player.defaultEdgeControlLayer.insertSubview(airplayView, at: 0)
目前使用上还行，没有其他问题

**Comment by changsanjiang** [comment]
可以尝试修改一下源码, 提个pr, 到时候合并进来

**Comment by chenfengfeng** [comment]
> 可以尝试修改一下源码, 提个pr, 到时候合并进来



> 可以尝试修改一下源码, 提个pr, 到时候合并进来

OK好，我会整理下代码提交下pr
