### ISSUE TITLE
SJRotationManager_4 没有文件，导致在 app delegate 中。使用  return window.sj_4_supportedInterfaceOrientations; 报错 无法找到

### ISSUE THREAD

**Issue by 99283817** [changsanjiang/SJVideoPlayer#539]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by 99283817** [comment]
安装方法。pod 'SJVideoPlayer'

**Comment by 99283817** [comment]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/20876910/178886487-ac71775f-d92a-4c82-b4e6-41d92093981f.png">

**Comment by changsanjiang** [comment]
已修复,  需要更新 SJVideoPlayer 到  3.4.1;

**Comment by ReefJones** [comment]
> 已修复，需要更新SJVideoPlayer到3.4.1；怎么更新到3.4.1？更新了好几遍都是3.3.3
