### ISSUE TITLE
app进去的第一个view里player无法旋转

### ISSUE THREAD

**Issue by trial** [changsanjiang/SJVideoPlayer#541]
如果从一个view跳转到带player的view是可以正常旋转的，如果是root view里有player，点击旋转按钮无反应

**运行环境**
 - iPhone XS max
 - iOS 15.5
 - Swift

**Comment by changsanjiang** [comment]
方便提供一个demo吗

**Comment by trial** [comment]
> 

[](https://github.com/trial/cdn/blob/main/Playr.zip)

**Comment by trial** [comment]
https://github.com/trial/cdn/blob/main/Playr.zip

> 方便提供一个demo吗

**Comment by changsanjiang** [comment]
[Playr 2.zip](https://github.com/changsanjiang/SJVideoPlayer/files/9380547/Playr.2.zip)
已修复(SJBaseVideoPlayer: 3.7.3.4)
