### ISSUE TITLE
手势异常

### ISSUE THREAD

**Issue by CH305426** [changsanjiang/SJVideoPlayer#548]
**必现/偶发?**
必现/偶发

**描述bug**
   _player.gestureController.supportedGestureTypes = SJPlayerGestureTypeMask_SingleTap | SJPlayerGestureTypeMask_DoubleTap | SJPlayerGestureTypeMask_Pan_V;

手势任然触发 SJPlayerGestureTypeMask_Pan_H

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone 12 pro max
 - iOS 15
 - Xcode 11.2.1
 - Objective-C

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
已修复 [SJBaseVideoPlayer v3.7.3](https://github.com/changsanjiang/SJBaseVideoPlayer/releases/tag/v3.7.3)
