### ISSUE TITLE
横屏模式下，重播一次后就无法返回了。。。

### ISSUE THREAD

**Issue by KiyoCao** [changsanjiang/SJVideoPlayer#55]
嵌套才tableViewCell 中使用的时候，横屏播放后，再重播一次后就无法返回了。。。缩小按钮跟播放按钮也无法点击了。。。。

手机开启了自动旋转屏幕。

**Comment by changsanjiang** [comment]
嵌套 tableViewCell 是什么情况的,   可否加我一下 QQ 1779609779, 详聊?
