### ISSUE TITLE
升级3.4.1后，在ios16上崩溃

### ISSUE THREAD

**Issue by BeginnerF** [changsanjiang/SJVideoPlayer#551]
**必现/偶发?**
必现

**描述bug**
线上版本：sdk升级3.4.1版本后，在手机系统ios16环境下， 旋转异常崩溃，我用的是sdk中DY的例子，也根据文档适配了旋转配置，线上还是有崩溃出现，

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
怎么解决这个问题

**运行环境**
 - iPhone
 - iOS 16
 - Objective-C

**截图**
![image](https://user-images.githubusercontent.com/26005167/182504184-c9f25a74-6067-4a46-94c8-c1556fdb1713.png)

**额外的**
最好能提供出现bug的Demo

**Comment by BeginnerF** [comment]
![image](https://user-images.githubusercontent.com/26005167/182516147-36235792-3f1b-423b-a691-035ad5df30fb.png)

**Comment by kingstal** [comment]
debug example工程，发现旋转控制的示例在最新的iOS 16版本上，横竖屏旋转不生效

**Comment by changsanjiang** [comment]
已解决, 更新到最新版本(3.4.2)
