### ISSUE TITLE
iPad分屏开发，将Requires Full Screen设置为NO全屏按钮点击无效。

### ISSUE THREAD

**Issue by GANGMENGCAO** [changsanjiang/SJVideoPlayer#555]
**必现/偶发?**
必现

**描述bug**
iPad分屏开发，将Requires Full Screen设置为NO，全屏按钮点击无效。
如果Requires Full Screen设置为YES是可以全屏的播放的，但是就无法分屏。如果Requires Full Screen设置为NO，可以分屏，但是无法全屏播放。
具体配置如图
<img width="752" alt="image" src="https://user-images.githubusercontent.com/30521410/184477051-0d4a5a79-a693-41a1-ab8f-bea456d24236.png">

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
希望分屏和全屏不产生冲突，分屏的时候全屏按钮点击生效。

**运行环境**
 - iPad
 - iOS 15.5
 - Xcode 13.0
 - Objective-C

**截图**
<img width="527" alt="image" src="https://user-images.githubusercontent.com/30521410/184477312-34a4349a-6802-4821-9e3b-177245ea08e5.png">

**额外的**

**Comment by changsanjiang** [comment]
ipad 用 fitOnScreen； 
```Objective-C
    _player = [SJVideoPlayer player];
    _player.onlyFitOnScreen = YES;
    
```
