### ISSUE TITLE
使用ijk播放器重播按钮点击没反应

### ISSUE THREAD

**Issue by slash130** [changsanjiang/SJVideoPlayer#561]
使用ijk播放器的时候视频播放结束后点击重播按钮没反应，用默认播放器重播好使，这个不知道是不是bug。

**Comment by changsanjiang** [comment]
@slash130 来个视频, 我测试看看.  Q群联系也行: 930508201  或者 610197491

**Comment by slash130** [comment]
这个是视频的问题
