### ISSUE TITLE
切换urlAsset之后 前面播放的视频声音还在

### ISSUE THREAD

**Issue by MidnightSmokingSoul** [changsanjiang/SJVideoPlayer#563]
切换urlAsset之后 前面播放的视频声音还在 就会出现两个声音 返回上一页之后 前面那个声音还在 需要调用哪个方法来关闭播放器 
我调用player?.stop()无效

**Comment by changsanjiang** [comment]
感觉有内存泄漏, 检查一下使用的block, 看看有没有循环引用之类的;

**Comment by MidnightSmokingSoul** [comment]
> 有内存检查查看，检查使用的块，查看有没有循环引用之类的；

是的 内存泄露了 block里没有加[weak self].我现在切换视频的时候是用player?.pause() 暂停上个视频 这样处理不会出问题吧

**Comment by changsanjiang** [comment]
[weak self] 最好养成习惯, 防止异常情况出现😄

**Comment by MidnightSmokingSoul** [comment]
嗯啊  非常谢谢
