### ISSUE TITLE
iOS16旋转失效

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [changsanjiang/SJVideoPlayer#566]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥
iOS16旋转失效，    [self.rotationManager rotate];

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone 14
 - iOS 16
 - Xcode 14
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图
<img width="615" alt="image" src="https://user-images.githubusercontent.com/17978155/190062959-6f5fff96-5a73-4275-ab5b-74105de6aba3.png">

**额外的**
最好能提供出现bug的Demo

**Comment by changsanjiang** [comment]
更新到最新版本就好了

**Comment by liunianhuaguoyanxi** [comment]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/17978155/190063332-bc9a43c6-7b71-4f12-af0a-9526c09d807e.png">
是最新的呢

**Comment by changsanjiang** [comment]
感觉跑的老版本, 清理一下重跑看看 shift + cmd + k

**Comment by liunianhuaguoyanxi** [comment]
可以了 但是发现新的旋转bug了，[self.rotationManager rotate];后 底层SJRotationManager_iOS_16_Later.m方法会走
<img width="737" alt="image" src="https://user-images.githubusercontent.com/17978155/190065940-e7aac575-23d2-43ce-8e21-4bae56561ea9.png">
进行旋转成横屏后
但是他还会继续走
<img width="748" alt="image" src="https://user-images.githubusercontent.com/17978155/190066099-dcfa76ee-657e-4e3b-a910-642e3eca76ee.png">
导致又旋转回来了，变成竖屏了

**Comment by changsanjiang** [comment]
根据旋转配置2 修改一下就行： 
https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
