### ISSUE TITLE
ios16无法旋转全屏，半屏—>全屏，然后一闪又退回到半屏界面

### ISSUE THREAD

**Issue by tikejc** [changsanjiang/SJVideoPlayer#568]
设备：iPhone13 Pro Max
系统：iOS16
问题：
**1、使用ijk播放器，半屏—>全屏，在全屏界面闪一下，就退回到半屏了。
2、半屏—>全屏：原来半屏界面是没有锁屏按钮的，突然闪一下退回到半屏，此时发现在半屏界面，锁屏按钮奇迹般出现了。**
3、如果打开手机重力感应旋转开关，把iPhone手机处于竖屏和横屏，播放器能正常响应全屏和半屏。

希望作者尽快解决，祝好。

**Comment by slash130** [comment]
@tikejc 这种情况是点击全屏按钮出现的吗？

**Comment by changsanjiang** [comment]
1: 闪屏问题在查看修复
2和3: 根据 [旋转配置2] (https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E9%85%8D%E7%BD%AE%E6%97%8B%E8%BD%AC) 做一下调整, 修改一下就好了

**Comment by tikejc** [comment]
@changsanjiang 问题1希望作者尽快解决，解决了麻烦说一下，希望作者重新再发一个release版本，谢谢

**Comment by changsanjiang** [comment]
@tikejc 可以先替换一下 https://github.com/changsanjiang/SJVideoPlayer/issues/565#issuecomment-1247515893

**Comment by tikejc** [comment]
@changsanjiang 作者你好，我这边测试，按照你说的替换SJRotationManager_iOS_16_Later.m文件，问题1任然存在，就是从：半屏—>全屏(横屏)，然后闪一下，屏幕又从全屏退回到半屏了，问题任然没有解决，我看那个XR用户他说他的问题解决了，可能我的手机是iPhone13 Pro Max(6.7寸的屏幕)大屏幕吧，我这边测试3个iPhone13 Pro Max设备都是问题1的情况，3个设备系统都是iOS16

**Comment by changsanjiang** [comment]
> 你那边项目的旋转配置应该没做好, 根据 [旋转配置2](https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E9%85%8D%E7%BD%AE%E6%97%8B%E8%BD%AC) 做一下调整

**Comment by tikejc** [comment]
@changsanjiang 好的，我配置一下，有问题再反馈，谢谢
