### ISSUE TITLE
iOS 16 全屏按钮点击失效

### ISSUE THREAD

**Issue by YuanJiaShuai** [changsanjiang/SJVideoPlayer#569]
**必现/偶发?**
必现/偶发

**描述bug**
清晰简单地描述这个bug是啥

**Demo中是否存在同样的问题?**
是/否

**你期望的结果是什么?**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 11.2.1
 - Objective-C/Swift

**截图**
如果有必要的话，请上传几张截图

**额外的**
最好能提供出现bug的Demo

使用Xcode 14 运行 iOS 16设备，全屏按钮点击后没有效果；
使用Xcode 14 运行 iOS 15设备，点击全屏按钮黑色褶照会变成一个横条，一闪而过，然后全屏成功

**Comment by changsanjiang** [comment]
升级到 [3.4.2](https://github.com/changsanjiang/SJVideoPlayer/releases/tag/v3.4.2)

[]旋转配置2](https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E9%85%8D%E7%BD%AE%E6%97%8B%E8%BD%AC)记得调整一下

**Comment by YuanJiaShuai** [comment]
好的，感谢大佬指点
