### ISSUE TITLE
Crash in iOS 10

### ISSUE THREAD

**Issue by jahnaviwisdom** [changsanjiang/SJVideoPlayer#57]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x608000387f90 of class SJBaseVideoPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x600000a2e080> (
<NSKeyValueObservance 0x600000a53fb0: Observer: 0x7f93fb14bc00, Key path: playStatus, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x600000854a60>

**Comment by changsanjiang** [comment]
Who is `Observer `, have you removed it?
