### ISSUE TITLE
iOS 16的makeKeyWindow导致页面的Size发生不必要的变化

### ISSUE THREAD

**Issue by hstdt** [changsanjiang/SJVideoPlayer#573]
继续 https://github.com/changsanjiang/SJVideoPlayer/issues/532 的讨论

**必现/偶发?**
项目必现，demo一定概率触发

**描述bug**
`Landscape`转`Portrait`的时候，必然会导致一次sourceWindow的size发生变化，而实际上此时rootViewController并不会发生转动，还是被触发了`viewWillTransition`，{414, 896} -> {896, 414} -> {414, 896} 
这些逻辑在demo中无法很好体现，但是在实际项目中，会导致页面不必要的滑动，Player停止(注释掉所有的viewWillTransition方法也照旧)

**Demo中是否存在同样的问题?**
是

**你期望的结果是什么?**
不要触发`viewWillTransition`等其他操作

**运行环境**
 - iPhone X
 - iOS 16
 - Xcode 14
 - Swift

**截图**
makeKeyWindow之前的frame是正确的，在调用之后尺寸反而发生了变化

<img width="1064" alt="CleanShot 2022-09-16 at 20 55 18" src="https://user-images.githubusercontent.com/10215098/190644631-9202db84-400c-40c9-89a7-aa85ee012648.png">

尝试采用的一些workaround: 

1. rootViewController暂时拿掉，不起作用，window尺寸没变化了，但是`viewWillTransition`还是会被触发

<img width="1084" alt="CleanShot 2022-09-16 at 20 54 24" src="https://user-images.githubusercontent.com/10215098/190644852-b5b8c1b8-f820-4141-b7f8-b7e136cecdd2.png">

2. 将`SJRotationFullscreenWindow`的`alpha`设置为0从而隐藏，效果较好。就算很复杂的项目，只要不触发旋转，就会减少很多意外
https://github.com/changsanjiang/SJBaseVideoPlayer/compare/master...hstdt:SJBaseVideoPlayer:master

<img width="1625" alt="CleanShot 2022-09-16 at 21 07 22" src="https://user-images.githubusercontent.com/10215098/190645898-0f20bfee-acda-4be8-b4cc-5909d248c292.png">

**额外的**

和 #532 中的demo差距不大，就是增加了一个打印，展示window尺寸莫名发生了变化
[player.zip](https://github.com/changsanjiang/SJVideoPlayer/files/9584264/player.zip)

**Comment by hstdt** [comment]
@changsanjiang 加了一个ParentViewController之后，出现位移的概率大幅增加(这也是我项目目前的用法，再参杂其他逻辑，以及更多childviewcontroller，导致几乎复现率100%)

https://user-images.githubusercontent.com/10215098/190837665-5eb7b3fd-f091-4c75-a006-868d447a548b.mp4

[playerv3.zip](https://github.com/changsanjiang/SJVideoPlayer/files/9590799/playerv3.zip)

**Comment by lunarboat** [comment]
同问，出现相同问题，在横屏旋转恢复到竖屏列表时候，contentOffset会变化

**Comment by changsanjiang** [comment]
已修复, SJBaseVideoPlayer 需要更新到 3.7.5;

**Comment by changsanjiang** [comment]
@lunarboat @hstdt
