### ISSUE TITLE
iOS16已配置竖屏，仍然会自动旋转

### ISSUE THREAD

**Issue by XiaoPangTang** [changsanjiang/SJVideoPlayer#579]
**必现/偶发?**
必现

**描述bug** 
新建一个空白测试项目，pod导入SJVideoPlayer，完成作者的[配置旋转](https://github.com/changsanjiang/SJVideoPlayer/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#%E9%85%8D%E7%BD%AE%E6%97%8B%E8%BD%AC)，但是仍然会自动旋转。（手机已在控制中心关闭固定旋转）。但是跑作者的Demo不会。

**Demo中是否存在同样的问题?**
否

**你期望的结果是什么?**
解决自动旋转的问题

**运行环境**
 - iPhone 14 Pro Max
 - iOS 16
 - Xcode 14.0
 - Objective-C

**截图**
见Demo

**额外的**
[Demo.zip](https://github.com/changsanjiang/SJVideoPlayer/files/9644242/Demo.zip)

**Comment by XiaoPangTang** [comment]
不好意思，刚刚发现可能是是属于Xcode 14的bug，clean也无效。发现连着线跑真机，运行的时候会自动旋转，拔了线就没问题了，第一次碰到这个情况。
另外，感谢作者。

**Comment by kklwg** [comment]
我也遇到了这个问题。  真机连线调试会自动旋转。 不连线就是好的。 刚开始以为是缓存，卸载App重装，还是这样。  不光是iOS16.0，我的一个iPad 15.0也是如此。  Xcode是14。 Maybe这是Xcode的bug。   
最近在做iPad的适配。寻思自己也没改代码啊， 怎么出问题了。还以为线上的App会有问题，没想到线上的app是好的。没改代码，却表现不一致。   花了一天时间各种查问题，最后还是在这里看到了答案。
