### ISSUE TITLE
点击右上角更多按钮，要求AppDelegate中有window属性，否则闪退

### ISSUE THREAD

**Issue by hstdt** [changsanjiang/SJVideoPlayer#580]
**必现/偶发?**
必现

**描述bug**
点击右上角更多按钮，闪退

**Demo中是否存在同样的问题?**
否

**你期望的结果是什么?**
不要求AppDelegate中有window属性

**运行环境**
 - iPhone X
 - iOS 13
 - Xcode 14
 - Swift

**截图**

**额外的**
同之前已修复的缺少`window`属性闪退问题

**Comment by changsanjiang** [comment]
已修复
