### ISSUE TITLE
有一个小问题

### ISSUE THREAD

**Issue by SuperEvilRabbit** [changsanjiang/SJVideoPlayer#59]
我设置了在DefaultPlayer这个控制器里我设置了autoPlayWhenPlayStatusIsReadyToPlay为NO，还是自动播放，打断点发现在这个类里面SJBaseVideoPlayer的这个方法vc_viewDidAppear里直接给播放了 是不是应该再加个判断

**Comment by changsanjiang** [comment]
恩, 对的.  这个问题, 下一版我再修复吧

**Comment by changsanjiang** [comment]
可能还需要另外一个变量, 记录是否播放过.

**Comment by SuperEvilRabbit** [comment]
嗯嗯 感谢😊 打卡下班啦
