### ISSUE TITLE
播放器缺少标题啊

### ISSUE THREAD

**Issue by shenguanjiejie** [changsanjiang/SJVideoPlayer#6]
一般播放器都会在左上角用来显示视频名称的,但是好像并不支持,能不能加入一下

**Comment by changsanjiang** [comment]
😅你好, 今天刚好加上(v1.4.5). 参考其他播放器, 标题只有在全屏的时候, 才会显示.

**Comment by shenguanjiejie** [comment]
不全屏显示标题的需求量也很大啊... 要不增加一个设置 可选也行

**Comment by changsanjiang** [comment]
好的, 稍等一下. 我现在就加上开关.

**Comment by changsanjiang** [comment]
你好, 开关已经加上了.
