### ISSUE TITLE
请问正确的 重复播放、循环播放 的方法是？

### ISSUE THREAD

**Issue by loveuqian** [changsanjiang/SJVideoPlayer#62]
找一圈都没有看到相关的 重复播放、循环播放 的设置
现在用的是在 playDidToEndExeBlock 里面 replay 一下

**Comment by changsanjiang** [comment]
这样操作没问题.  
由于一些其他原因, 暂时没有循环播放的接口, 后续可能会加上.

**Comment by loveuqian** [comment]
[test0123.zip](https://github.com/changsanjiang/SJVideoPlayer/files/2790510/test0123.zip)
[问题视频.zip](https://github.com/changsanjiang/SJVideoPlayer/files/2790523/default.zip)

能否帮我看看这个 demo，有2个 cell 复用的问题，应该怎么改改

**Comment by changsanjiang** [comment]
稍等

**Comment by changsanjiang** [comment]
@loveuqian 不好意思, 这种嵌套, CollectionViewCell 嵌套 CollectionView 存在复用的 Bug.

**Comment by changsanjiang** [comment]
我想想办法解决一下

**Comment by loveuqian** [comment]
我看你的 demo 这种嵌套貌似没问题啊
不过你是 cell 内是一个 SJHasCollectionView
但是 SJHasCollectionView 也是有一个 collectionView

**Comment by changsanjiang** [comment]
恩, 我的那个Demo中, 也存在这样的Bug.   没有监听全部的CollectionView, 这样在复用的情况下, 就会出现问题.

**Comment by changsanjiang** [comment]
因为你的一屏展示的 CollectionView 很多, 所以这个Bug, 就明显的显现出来了.

**Comment by loveuqian** [comment]
![image](https://user-images.githubusercontent.com/9745332/51667883-ede57100-1ffb-11e9-934a-ef7559fde0a5.png)
不会啊，我把你的 demo 改成这样子也没重现复用的 bug 呢，我试下改成跟你 demo 一模一样

**Comment by changsanjiang** [comment]
@loveuqian 这个问题刚修复, 我待会发个版本. 

// 我在你原来的Demo中, 修改了一下.  请看附件. 
[test0123 2.zip](https://github.com/changsanjiang/SJVideoPlayer/files/2791049/test0123.2.zip)


![image](https://user-images.githubusercontent.com/25744224/51669355-410cf300-1fff-11e9-85fb-98f037b90f02.png)

**Comment by changsanjiang** [comment]
如果有其他问题, 可以加我QQ: 1779609779. 微信同号.
