### ISSUE TITLE
直播流

### ISSUE THREAD

**Issue by UnicomMrLee** [changsanjiang/SJVideoPlayer#63]
怎么加载直播流数据呢

**Comment by changsanjiang** [comment]
是m3u8的吧? 如果是 直接用URL播放就可以了. 

![image](https://user-images.githubusercontent.com/25744224/51601607-d183fe80-1f3f-11e9-9d94-4b36fa94e28b.png)

**Comment by UnicomMrLee** [comment]
> 是M3U8的吧？如果是直接用URL播放就可以了。
> 
> ![图片](https://user-images.githubusercontent.com/25744224/51601607-d183fe80-1f3f-11e9-9d94-4b36fa94e28b.png)

**Comment by UnicomMrLee** [comment]
谢谢就是m3u8的
