### ISSUE TITLE
每次模拟器播放视频的时候都有这个麦克风弹窗，请问解决办法

### ISSUE THREAD

**Issue by loveuqian** [changsanjiang/SJVideoPlayer#67]
![image](https://user-images.githubusercontent.com/9745332/52770116-3a592500-306d-11e9-948a-59d33da6b1c7.png)

**Comment by changsanjiang** [comment]
如下, 去掉xcode的勾选. 再试试

![image](https://user-images.githubusercontent.com/25744224/52770716-d0417f80-306e-11e9-9787-e45478a700f5.png)
