### ISSUE TITLE
再报一个 bug

### ISSUE THREAD

**Issue by loveuqian** [changsanjiang/SJVideoPlayer#68]
使用列表自动播放

假设有很多个 cell，但只有第0个和第10个是有视频
那么刷新的完之后，调用 sj_needPlayNextAsset 会自动播放第0个的视频
滑动列表，第0个会暂停，滑到第10个，会播放第10个

这些都正常，有问题的是

刷新完之后，调用播放，播放第0个
滑动列表，第0个暂停
滑到第5个，然后又滑回到第0个
这个时候第0个并没有自动播放

如果没说清楚的话，我上 demo

**Comment by changsanjiang** [comment]
@loveuqian 你好, 如果有demo的话, 发我一个吧

**Comment by loveuqian** [comment]
[列表自动播放.zip](https://github.com/changsanjiang/SJVideoPlayer/files/2868772/default.zip)

@changsanjiang 

打开后，列表第0个播视频
滑动列表，视频暂停
再滑回第0个，视频还是暂停

**Comment by changsanjiang** [comment]
@loveuqian  收到.

**Comment by changsanjiang** [comment]
@loveuqian 可以暂时先手动调用一下播放. 如下: 

```Objective-C
     _player.playerViewWillAppearExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull videoPlayer) {
            [videoPlayer play];
 };
```

![image](https://user-images.githubusercontent.com/25744224/52850425-6d271a00-314e-11e9-815d-126c24e89d5f.png)

**Comment by loveuqian** [comment]
get

**Comment by changsanjiang** [comment]
@loveuqian 开启自动播放的这个情况没有考虑到, 下一个版本, 我修改一下. 😆

**Comment by changsanjiang** [comment]
@loveuqian  用下面的新属性吧, 记得更新一下库. 

```Objective-C
_player.resumePlaybackWhenPlayerViewScrollAppears = YES;
```

**Comment by loveuqian** [comment]
get

**Comment by loveuqian** [comment]
如何在 seekToTime 之后 pause
貌似在 completionHandler 里调 pause，并不会生效
