### ISSUE TITLE
刘海屏内存飙升

### ISSUE THREAD

**Issue by smile659974981** [changsanjiang/SJVideoPlayer#71]
我在一个控制器里添加了视图控制器并且添加了下面的代码

 **_rotationManager = [[SJVCRotationManager alloc] initWithViewController:self];
    _player.rotationManager = _rotationManager;
    _player.supportedOrientation = SJAutoRotateSupportedOrientation_LandscapeLeft;
    /// update device orientation
    [[UIDevice currentDevice] setValue:@(UIDeviceOrientationPortrait) forKey:@"orientation"];
    [[UIDevice currentDevice] setValue:@(UIDeviceOrientationLandscapeLeft) forKey:@"orientation"];**

    **__weak typeof(self) _self = self;
    _player.clickedBackEvent = ^(SJVideoPlayer * _Nonnull player) {
        __strong typeof(_self) self = _self;
        if ( !self ) return;
        [[UIDevice currentDevice] setValue:@(UIDeviceOrientationPortrait) forKey:@"orientation"];
        [self.navigationController popViewControllerAnimated:YES];
    };**

刘海屏会出现这种情况：[Snapshotting] a view (0x1057c6de0, SJButtonItemCollectionViewCell)  that has not been rendered at least once requires afterScreenUpdates:YES
导致内存一直飙升，卡住，然后崩溃

iphone X 以下的机型正常

**Comment by changsanjiang** [comment]
有相关的Demo吗?

**Comment by changsanjiang** [comment]
这个问题应该出在之前的一个旧版本上, 尝试一下最新版的吧.
