### ISSUE TITLE
mute 功能好像坏了

### ISSUE THREAD

**Issue by loveuqian** [changsanjiang/SJVideoPlayer#72]
demo 随便找个 player 改成 mute = YES
跑起来后看，好像还是有声音
![image](https://user-images.githubusercontent.com/9745332/54407988-24e22400-471b-11e9-88ae-c1d3f598cf6e.png)

**Comment by changsanjiang** [comment]
哦哦, 放到设置资源后面吧, 或者主动激活一下 playbackController. 下个版本, 我修复他.
```
// 先主动激活一下吧.  下个版本我修复这个问题
[_player playbackController];
_player.mute = YES:
```
