### ISSUE TITLE
在 Cell 上会出现重用问题？

### ISSUE THREAD

**Issue by GodzzZZZ** [changsanjiang/SJVideoPlayer#73]
在 TableViewCell 上使用出现了重用问题，是我使用方式有问题吗？

**Comment by changsanjiang** [comment]
<img width="695" alt="屏幕快照 2019-03-16 下午1 38 08 1" src="https://user-images.githubusercontent.com/25744224/54471249-f2a2f600-47f0-11e9-8a24-9896acae92d1.png">

父视图设置 Tag了吗?

**Comment by GodzzZZZ** [comment]
设置了

**Comment by changsanjiang** [comment]
播放初始化那块截个图 看一下

**Comment by GodzzZZZ** [comment]
![屏幕快照 2019-03-16 下午1 47 00 1](https://user-images.githubusercontent.com/36092926/54471331-2af70400-47f2-11e9-9714-e1cc99ba842d.png)

**Comment by changsanjiang** [comment]
看起来没啥问题.
那个 bgImageView 怎么初始化的呢?

**Comment by GodzzZZZ** [comment]
![屏幕快照 2019-03-16 下午1 56 16](https://user-images.githubusercontent.com/36092926/54471401-4d3d5180-47f3-11e9-93ef-1b28648ef883.png)
大概是这样。
而且进入tableView 第一个cell 不会自动播放，咱们这个播放哪个cell上的视频逻辑好像有点问题，最好判断那个cell最处于中间位置来决定播放那个吧

**Comment by changsanjiang** [comment]
这样设置正常来说, 不应该出现复用的问题的. 

自动播放那块, 试试下面这个效果
```
SJPlayerAutoplayConfig *config = [SJPlayerAutoplayConfig configWithPlayerSuperviewTag:101 autoplayDelegate:self];
    config.autoplayPosition = SJAutoplayPositionTop; 改成 SJAutoplayPositionMiddle 试试
```

**Comment by changsanjiang** [comment]
@GodzzZZZ 那个复用的问题解决了吗? 没有的话加我QQ 1779609779 吧, 我们QQ聊.

**Comment by changsanjiang** [comment]
SJBaseVideoPlayer 在scrollView上滚动出现和消失时, 默认没有做处理.   
用下面的方式处理一下吧:

```
    _player.playerViewWillAppearExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull videoPlayer) {
        [videoPlayer play];
        videoPlayer.view.hidden = YES;
    };
    
    _player.playerViewWillDisappearExeBlock = ^(__kindof SJBaseVideoPlayer * _Nonnull videoPlayer) {
        [videoPlayer pause];
        videoPlayer.view.hidden = NO;
    };
```
