### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by black1997** [changsanjiang/SJVideoPlayer#76]
使用如下初始化方法、播放不了
  CGRect rect = CGRectMake(0,0, self.view.frame.size.width, 250);
    SJVideoPlayer *play = [SJVideoPlayer lightweightPlayer];
    play.view.frame = rect;
    play.URLAsset = [[SJVideoPlayerURLAsset alloc] initWithURL:[NSURL URLWithString:src]];
    play.URLAsset.title = @"";
    play.URLAsset.alwaysShowTitle = YES;
    play.hideBackButtonWhenOrientationIsPortrait = YES;
    play.pausedToKeepAppearState = YES;
    play.enableFilmEditing = YES;
    [self.view addSubview:play.view];

**Comment by changsanjiang** [comment]
把 player 作为属性强引用一下, 否则出了这个函数, 播放器会被释放的.

**Comment by black1997** [comment]
收到，十分感谢。
