### ISSUE TITLE
SJProgressSlider错误

### ISSUE THREAD

**Issue by black1997** [changsanjiang/SJVideoPlayer#77]
<img width="1296" alt="WX20190327-153828@2x" src="https://user-images.githubusercontent.com/15035749/55058252-67eeb080-50a6-11e9-9cbe-51a41a7cdb2c.png">

老项目、引入后出现改问题、闪退

**Comment by changsanjiang** [comment]
恩, 是因为 NaN 奔溃的.  你那边的库的不是最新的, 更新一下吧.

**Comment by black1997** [comment]
我使用pod管理的，但好像还是2.2.3耶，没有更新。老哥

**Comment by changsanjiang** [comment]
用这个命令安装吧   pod update SJVideoPlayer 

要是网速慢的话, podfile里面改成下面的样子, 再安装
pod 'SJBaseVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJBaseVideoPlayer.git'
pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'
pod 'SJObserverHelper', :git => 'https://gitee.com/changsanjiang/SJObserverHelper.git' 
pod 'SJAttributesFactory', :git => 'https://gitee.com/changsanjiang/SJAttributesFactory.git'

**Comment by black1997** [comment]
十分感谢、十分感谢。老铁、晚上加鸡腿
