### ISSUE TITLE
使用自定义URL，发生播放错误的时候“点击重试”点击后会直接崩溃

### ISSUE THREAD

**Issue by KanveM** [changsanjiang/SJVideoPlayer#78]
能否将 SJBaseVideoPlayer中的 refresh函数 改为执行block的那种?
因为我创建资源的时候使用了AVAssetResourceLoaderDelegate而refresh的时候没有添加delegate,且使用的是自定义scheme，这样就会导致程序直接崩溃 😂

非常感谢你做的这个播放器，功能非常强大哦，希望能添加对AVAssetResourceLoaderDelegate的支持，也就是边下边播

**Comment by changsanjiang** [comment]
用最新的那个版本试试吧, refresh之前重写过实现.
