### ISSUE TITLE
background playback is not working well while playing video list

### ISSUE THREAD

**Issue by szdkkk** [changsanjiang/SJVideoPlayer#80]
I cloned this repo and did changes as below in ViewControllerPlaybackListController.m:
`_player.pauseWhenAppDidEnterBackground = NO;`
then I run PlaybackListController, it continues to play current video in background, but failed to continue to play next video, although the log says it's playing:
`SJBaseVideoPlayer<0x10148e3f0>.SJVideoPlayerPlayStatus.Inactivity(Reason: PlayEnd)
播放列表: 将要播放 - idx = 1
SJBaseVideoPlayer<0x10148e3f0>.SJVideoPlayerPlayStatus.Prepare
2019-04-02 15:42:16.562856+0800 SJVideoPlayer[19750:814377] 84 - -[SJAVMediaPlayAsset dealloc]
SJBaseVideoPlayer<0x10148e3f0>.SJVideoPlayerPlayStatus.ReadyToPlay
SJAVMediaPlaybackController<0x280e14000>.rate == 1.000000
SJAVMediaPlaybackController<0x280e14000>.mute == NO
SJAVMediaPlaybackController<0x280e14000>.playerVolume == 1.000000
SJBaseVideoPlayer<0x10148e3f0>.SJVideoPlayerPlayStatus.Playing`

**Comment by changsanjiang** [comment]
Thanks @szdkkk , this is a bug, I will fix it as soon as possible.

**Comment by changsanjiang** [comment]
Hi @szdkkk,  I just fixed this problem. See demo for details.

**Comment by szdkkk** [comment]
@changsanjiang thanks for quick response! will check it now
