### ISSUE TITLE
设置自动播放无效的问题

### ISSUE THREAD

**Issue by koploop** [changsanjiang/SJVideoPlayer#81]
autoPlayWhenPlayStatusIsReadyToPlay = NO禁止自动播放，第一次是可以的，但是返回后再进入控制器，有很大概率会自动播放。

我看了下返回后，有很多东西没有释放。不知道是否有关。

——————————————

控制器是正常释放了的。log中也显示SJVideoPlayer也已经释放。所以很费解为何再次进入，自动播放的设置就无效了，会自动播放。

![sjvideo](https://user-images.githubusercontent.com/11609831/55677902-4baf0700-5923-11e9-9e96-ef71610f0678.jpg)

**Comment by changsanjiang** [comment]
在 play 方法那里打个断点看看,  应该是有地方调用播放了.  

___

底部如果正常的打印播放 dealloc 的log的话, 那就是正常释放了.   上面这个截图其中像 settings 是单例,  这些是播放器的全局配置用的, 例如图片资源等.

**Comment by changsanjiang** [comment]
尝试一下新版本吧,  2.5.5, 播放控制重构了一遍.
