### ISSUE TITLE
Change periodic time observe interval.

### ISSUE THREAD

**Issue by NobuhitoSuzuki** [changsanjiang/SJVideoPlayer#82]
Hello.
I have implemented a custom control layer.

Now, methods that receive SJVideoPlayerControlLayerDelegate's currentTime are called at intervals of 0.5 seconds.

I want to move the custom slider more smoothly, so I want to shorten this interval.

Can you make this interval customizable?

Thank you for providing a great library.

**Comment by changsanjiang** [comment]
Ok, I'll add it to the next version.

**Comment by NobuhitoSuzuki** [comment]
@changsanjiang Thanks!!!!

**Comment by changsanjiang** [comment]
Hello, @NobuhitoSuzuki, Now you can use it in the new version(2.5.5) to set the `interval`:

```Objective-c
_player.playbackController.refreshTimeInterval = 0.5;
```
