### ISSUE TITLE
更新版本后报错

### ISSUE THREAD

**Issue by daibo789** [changsanjiang/SJVideoPlayer#83]
Property 'isMP3' not found on object of type 'SJVideoPlayerURLAsset *'

**Comment by changsanjiang** [comment]
版本号是多少呢?

**Comment by daibo789** [comment]
> 版本号是多少呢？

ios8.0 版本 2.2.9

**Comment by changsanjiang** [comment]
你那边 `SJBaseVideoPlayer` 可能不是新的, isMP3在新版已经没用了.

**Comment by daibo789** [comment]
![image](https://user-images.githubusercontent.com/37980628/55854864-7f469700-5b98-11e9-9995-69180287cecc.png)


> 你那边 `SJBaseVideoPlayer` 可能不是新的, isMP3在新版已经没用了.

刚装的

**Comment by changsanjiang** [comment]
pod update SJVideoPlayer   这样装吧

**Comment by daibo789** [comment]
> pod update SJVideoPlayer 这样装吧
我再看看
