### ISSUE TITLE
报个 bug

### ISSUE THREAD

**Issue by loveuqian** [changsanjiang/SJVideoPlayer#85]

**Comment by loveuqian** [comment]
*** Assertion failure in +[SJPlayerAutoplayConfig configWithPlayerSuperviewTag:autoplayDelegate:], /Users/wangshengfeng/Documents/cloudmall-5.0/Pods/SJBaseVideoPlayer/SJBaseVideoPlayer/Model/SJPlayerAutoplayConfig.m:14
[Bugly]  Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: autoplayDelegate != nil' 
CRASH: Invalid parameter not satisfying: autoplayDelegate != nil
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: autoplayDelegate != nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001081fe6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010fed0ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001081fe482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000108fbd927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   SJBaseVideoPlayer                   0x000000010d1c763f +[SJPlayerAutoplayConfig configWithPlayerSuperviewTag:autoplayDelegate:] + 623
	5   CloudMall                           0x000000010506696b __43-[CMShowTimelineViewController viewDidLoad]_block_invoke.371 + 75
	6   MJRefresh                           0x000000010c678c88 __28-[MJRefreshHeader setState:]_block_invoke.67 + 168
	7   UIKitCore                           0x000000011b09bf3b -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 847
	8   UIKitCore                           0x000000011b06f8ff -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343
	9   UIKitCore                           0x000000011b06ff21 -[UIViewAnimationState animationDidStop:finished:] + 293
	10  QuartzCore                          0x0000000109ee3de7 _ZN2CA5Layer23run_animation_callbacksEPv + 321
	11  ReactiveCocoa                       0x000000010d041861 RACTraceDispatch + 209
	12  libdispatch.dylib                   0x00000001114ffdb5 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000011150d080 _dispatch_main_queue_callback_4CF + 1540
	14  CoreFoundation                      0x00000001081658a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x000000010815ff56 __CFRunLoopRun + 2310
	16  CoreFoundation                      0x000000010815f302 CFRunLoopRunSpecific + 626
	17  GraphicsServices                    0x000000011406e2fe GSEventRunModal + 65
	18  UIKitCore                           0x000000011abdaba2 UIApplicationMain + 140
	19  CloudMall                           0x000000010580b9d2 main + 146
	20  libdyld.dylib                       0x0000000111574541 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by loveuqian** [comment]
没有找到必现方法
大概操作是，跳到了一个做了 tableView 自动播放的页面
然后又快速退出，就会闪退了

**Comment by changsanjiang** [comment]
配置列表自动播放那块的代码截个图看看吧.

**Comment by loveuqian** [comment]
![image](https://user-images.githubusercontent.com/9745332/56564059-d2c8d400-65df-11e9-8f08-0fda79fae4f5.png)

**Comment by changsanjiang** [comment]
恩, 配置TableView自动播放在那块写的呢?

**Comment by loveuqian** [comment]
![image](https://user-images.githubusercontent.com/9745332/56564225-2b986c80-65e0-11e9-9bb2-0f4a5065d6b5.png)

**Comment by changsanjiang** [comment]
weakSelf 到这里有可能释放了,  这里需要做一下非空判断.  if( !weakSelf ) return;

**Comment by loveuqian** [comment]
好的
