### ISSUE TITLE
偶尔会出现在线视频播放失败的现象

### ISSUE THREAD

**Issue by peterHchina** [changsanjiang/SJVideoPlayer#88]
测试的某些在线视频比较大，大概1G多，播放时很容出现播放失败的现象。麻烦看下是为什么。
🙅‍♂️

**Comment by changsanjiang** [comment]
QQ(1779609779) 私聊发个链接吧, 我测试看看

**Comment by xieweicai** [comment]
> QQ(1779609779) 私聊发个链接吧, 我测试看看

很小的视频，出现播放失败，安卓网页都能播放。
视频链接：https://cdn.1home.online/video/ec63f30db770e60ca620f7e0f76ca164.mp4

**Comment by xieweicai** [comment]
SJAVMediaPlayer.error ==> Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (1885696621), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x28330d7a0 {Error Domain=NSOSStatusErrorDomain Code=1885696621 "(null)" UserInfo={AVErrorFourCharCode='perm'}}}

**Comment by zhangle520** [comment]
所以这个问题怎么解决？
