### ISSUE TITLE
Volume and Brightness Setting

### ISSUE THREAD

**Issue by anhnt92** [changsanjiang/SJVideoPlayer#9]
Hi there,
Please tell me how to disable Volume and Brightness setting at tableview viewctroller. I can't understand example.
Thanks.

**Comment by changsanjiang** [comment]
Please wait 10 minutes.

**Comment by changsanjiang** [comment]
I just added [two properties](https://github.com/changsanjiang/SJBaseVideoPlayer/blob/master/SJBaseVideoPlayer/SJBaseVideoPlayer.h).( line 106 )
Is pushing to trunk, please wait.

**Comment by anhnt92** [comment]
To use, i update pod or something?

**Comment by changsanjiang** [comment]
you can pod update use it.    
In addition, I don't understand the [problem](https://github.com/changsanjiang/SJVideoPlayer/issues/11). Does my demo have the same problem?

**Comment by changsanjiang** [comment]
Sorry, my English is not very good.....😁
