### ISSUE TITLE
更新版本后报错

### ISSUE THREAD

**Issue by KanveM** [changsanjiang/SJVideoPlayer#92]
![屏幕快照 2019-05-19 12 08 55](https://user-images.githubusercontent.com/33738071/57977790-6d2b0480-7a32-11e9-8648-6468ca2f8200.png)

提示多个文件重复

**Comment by changsanjiang** [comment]
pod 'SJAttributesFactory' 和 pod 'SJKVOHelper' 从podfile里面删掉吧.  这两个库合并到另一个库了.

**Comment by KanveM** [comment]
![屏幕快照 2019-05-19 13 07 05](https://user-images.githubusercontent.com/33738071/57978028-0a883780-7a37-11e9-85e2-943ad01d77e3.png)
修改后的podfile

![屏幕快照 2019-05-19 13 06 20](https://user-images.githubusercontent.com/33738071/57978031-11af4580-7a37-11e9-9e2a-a375191df331.png)
提示未找到 SJAttributesFactory。。。

**Comment by KanveM** [comment]
是不是少下载了什么。。。

**Comment by changsanjiang** [comment]
没事, 关掉项目, 重新pod安装就行了.

**Comment by lahala** [comment]
也是pod不上 一直提示少库文件
![Snip20190521_2](https://user-images.githubusercontent.com/9395580/58083139-03098f80-7beb-11e9-8c8f-e45271e785c9.png)

**Comment by KanveM** [comment]
Library not found 可以在build setting中添加库的搜索路径来解决
