### ISSUE TITLE
conflicting types for "sj_view_makeAppear"

### ISSUE THREAD

**Issue by KanveM** [changsanjiang/SJVideoPlayer#96]
![image](https://user-images.githubusercontent.com/33738071/58797091-9aca9d00-8631-11e9-80d0-d3379125fe66.png)
podfile 如上，使用的不是最新版本，之前使用时都没有问题，重建项目时出现下面的问题，求解

**Comment by KanveM** [comment]
![IMG_0496](https://user-images.githubusercontent.com/33738071/58797695-37da0580-8633-11e9-8b9d-98f80afef313.png)
![IMG_0497](https://user-images.githubusercontent.com/33738071/58797762-67890d80-8633-11e9-8d74-1b5c72bb0afe.png)

**Comment by changsanjiang** [comment]
尝试用最新版本的吧, 接口变动很小. 

```ruby
pod 'SJBaseVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJBaseVideoPlayer.git'
pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'
```
