### ISSUE TITLE
快进，拖动的时候，进度条跨度太大，这个是在哪里设置的？

### ISSUE THREAD

**Issue by wty302857194** [changsanjiang/SJVideoPlayer#97]

**Comment by changsanjiang** [comment]
暂时没有接口, 可以先修改一下这里:

![image](https://user-images.githubusercontent.com/25744224/58846334-67c7ee00-86b1-11e9-8805-85a2632a669e.png)

**Comment by wty302857194** [comment]
667 指的是总长度吗？




------------------ 原始邮件 ------------------
发件人: "changsanjiang"<notifications@github.com>; 
发送时间: 2019年6月4日(星期二) 上午10:14
收件人: "changsanjiang/SJVideoPlayer"<SJVideoPlayer@noreply.github.com>; 
抄送: "无根的风"<302857194@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [changsanjiang/SJVideoPlayer] 快进，拖动的时候，进度条跨度太大，这个是在哪里设置的？ (#97)




暂时没有接口, 可以先修改一下这里:

**Comment by wty302857194** [comment]
我改了这个数字感觉没什么变化（不管是大还是小）

**Comment by changsanjiang** [comment]
可能是设置的小了,  你先设置个大一点的, 比如5000试试, 再慢慢让下降

**Comment by changsanjiang** [comment]
你先改源码, 端午的时候我发个版本, 把这个属性添加上去.
