### ISSUE TITLE
centerAdapter 不能 addItem 吗 或者交换位置吗

### ISSUE THREAD

**Issue by Apolla** [changsanjiang/SJVideoPlayer#98]
我想将播放按钮转移到中间，但是用了交换 和 您提供的addItem 貌似都不可以，请问怎么解决呢

**Comment by changsanjiang** [comment]
代码截个图看看

**Comment by Apolla** [comment]
我找到了原因，因为现有的centerContainerView 已经有重播按钮了，并且处于隐藏状态，这个我也是需要的，所有我自己在层级上新加入了一个按钮，使用您回调控制状态
![屏幕快照 2019-06-04 下午4 42 39](https://user-images.githubusercontent.com/14369764/58864751-e3dd2880-86e7-11e9-9b25-8100953d56f9.png)

**Comment by changsanjiang** [comment]
ok
